const CSEBtechNEP21 = [
 {
  coursecode: "CS14103",
  coursetitle: "Web Technology",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
  sem_elect: 1,
  url: `#`,
 },
 {
  coursecode: "MA14102",
  coursetitle: "Engineering Mathematics",
  l: 3,
  t: 1,
  p: 0,
  credits: 4,
  dept: `MATH`,
  sem_elect: 1,
  url: `#`,
 },
 {
  coursecode: "CH14101",
  coursetitle: "Engineering Chemistry",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CHEM`,
  sem_elect: 1,
  url: `#`,
 },
 {
  coursecode: "EC14102",
  coursetitle: "Digital Design",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: `ECE`,
  sem_elect: 1,
  url: `#`,
 },
 {
  coursecode: "CS14102",
  coursetitle: "Programming in C",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
  sem_elect: 1,
  url: `#`,
 },
 {
  coursecode: "EAA14102",
  coursetitle: "EAA -II Swachha Bharat Mission (SBM)",
  l: 0,
  t: 0,
  p: 3,
  credits: 1,
  dept: `CSUG`,
  sem_elect: 1,
  url: `#`,
 },
 {
  coursecode: null,
  coursetitle: null,
  l: "Total",
  t: null,
  p: null,
  credits: 20,
  dept: null,
  sem_elect: null,
  url: `#`,
 },
 {
  coursecode: "CS24102",
  coursetitle: "Information Technology Workshop Web",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
  sem_elect: 2,
  url: `#`,
 },
 {
  coursecode: "HS24101",
  coursetitle: "Communicative English",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `HSS`,
  sem_elect: 2,
  url: `#`,
 },
 {
  coursecode: "PH24101",
  coursetitle: "Engineering Physics",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `PHY`,
  sem_elect: 2,
  url: `#`,
 },
 {
  coursecode: "CS24108",
  coursetitle: "Computer Organization",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
  sem_elect: 2,
  url: `#`,
 },
 {
  coursecode: "MA241XX",
  coursetitle: "Engineering Mathematics II",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: `MATH`,
  sem_elect: 2,
  url: `#`,
 },
 {
  coursecode: "EAA24101",
  coursetitle: "EAA - I Sports/Innovative Project/NCC/NSS",
  l: 0,
  t: 0,
  p: 3,
  credits: 1,
  dept: `SAC`,
  sem_elect: 2,
  url: `#`,
 },
 {
  coursecode: null,
  coursetitle: null,
  l: "Total",
  t: null,
  p: null,
  credits: 20,
  dept: null,
  sem_elect: 2,
  url: `#`,
 },
 {
  sem_elect: 3,
  coursecode: "CS34104",
  coursetitle: "Data Structures",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
  url: `#`,
 },
 {
  sem_elect: 3,
  coursecode: "CS34105",
  coursetitle: "Object Oriented Programming",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: `CSUG`,
  url: `#`,
 },
 {
  sem_elect: 3,
  coursecode: "CS34109",
  coursetitle: "Database Management Systems",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
  url: `#`,
 },
 {
  sem_elect: 3,
  coursecode: "CS34110",
  coursetitle: "Discrete Maths and Graph Theory",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: `CSUG`,
  url: `#`,
 },
 {
  sem_elect: 3,
  coursecode: "CS34111",
  coursetitle: "Operating Systems",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
  url: `#`,
 },
 {
  sem_elect: 3,
  coursecode: "HS34151",
  coursetitle: "Professional Ethics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: `CSUG`,
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: null,
  coursetitle: null,
  l: "Total",
  t: null,
  p: null,
  credits: 21,
  dept: null,
  url: `#`,
 },
 {
  sem_elect: 4,
  coursecode: "CS44112",
  coursetitle: "Artificial Intelligence",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
  url: `#`,
 },
 {
  sem_elect: 4,
  coursecode: "CS44113",
  coursetitle: "Computer Networks",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
  url: `#`,
 },
 {
  sem_elect: 4,
  coursecode: "CS44114",
  coursetitle: "Automata Theory and compiler design",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
  url: `#`,
 },
 {
  sem_elect: 4,
  coursecode: "CS44115",
  coursetitle: "Design and Analysis of Algorithms",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
  url: `#`,
 },
 {
  sem_elect: 4,
  coursecode: "OP44XXX",
  coursetitle: "Open Electives-1 /MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: `CSUG`,
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: null,
  coursetitle: null,
  l: "Total",
  t: null,
  p: null,
  credits: 19,
  dept: null,
  url: `#`,
 },
 {
  url: `#`,
  sem_elect: 5,
  coursecode: "CS54116",
  coursetitle: "Software Enginnering",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
 },
 {
  url: `#`,
  sem_elect: 5,
  coursecode: "CS54117",
  coursetitle: "Internet of Things",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
 },
 {
  url: `#`,
  sem_elect: 5,
  coursecode: "CS54118",
  coursetitle: "Machine Learning",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
 },
 {
  url: `#`,
  sem_elect: 5,
  coursecode: "CS54119",
  coursetitle: "Information Security",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: `CSUG`,
 },
 {
  url: `#`,
  sem_elect: 5,
  coursecode: "CS54XXX",
  coursetitle: "Dept Elective -1/ MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: `CSUG`,
 },
 {
  url: `#`,
  sem_elect: 5,
  coursecode: "OP54XXX",
  coursetitle: "Open Elective - 2 MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: `CSUG`,
 },
 {
  url: `#`,
  sem_elect: null,
  coursecode: null,
  coursetitle: null,
  l: "Total",
  t: null,
  p: null,
  credits: 21,
  dept: null,
 },
 {
  url: `#`,
  sem_elect: 6,
  coursecode: "CS64120",
  coursetitle: "Data Mining",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: `CSUG`,
 },
 {
  url: `#`,
  sem_elect: 6,
  coursecode: "CS64121",
  coursetitle: "Cloud Computing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: `CSUG`,
 },
 {
  url: `#`,
  sem_elect: 6,
  coursecode: "CS641XX",
  coursetitle: "Dept. Electives - 2/ MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: `CSUG`,
 },
 {
  url: `#`,
  sem_elect: 6,
  coursecode: "OP64XXX",
  coursetitle: "Open Elective- 3 / MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: `CSUG`,
 },
 {
  url: `#`,
  sem_elect: 6,
  coursecode: "CS64123",
  coursetitle: "Project",
  l: 0,
  t: 0,
  p: 12,
  credits: 6,
  dept: `CSUG`,
 },
 {
  url: `#`,
  sem_elect: null,
  coursecode: null,
  coursetitle: null,
  l: "Total",
  t: null,
  p: null,
  credits: 19,
  dept: null,
 },
 {
  sem_elect: null,
  dept: null,
  coursecode: null,
  coursetitle: <strong>Department Electives</strong>,
  l: null,
  t: null,
  p: null,
  credits: null,
  url: null,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4131",
  coursetitle: "Cryptography",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4132",
  coursetitle: "Distributed Database Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4133",
  coursetitle: "Operations Research",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4134",
  coursetitle: "Digital Image Processing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4135",
  coursetitle: "Intrusion Detection",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4136",
  coursetitle: "Real Time Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4137",
  coursetitle: "Computer Vision",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4138",
  coursetitle: "Social Networks",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4139",
  coursetitle: "Big Data Analytics",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4140",
  coursetitle: "Network Security",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4141",
  coursetitle: "Object Oriented Systems Development",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4142",
  coursetitle: "Computer Graphics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4143",
  coursetitle: "Malware Analysis",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4144",
  coursetitle: "Digital Signal Processing",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4145",
  coursetitle: "Microprocesor and Microcontrollers",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4146",
  coursetitle: "Distributed Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4147",
  coursetitle: "Virtual Reality",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "HSXXXXX",
  coursetitle: "Intellectual Property Rights",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4149",
  coursetitle: "Blockchain Technology",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: "EL",
  dept: `CSUG`,
  coursecode: "CSX4150",
  coursetitle: "Biometrics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  url: `#`,
 },
 {
  sem_elect: null,
  dept: null,
  coursecode: null,
  coursetitle: <strong>Open Elective other than CSE Minor(Iot)</strong>,
  l: null,
  t: null,
  p: null,
  credits: null,
  url: null,
 },
 {
  sem_elect: null,
  coursecode: "CS34104",
  coursetitle: "Data Structures",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: "CS44113",
  coursetitle: "Computer Networks",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: "CS54117",
  coursetitle: "Internet of Things",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: "CSX41XX",
  coursetitle: "Dept Elective 1/ MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: "CSX41XX",
  coursetitle: "Dept Elective 2/ MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: "CSX41XX",
  coursetitle: "Dept Elective 3/ MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: null,
  coursetitle: null,
  l: "Total",
  t: null,
  p: null,
  credits: 21,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  dept: null,
  coursecode: null,
  coursetitle: <strong>Open Elective other than CSE Minor(AI)</strong>,
  l: null,
  t: null,
  p: null,
  credits: null,
  url: null,
 },
 {
  sem_elect: null,
  coursecode: "CS34104",
  coursetitle: "Data Structures",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: "CS44112",
  coursetitle: "Artificial Intelligence",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: "CS54118",
  coursetitle: "Machine Learning",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: "CSX41XX",
  coursetitle: "Dept Elective 1/ MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: "CSX41XX",
  coursetitle: "Dept Elective 2/ MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: "CSX41XX",
  coursetitle: "Dept Elective 3/ MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "XX",
  url: `#`,
 },
 {
  sem_elect: null,
  coursecode: null,
  coursetitle: null,
  l: "Total",
  t: null,
  p: null,
  credits: 21,
  dept: null,
  url: `#`,
 },
]
export default CSEBtechNEP21
