const Mtech = [
 {
  dept: "M.Tech(CSE) Semester- I",
  "CCMT Code": null,
  Group: null,
  sem_elect: null,
  coursecode: null,
  coursetitle: null,
  l: null,
  t: null,
  p: null,
  credits: null,
  //   "FM": null
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "Core",
  sem_elect: "1",
  coursecode: "1CS601",
  coursetitle: "Advanced Data Structure and File systems",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "Core",
  sem_elect: "1",
  coursecode: "1CS602",
  coursetitle: "Advanced Computer Networks",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: "1",
  coursecode: "1CS6xx",
  coursetitle: "Elective-I",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: "1",
  coursecode: "1CS6xx",
  coursetitle: "Elective-II",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: "1",
  coursecode: "CS6xx",
  coursetitle: "Elective-III",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "Lab",
  sem_elect: "1",
  coursecode: "1CS603",
  coursetitle: "Advanced Computer Lab-I",
  l: "0",
  t: "0",
  p: "6",
  credits: "4",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: null,
  sem_elect: "1",
  coursecode: null,
  coursetitle: "Total Semester Credit",
  l: "15",
  t: "0",
  p: "6",
  credits: "19",
  FM: "600",
 },
 {
  dept: "M.Tech(CSE) Semester- II",
  "CCMT Code": null,
  Group: null,
  sem_elect: null,
  coursecode: null,
  coursetitle: null,
  l: null,
  t: null,
  p: null,
  credits: null,
  FM: null,
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "Core",
  sem_elect: "2",
  coursecode: "2CS604",
  coursetitle: "Advanced Database Management System",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: "2",
  coursecode: "2CS6xx",
  coursetitle: "Elective-IV",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: "2",
  coursecode: "2CS6xx",
  coursetitle: "Elective-V",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: "2",
  coursecode: "2CS6xx",
  coursetitle: "Elective-VI",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: "2",
  coursecode: "2CS6xx",
  coursetitle: "Elective - VII",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "Lab",
  sem_elect: "2",
  coursecode: "2CS605",
  coursetitle: "Advanced Computer Lab-II",
  l: "0",
  t: "0",
  p: "6",
  credits: "4",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "Lab",
  sem_elect: "2",
  coursecode: "2CS691",
  coursetitle: "Seminar",
  l: "0",
  t: "0",
  p: "3",
  credits: "2",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: null,
  sem_elect: "2",
  coursecode: null,
  coursetitle: "Total Semester Credit",
  l: "15",
  t: "0",
  p: "9",
  credits: "21",
  FM: "700",
 },
 {
  dept: "M.Tech(CSE) Semester-III",
  "CCMT Code": null,
  Group: null,
  sem_elect: null,
  coursecode: null,
  coursetitle: null,
  l: null,
  t: null,
  p: null,
  credits: null,
  FM: null,
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "Lab",
  sem_elect: "3",
  coursecode: "3CS692",
  coursetitle: "Seminar and Comprehensive Viva",
  l: "0",
  t: "0",
  p: "3",
  credits: "2",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "Lab",
  sem_elect: "3",
  coursecode: "3CS693",
  coursetitle: "Dissertation (to be continued in 4th Sem)",
  l: "0",
  t: "0",
  p: "16",
  credits: "8",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: null,
  sem_elect: "3",
  coursecode: null,
  coursetitle: "Total Semester Credit",
  l: "0",
  t: "0",
  p: "19",
  credits: "10",
  FM: "200",
 },
 {
  dept: "M.Tech(CSE) Semester-IV",
  "CCMT Code": null,
  Group: null,
  sem_elect: null,
  coursecode: null,
  coursetitle: null,
  l: null,
  t: null,
  p: null,
  credits: null,
  FM: null,
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "Lab",
  sem_elect: "4",
  coursecode: "CS694",
  coursetitle: "Seminar and Comprehensive Viva",
  l: "0",
  t: "0",
  p: "3",
  credits: "2",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "Lab",
  sem_elect: "4",
  coursecode: "4CS695",
  coursetitle: "Dissertation",
  l: "0",
  t: "0",
  p: "15",
  credits: "10",
  FM: "100",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: null,
  sem_elect: "4",
  coursecode: null,
  coursetitle: "Total Semester Credit",
  l: "0",
  t: "0",
  p: "18",
  credits: "12",
  FM: "200",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: null,
  sem_elect: null,
  coursecode: null,
  coursetitle: "Cumulative Total Credit",
  l: null,
  t: null,
  p: null,
  credits: "62",
  FM: "1700",
 },
 {
  dept: "List of Elective I, II, III, IV, V, VI & VII",
  "CCMT Code": null,
  Group: null,
  sem_elect: null,
  coursecode: null,
  coursetitle: null,
  l: null,
  t: null,
  p: null,
  credits: null,
  FM: null,
 },
 // {
 //   "dept": "dept",
 //   "CCMT Code": "CCMT Code",
 //   "Group": "Group",
 //   "sem_elect": "sem_elect",
 //   "coursecode": "coursecode",
 //   "coursetitle": "coursetitle",
 //   "l": "l",
 //   "t": "t",
 //   "p": "p",
 //   "credits": "credits",
 //   "FM": "Elective Pool"
 // },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS621",
  coursetitle: "Artificial Intelligence and Intelligent Systems",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "AI",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS622",
  coursetitle: "Real Time Systems",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "EVD",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS623",
  coursetitle: "Data Encryption and Compression",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "INS",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS624",
  coursetitle: "Analysis and Design of Information Systems",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "IR",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS625",
  coursetitle: "Information Retrieval",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "IR",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS626",
  coursetitle: "Advanced Computer Graphics",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "MS",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS627",
  coursetitle: "Parallel Algorithm",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "PC",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS628",
  coursetitle: "Advanced Software Engineering",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "PRM",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS629",
  coursetitle: "Theory of Computer Science",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "TOC",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS630",
  coursetitle: "Compiler Design",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "TOC",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS631",
  coursetitle: "Genetic Algorithms",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "AI",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS632",
  coursetitle: "Neural Networks",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "AI",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS633",
  coursetitle: "Ubiquitous and Pervasive Computing",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "EVD",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS634",
  coursetitle: "VLSI Design",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "EVD",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS635",
  coursetitle: "Cryptography and Network Security",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "INS",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS636",
  coursetitle: "Geographical Information Systems",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "IR",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS637",
  coursetitle: "Data Warehousing and Mining",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "IR",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS638",
  coursetitle: "Multimedia Systems",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "MS",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS639",
  coursetitle: "Image Processing",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "MS",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS640",
  coursetitle: "Grid and Cluster Computing",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "PC",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS641",
  coursetitle: "Quantum Computing",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "PC",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS642",
  coursetitle: "DNA Computing",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "PC",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS643",
  coursetitle: "Advanced Software Project Management",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "PRM",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS644",
  coursetitle: "Semantic Web",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "PRM",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS645",
  coursetitle: "Advanced Graph Theory",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "TOC",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS646",
  coursetitle: "Approximation Algorithms",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "TOC",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS647",
  coursetitle: "Advanced Computer Architecture",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "EVD",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS648",
  coursetitle: "Distributed Systems",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "PC",
 },
 {
  dept: "CSPG",
  "CCMT Code": "CTXG",
  Group: "EL-x",
  sem_elect: null,
  coursecode: "CS649",
  coursetitle: "Object Oriented Modeling and Design",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
  FM: "EVD",
 },
]

export default Mtech
