const Course_DD_DataScience = [
 {
  coursecode: "CS14102",
  coursetitle: "Programming in C",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "MA14102",
  coursetitle: "Engineering Mathematics I",
  l: 3,
  t: 1,
  p: 0,
  credits: 4,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "CH14101",
  coursetitle: "Engineering Chemistry",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "EC14102",
  coursetitle: "Digital Design",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "CS14106",
  coursetitle: "Information Technology  Workshop",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "EAA14102",
  coursetitle: "EAA -II Swachha Bharat Mission (SBM)",
  l: 0,
  t: 0,
  p: 2,
  credits: 1,
  dept: "CSE",
  sem_elect: 1,
 },
 {
  coursecode: "CS24107",
  coursetitle: "Web Technology",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "HS24101",
  coursetitle: "Communicative English",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "PH24101",
  coursetitle: "Engineering Physics",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "CS24108",
  coursetitle: "Computer Organization",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "MA24102",
  coursetitle: "Engineering Mathematics II",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "EAA24101",
  coursetitle: "EAA - I Sports/Innovative Project/NCC/NSS",
  l: 0,
  t: 0,
  p: 2,
  credits: 1,
  dept: "CSE",
  sem_elect: 2,
 },
 {
  coursecode: "CS34104",
  coursetitle: "Data Structures",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "CS34105",
  coursetitle: "Object Oriented Programming",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "CS34109",
  coursetitle: "Database Management Systems",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "CS34110",
  coursetitle: "Discrete Mathematics and Graph Theory",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "CS34111",
  coursetitle: "Operating Systems",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "HS34151",
  coursetitle: "Social and Professional Ethics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: 3,
 },
 {
  coursecode: "CS44112",
  coursetitle: "Artificial Intelligence",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "CS44113",
  coursetitle: "Computer Networks",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "CS44114",
  coursetitle: "Automata Theory and compiler design",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "CS44115",
  coursetitle: "Design and Analysis of Algorithms",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "OP44XXX",
  coursetitle: "Open Electives-1 ",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "CSE",
  sem_elect: 4,
 },
 {
  coursecode: "CS54116",
  coursetitle: "Software Enginnering",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "CS54117",
  coursetitle: "Internet of Things",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "CS54118",
  coursetitle: "Machine Learning",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "CS54119",
  coursetitle: "Information Security",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "CS54XXX",
  coursetitle: "Dept Elective - I",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "OP54XXX",
  coursetitle: "MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "CSE",
  sem_elect: 5,
 },
 {
  coursecode: "CS64120",
  coursetitle: "Data Mining",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 6,
 },
 {
  coursecode: "CS64121",
  coursetitle: "Cloud Computing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: 6,
 },
 {
  coursecode: "CS641XX",
  coursetitle: "Dept. Elective - II",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "CSE",
  sem_elect: 6,
 },
 {
  coursecode: "OP64XXX",
  coursetitle: "MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "CSE",
  sem_elect: 6,
 },
 {
  coursecode: "CS64123",
  coursetitle: "Project",
  l: 0,
  t: 0,
  p: 12,
  credits: 6,
  dept: "CSE",
  sem_elect: 6,
 },
 {
  coursecode: "CS74127",
  coursetitle: "Mathematical Foundations of Data Science",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 7,
 },
 {
  coursecode: "CS74128",
  coursetitle: "Pattern Recognition",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 7,
 },
 {
  coursecode: "CS74XXX",
  coursetitle: "Dept. Elective-I",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "CSE",
  sem_elect: 7,
 },
 {
  coursecode: "CS74XXX",
  coursetitle: "Dept. Elective-II",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "CSE",
  sem_elect: 7,
 },
 {
  coursecode: "CS74XXX",
  coursetitle: "MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "CSE",
  sem_elect: 7,
 },
 {
  coursecode: "CS74129",
  coursetitle: "Technical Seminar and Report Writing",
  l: 0,
  t: 0,
  p: 4,
  credits: 2,
  dept: "CSE",
  sem_elect: 7,
 },
 {
  coursecode: "CS84130",
  coursetitle: "Natural Language Processing",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 8,
 },
 {
  coursecode: "CS84131",
  coursetitle: "Deep Learning",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 8,
 },
 {
  coursecode: "CS84132",
  coursetitle: "Data Visualization Techniques",
  l: 3,
  t: 0,
  p: 2,
  credits: 4,
  dept: "CSE",
  sem_elect: 8,
 },
 {
  coursecode: "CS84XXX",
  coursetitle: "Dept. Elective-III",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "CSE",
  sem_elect: 8,
 },
 {
  coursecode: "CS84XXX",
  coursetitle: "Dept Elective-IV",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "CSE",
  sem_elect: 8,
 },
 {
  coursecode: "CS84XXX",
  coursetitle: "MOOC",
  l: "X",
  t: "X",
  p: "X",
  credits: 3,
  dept: "CSE",
  sem_elect: 8,
 },
 {
  coursecode: "CS94133",
  coursetitle: "Industrial Training / Project (to be continued in 10th Sem)",
  l: 0,
  t: 0,
  p: 20,
  credits: 10,
  dept: "CSE",
  sem_elect: 9,
 },
 {
  coursecode: "CS104134",
  coursetitle: "Industrial Training / Project",
  l: 0,
  t: 0,
  p: 24,
  credits: 12,
  dept: "CSE",
  sem_elect: 10,
 },
 {
  coursecode: "CSX4145",
  coursetitle: "Distributed Database Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4146",
  coursetitle: "Operations Research",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4147",
  coursetitle: "Digital Image Processing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4148",
  coursetitle: "Intrusion Detection",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4149",
  coursetitle: "Real Time Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4150",
  coursetitle: "Computer Vision",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4151",
  coursetitle: "Social Networks",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4152",
  coursetitle: "Big Data Analytics",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4153",
  coursetitle: "Network Security",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4154",
  coursetitle: "Object Oriented Systems Development",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4155",
  coursetitle: "Computer Graphics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4156",
  coursetitle: "Malware Analysis",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4157",
  coursetitle: "Microprocesor and Microcontrollers",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4158",
  coursetitle: "Distributed Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4159",
  coursetitle: "Virtual Reality",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4160",
  coursetitle: "Intellectual Property Rights",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4161",
  coursetitle: "Blockchain Technology",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4162",
  coursetitle: "Biometrics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4163",
  coursetitle: "Recommendation Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4164",
  coursetitle: "Computer System Parallelism",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4165",
  coursetitle: "Advanced Algorithms",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4166",
  coursetitle: "File System Forensic ",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4167",
  coursetitle: "Distributed Operating Systems ",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4171",
  coursetitle: "Adversarial ML",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4172",
  coursetitle: "Digital Signal Processing  ",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4173",
  coursetitle: "IOT Systems ",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4174",
  coursetitle: "Nature Inspired Computing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4175",
  coursetitle: "Image Processing Techniques",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4176",
  coursetitle: "Bioinformatics",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4177",
  coursetitle: "Information Retrieval",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4178",
  coursetitle: "Computer Vision",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4179",
  coursetitle: "Reinforcement Learning",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4180",
  coursetitle: "Social Networks",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4181",
  coursetitle: "Recommendation Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4182",
  coursetitle: "Speech Processing",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4183",
  coursetitle: "Malware Analysis",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4184",
  coursetitle: "Network Security ",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4185",
  coursetitle: "Intrusion Detection ",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4186",
  coursetitle: "Time Series Analysis",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4187",
  coursetitle: "Big Data Analytics",
  l: 2,
  t: 0,
  p: 2,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4188",
  coursetitle: "Multimedia Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4189",
  coursetitle: "Biometric Security",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4190",
  coursetitle: "Federated Learning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4191",
  coursetitle: "Knowledge Representation & Reasoning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "CSX4192",
  coursetitle: "Decision Support Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
 {
  coursecode: "HSXXXXX",
  coursetitle: "Intellectual Property Rights",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  dept: "CSE",
  sem_elect: "EL",
 },
]

export default Course_DD_DataScience
