const CSEBtechCourseStructure = [
 // {
 //   dept: `Deptt`,
 //   sem_elect: `Sem/Electives`,
 //   coursecode: `Course Code`,
 //   coursetitle: `Course Title`,
 //   l: `L`,
 //   t: `T`,
 //   p: `P`,
 //   credits: `Credits`,
 // },
 {
  dept: `CSUG`,
  sem_elect: `1`,
  coursecode: `HS1401`,
  url: `#`,
  coursetitle: `Science, Society and Ethical values`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `1`,
  coursecode: `MA1401`,
  url: `#`,
  coursetitle: `Engineering Mathematics I`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `1`,
  coursecode: `CH1401`,
  url: `#`,
  coursetitle: `Engineering Chemistry`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `1`,
  coursecode: `CHL1401`,
  url: `#`,
  coursetitle: `Chemistry Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `1`,
  coursecode: `EC1401`,
  url: `#`,
  coursetitle: `Elements of Electronics  Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `1`,
  coursecode: `ECL1401`,
  url: `#`,
  coursetitle: `EC Workshop`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `1`,
  coursecode: `CS1401`,
  url: `#`,
  coursetitle: `Introduction to computing`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `1`,
  coursecode: `CSL1401`,
  url: `#`,
  coursetitle: `Computing lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `1`,
  coursecode: `MEL1401`,
  url: `#`,
  coursetitle: `Engineering Graphics Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `1`,
  coursecode: `EAA1401`,
  url: `#`,
  coursetitle: `EAA-Sports/Innovative project`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `2`,
  coursecode: `HS2401`,
  url: `#`,
  coursetitle: `Communicative English`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `2`,
  coursecode: `HSL2401`,
  url: `#`,
  coursetitle: `Language lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `2`,
  coursecode: `MA2401`,
  url: `#`,
  coursetitle: `Engineering Mathematics II`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `2`,
  coursecode: `PH2401`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/phyl.docx`,
  coursetitle: `Engineering Physics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `2`,
  coursecode: `PHL2401`,
  url: `#`,
  coursetitle: `Physics Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `2`,
  coursecode: `EE2401`,
  url: `#`,
  coursetitle: `Elements of Electrical Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `2`,
  coursecode: `EEL2401`,
  url: `#`,
  coursetitle: `EE Workshop`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `2`,
  coursecode: `CS2401`,
  url: `#`,
  coursetitle: `Object Oriented Programming`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `2`,
  coursecode: `CSL2401`,
  url: `#`,
  coursetitle: `Object Oriented Programming Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  dept: `CSUG`,
  sem_elect: `2`,
  coursecode: `MEL2401`,
  url: `#`,
  coursetitle: `Workshop practice`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  dept: `CSUG`,
  sem_elect: `2`,
  coursecode: `EAA2401`,
  url: `#`,
  coursetitle: `EAA-Swachha Bharat Mission (SBM)`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `3`,
  coursecode: `CS3401`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS3401_Data Structures.docx`,
  coursetitle: `Data Structures`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CSUG`,
  sem_elect: `3`,
  coursecode: `CS3402`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS3402_Discrete Mathematics&Graph Theory.docx`,
  coursetitle: `Discrete Mathematics and Graph Theory`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CSUG`,
  sem_elect: `3`,
  coursecode: `CS3403`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS3403_WebTechnology.docx`,
  coursetitle: `Web Technology`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `3`,
  coursecode: `EC34XX`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/EC34XX_Digital Logic and Computer Organization.docx`,
  coursetitle: `Digital Logic and Computer Organization`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `3`,
  coursecode: `MA34XX`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/MA34XX_Probability & Statistics.docx`,
  coursetitle: `Probability & Statistics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `3`,
  coursecode: `CSL3401`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSL3401_Data Structures Lab.docx`,
  coursetitle: `Data Structures Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `3`,
  coursecode: `CSL3403`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSL3403_Web Technology Lab.docx`,
  coursetitle: `Web Technology Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `3`,
  coursecode: `ECL34XX`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/ECL34XX_Digital Logic and Computer OrganizationLab.docx`,
  coursetitle: `Digital Logic and Computer Organization Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `3`,
  coursecode: `CE34XX`,
  url: `#`,
  coursetitle: `Environmental Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `4`,
  coursecode: `CS44XX`,
  coursetitle: `Professional Elective I`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `4`,
  coursecode: `CS4401`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS4401_ComputerArchitecture.docx`,
  coursetitle: `Computer Architecture`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `4`,
  coursecode: `XX44XX`,
  coursetitle: `Open Elective I/MOOCS`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `4`,
  coursecode: `CS4402`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS4402_Formal Languages & Automata Theory.docx`,
  coursetitle: `Formal Languages and Automata Theory`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CSUG`,
  sem_elect: `4`,
  coursecode: `CS4403`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS4403_Design and Analysis of Algorithms.docx`,
  coursetitle: `Design and Analysis of Algorithms`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CSUG`,
  sem_elect: `4`,
  coursecode: `CS4404`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS4404_Operating System.docx`,
  coursetitle: `Operating Systems`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CSUG`,
  sem_elect: `4`,
  coursecode: `CSL4403`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSL4403_Design & Analysis of Algorithms Lab.docx`,
  coursetitle: `Design & Analysis of Algorithms Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `4`,
  coursecode: `CSL4404`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSL4404_OperatingSystemsLab.docx`,
  coursetitle: `Operating System Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `5`,
  coursecode: `CS5401`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS5401_Database Management Systems.docx`,
  coursetitle: `Database Management Systems`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CSUG`,
  sem_elect: `5`,
  coursecode: `CS5402`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS5402_Artificial Intelligence.docx`,
  coursetitle: `Artificial Intelligence`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `5`,
  coursecode: `CS5403`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS5403_ComputerNetworks.docx`,
  coursetitle: `Computer Networks`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },

 {
  dept: `CSUG`,
  sem_elect: `5`,
  coursecode: `XX54XX`,
  coursetitle: `Open Elective IV/MOOCS`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `5`,
  coursecode: `CS54XX`,
  coursetitle: `Professional Elective II`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `5`,
  coursecode: `CS5404`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS5404_CompilerDesign.docx`,
  coursetitle: `Compiler Design`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `5`,
  coursecode: `CSL5401`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSL5401_Database Management Systems Lab.docx`,
  coursetitle: `Database Management Systems Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  dept: `CSUG`,
  sem_elect: `5`,
  coursecode: `CSL5402`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSL5402_Artificial Intelligence Lab.docx`,
  coursetitle: `Artificial Intelligence Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `5`,
  coursecode: `CSL5403`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSL5403_ComputerNetworkLab.docx`,
  coursetitle: `Computer Networks Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  dept: `CSUG`,
  sem_elect: `5`,
  coursecode: `CSL5404`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSL5404_CompilerDesignLab.docx`,
  coursetitle: `Compiler Design Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `6`,
  coursecode: `CS6401`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS6401_ComputerGraphics.docx`,
  coursetitle: `Computer Graphics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `6`,
  coursecode: `CSL6401`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSL6401_ComputerGraphics lab.docx`,
  coursetitle: `Computer Graphics lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  dept: `CSUG`,
  sem_elect: `6`,
  coursecode: `XX64XX`,
  coursetitle: `Open Elective II/MOOCS`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `6`,
  coursecode: `CS6402`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS6402_Software_Engineering.docx`,
  coursetitle: `Software Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `6`,
  coursecode: `CSL6402`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSL6402_SoftwareEngineeringLab.docx`,
  coursetitle: `Software Engineering lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `6`,
  coursecode: `CS6403`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS6403_Data Mining and Warehousing.docx`,
  coursetitle: `Data Mining And Warehousing`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },

 {
  dept: `CSUG`,
  sem_elect: `6`,
  coursecode: `CS6404`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS6404_Information Security.docx`,
  coursetitle: `Information Security`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `6`,
  coursecode: `CS64XX`,
  coursetitle: `Professional Elective III`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `6`,
  coursecode: `CS6490`,
  coursetitle: `Minor Project I`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `6`,
 },
 {
  dept: `CSUG`,
  sem_elect: `7`,
  coursecode: `CS74XX`,
  coursetitle: `Professional Elective IV`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `7`,
  coursecode: `CS7401`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CS7401_IoT.docx`,
  coursetitle: `IOT`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `7`,
  coursecode: `CS7401`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSL7401_IoT Lab.docx`,
  coursetitle: `IOT lab`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `7`,
  coursecode: `CS74XX`,
  coursetitle: `Professional Elective V`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `7`,
  coursecode: `XX74XX`,
  coursetitle: `Open Elective III/MOOCS`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `7`,
  coursecode: `CS7491`,
  coursetitle: `Minor Project II`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `6`,
 },
 {
  dept: `CSUG`,
  sem_elect: `7`,
  coursecode: `CS7492`,
  coursetitle: `Industrial Training (4 to 6 weeks after 6th Sem)`,
  l: `0`,
  t: `0`,
  p: `0`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `7`,
  coursecode: `CS7493`,
  coursetitle: `Seminar and Technical Writing`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `1`,
 },
 {
  dept: `CSUG`,
  sem_elect: `8`,
  coursecode: `CS84XX`,
  coursetitle: `Professional Elective VI`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `8`,
  coursecode: `CSL8494`,
  coursetitle: `Major Project & Comprehensive Viva`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `12`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX430`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX430_Semantic Web.docx`,
  coursetitle: `Semantic  Web`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX431`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX431_Natural Language Processing.docx`,
  coursetitle: `Natural Language Processing`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX432`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX432_Computational Intelligence.docx`,
  coursetitle: `Computational Intelligence`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX433`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX433_Pattern Recognition and Machine Learning.docx`,
  coursetitle: `Pattern Recognition and Machine Learning`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX434`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX434_Mobile and Web Applications.docx`,
  coursetitle: `Mobile and Web Applications`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX435`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX435_E-Governance.docx`,
  coursetitle: `E-Governance`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX436`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX436_Cryptography.docx`,
  coursetitle: `Cryptography`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX437`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX437_Distributed Database Systems.docx`,
  coursetitle: `Distributed Database Systems`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX438`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX438_Computational Geometry.docx`,
  coursetitle: `Computational Geometry`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX439`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX439_MachineLearning.docx`,
  coursetitle: `Machine Learning`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX440`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX440_Operations Research.docx`,
  coursetitle: `Operations Research`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX441`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX441_Digital Image Processing.docx`,
  coursetitle: `Digital Image Processing`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX442`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX442_Intrusion Detection.docx`,
  coursetitle: `Intrusion Detection`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX443`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX443_Computational_Biology.docx`,
  coursetitle: `Computational Biology`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX444`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX444_Real Time System.docx`,
  coursetitle: `Real Time Systems`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX445`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX445_Distributed Algorithms.docx`,
  coursetitle: `Distributed Algorithms`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX446`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX446_ADVANCED ALGORITHMS.docx`,
  coursetitle: `Advanced Algorithms`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX447`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX447_Computer Vision.docx`,
  coursetitle: `Computer Vision`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX448`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX448 Text Mining.docx`,
  coursetitle: `Text Mining`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX449`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX449_Data_Science.docx`,
  coursetitle: `Data Science`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX450`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX450 Social Network.docx`,
  coursetitle: `Social Networks`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX451`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX451_Big Data.docx`,
  coursetitle: `Big Data`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX452`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX452_Recommendation_Systems.docx`,
  coursetitle: `Recommendation Systems`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX453`,
  url: ` ./cse/CSX453_Network Security.docx`,
  coursetitle: `Network Security`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX454`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX454_DistributedEventBasedSystems.docx`,
  coursetitle: `Distributed Event Based Systems`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX455`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX455_ApproximationAlgorithms.docx`,
  coursetitle: `Approximation Algorithms`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX456`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX456_Advanced Data Mining.docx`,
  coursetitle: `Advanced Data Mining`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX457`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX457_Cloud Computing.docx`,
  coursetitle: `Cloud Computing`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX458`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX458_Wireless Sensor Networks.docx`,
  coursetitle: `Wireless Sensor Networks`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX459`,
  url: ` ./cse/CSX459_WebMining.docx`,
  coursetitle: `Web Mining`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX460`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX460_Object Oriented Systems Development.docx`,
  coursetitle: `Object Oriented Systems Development`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX461`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX461_Wireless_Networks.docx`,
  coursetitle: `Wireless Networks`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX462`,
  url: `${process.env.GATSBY_BASE_URL}cse/syllabus/CSX462_Mobile Communication.docx`,
  coursetitle: `Mobile Communication`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX463`,
  coursetitle: `Introduction to Digital Signal Processing`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX464`,
  coursetitle: `Introduction to Communication System`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX465`,
  coursetitle: `Introduction to Control System`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX466`,
  coursetitle: `Random Processes and Linear Algebra`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX467`,
  coursetitle: `Microprocesor and Microcontrollers`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX468`,
  coursetitle: `Introduction to Robotics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX469`,
  coursetitle: `Virtual Reality`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX470`,
  coursetitle: `Software Testing and Debugging`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX471`,
  coursetitle: `Data Compression`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX472`,
  coursetitle: `Ontology Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX473`,
  coursetitle: `Blockchain Technology`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX474`,
  coursetitle: `Biometrics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX475`,
  coursetitle: `Data Analytics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CSX476`,
  coursetitle: `Numerical Analysis`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `HSX413`,
  coursetitle: `Intellectual Property Rights`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `3CS105`,
  coursetitle: ` Object Oriented Methodology `,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CS171`,
  coursetitle: ` Information Security `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CSUG`,
  sem_elect: `EL`,
  coursecode: `CS103`,
  coursetitle: ` Data Structures and Algorithms `,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
]

export default CSEBtechCourseStructure
