import React from "react"

const Btech = [
 {
  "Sl. No.": "Mandatory Courses",
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: "",
 },
 {
  "Sl. No.": "1",
  coursecode: "xxxx",
  coursetitle: "Research Methodology",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "2",
  coursecode: "xxxx",
  coursetitle: "Seminar and Technical report Writing",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
  Total: "",
 },
 {
  "Sl. No.": "3",
  coursecode: "xxxx",
  coursetitle: "Comprehensive Viva & Presentation",
  l: 0,
  t: 0,
  p: 2,
  credits: 1,
  Total: "",
 },
 {
  "Sl. No.": "Departmental Courses",
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: "",
 },
 {
  "Sl. No.": "1",
  coursecode: "xxxx",
  coursetitle: "Course - I",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "2",
  coursecode: "xxxx",
  coursetitle: "Course - II",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "3",
  coursecode: "xxxx",
  coursetitle: "lab Course",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
  Total: "",
 },
 {
  "Sl. No.": "4",
  coursecode: "xxxx",
  coursetitle: "Course - III",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "5",
  coursecode: "xxxx",
  coursetitle: "Course - IV",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "6",
  coursecode: "xxxx",
  coursetitle: "Course - V",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.":
   "Course from (4) to (6) shall be for candidates having only B. Tech/ B. Arch Degree i.e. without Master’s degree in Technology/ Engineering/ Architecture/ Planning.",
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: "",
 },
]

export default Btech
