const HSSBtechCourseStructure = [
 {
  dept: `B Arch & B Arch`,
  sem_elect: `5`,
  coursecode: `HS5101`,
  url: `#`,
  coursetitle: `Sociology and Building Economics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `B Tech & B Arch `,
  sem_elect: `6 & 7 Open Elective`,
  coursecode: `HS107`,
  url: `#`,
  coursetitle: `Industrial Economics and Financial Management`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `B Tech & B Arch`,
  sem_elect: `6 & 7 Open Elective`,
  coursecode: `HS108`,
  url: `#`,
  coursetitle: `IPR and Entrepreneurship`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `B Tech & B Arch`,
  sem_elect: `6 & 7 Open Elective`,
  coursecode: `HS109`,
  url: `#`,
  coursetitle: `Organizational and Industrial Psychology`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `B Tech & B Arch`,
  sem_elect: `6 & 7 Open Elective`,
  coursecode: `HS110`,
  url: `#`,
  coursetitle: `History of Science and  Technology`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `B Tech & B Arch`,
  sem_elect: `6 & 7 Open Elective`,
  coursecode: `HS113`,
  url: `#`,
  coursetitle: `Intellectual Property Rights`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `B Tech & B Arch`,
  sem_elect: `7`,
  coursecode: `HS7601`,
  url: `#`,
  coursetitle: `Industrial Economics and Financial Management`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
]

export default HSSBtechCourseStructure
