import React from "react"

const hssCourseStructure = [
    {
        dept: `Deptt`,
        sem_elect: `Sem/Electives`,
        coursecode: `Course Code`,
        coursetitle: `Course Title`,
        l: `L`,
        t: `T`,
        p: `P`,
        credits: `Credits`,
      },
      {
        dept: `Mechanical Engineering`,
        sem_elect: `1`,
        coursecode: `HS1801`,
        coursetitle: `Communicative English`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Civil Engineering`,
        sem_elect: `1`,
        coursecode: `HS1301`,
        coursetitle: `Communicative English`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Architecture`,
        sem_elect: `1`,
        coursecode: `HS1101`,
        coursetitle: `Communicative English`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Integrated MSc`,
        sem_elect: `1`,
        coursecode: `HS1201`,
        coursetitle: `Communicative English`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Integrated MSc`,
        sem_elect: `1`,
        coursecode: `HS1701`,
        coursetitle: `Communicative English`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Integrated MSc`,
        sem_elect: `1`,
        coursecode: `HS1901`,
        coursetitle: `Communicative English`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Mechanical Engineering`,
        sem_elect: `1`,
        coursecode: `HSL1801`,
        coursetitle: `Language Lab`,
        l: `0`,
        t: `0`,
        p: `3`,
        credits: `1`,
      },
      {
        dept: `Civil Engineering`,
        sem_elect: `1`,
        coursecode: `HSL1301`,
        coursetitle: `Language Lab`,
        l: `0`,
        t: `0`,
        p: `3`,
        credits: `1`,
      },
      {
        dept: `Architecture`,
        sem_elect: `1`,
        coursecode: `HSL1101`,
        coursetitle: `Language Lab`,
        l: `0`,
        t: `0`,
        p: `3`,
        credits: `1`,
      },
      {
        dept: `Integrated MSc`,
        sem_elect: `1`,
        coursecode: `HSL1201`,
        coursetitle: `Language Lab`,
        l: `0`,
        t: `0`,
        p: `3`,
        credits: `1`,
      },
      {
        dept: `Integrated MSc`,
        sem_elect: `1`,
        coursecode: `HSL1701`,
        coursetitle: `Language Lab`,
        l: `0`,
        t: `0`,
        p: `3`,
        credits: `1`,
      },
      {
        dept: `Integrated MSc`,
        sem_elect: `1`,
        coursecode: `HSL1901`,
        coursetitle: `Language Lab`,
        l: `0`,
        t: `0`,
        p: `3`,
        credits: `1`,
      },
      {
        dept: `Computer Science Engineering`,
        sem_elect: `1`,
        coursecode: `HS1401`,
        coursetitle: `Science Society and Ethical Values`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Electronics and Communication Engineering`,
        sem_elect: `1`,
        coursecode: `HS1501`,
        coursetitle: `Science Society and Ethical Values`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Electrical Engineering`,
        sem_elect: `1`,
        coursecode: `HS1601`,
        coursetitle: `Science Society and Ethical Values`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Computer Science Engineering`,
        sem_elect: `2`,
        coursecode: `2HS2401`,
        coursetitle: `Communicative English`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Electronics and Communication Engineering`,
        sem_elect: `2`,
        coursecode: `2HS2501`,
        coursetitle: `Communicative English`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Electrical Engineering`,
        sem_elect: `2`,
        coursecode: `2HS2601`,
        coursetitle: `Communicative English`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Computer Science Engineering`,
        sem_elect: `2`,
        coursecode: `HSL2401`,
        coursetitle: `Language Lab`,
        l: `0`,
        t: `0`,
        p: `3`,
        credits: `1`,
      },
      {
        dept: `Electronics and Communication Engineering`,
        sem_elect: `2`,
        coursecode: `HSL2501`,
        coursetitle: `Language Lab`,
        l: `0`,
        t: `0`,
        p: `3`,
        credits: `1`,
      },
      {
        dept: `Electrical Engineering`,
        sem_elect: `2`,
        coursecode: `HSL2601`,
        coursetitle: `Language Lab`,
        l: `0`,
        t: `0`,
        p: `3`,
        credits: `1`,
      },
      {
        dept: `Mechanical Engineering`,
        sem_elect: `2`,
        coursecode: `HS2801`,
        coursetitle: `Science Society and Ethical Value`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Civil Engineering`,
        sem_elect: `2`,
        coursecode: `HS2301`,
        coursetitle: `Science Society and Ethical Value`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Architecture`,
        sem_elect: `2`,
        coursecode: `HS2101`,
        coursetitle: `Science Society and Ethical Value`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Integrated MSc`,
        sem_elect: `2`,
        coursecode: `HS2201`,
        coursetitle: `Science Society and Ethical Value`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Integrated MSc`,
        sem_elect: `2`,
        coursecode: `HS2701`,
        coursetitle: `Science Society and Ethical Value`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
      {
        dept: `Integrated MSc`,
        sem_elect: `2`,
        coursecode: `HS2901`,
        coursetitle: `Science Society and Ethical Value`,
        l: `2`,
        t: `1`,
        p: `0`,
        credits: `3`,
      },
]
export default hssCourseStructure