import React from "react"

const hssCourseStructure = [
 {
  dept: `Deptt`,
  sem_elect: `Sem/Electives`,
  course_code: `Course Code`,
  course_title: `Course Title`,
  l: `L`,
  t: `T`,
  p: `P`,
  credits: `Credits`,
 },
 {
  dept: `Mechanical Engineering`,
  sem_elect: `1`,
  course_code: `HS1801`,
  course_title: `Communicative English`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Civil Engineering`,
  sem_elect: `1`,
  course_code: `HS1301`,
  course_title: `Communicative English`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Architecture`,
  sem_elect: `1`,
  course_code: `HS1101`,
  course_title: `Communicative English`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Integrated MSc`,
  sem_elect: `1`,
  course_code: `HS1201`,
  course_title: `Communicative English`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Integrated MSc`,
  sem_elect: `1`,
  course_code: `HS1701`,
  course_title: `Communicative English`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Integrated MSc`,
  sem_elect: `1`,
  course_code: `HS1901`,
  course_title: `Communicative English`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Mechanical Engineering`,
  sem_elect: `1`,
  course_code: `HSL1801`,
  course_title: `Language Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `Civil Engineering`,
  sem_elect: `1`,
  course_code: `HSL1301`,
  course_title: `Language Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `Architecture`,
  sem_elect: `1`,
  course_code: `HSL1101`,
  course_title: `Language Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `Integrated MSc`,
  sem_elect: `1`,
  course_code: `HSL1201`,
  course_title: `Language Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `Integrated MSc`,
  sem_elect: `1`,
  course_code: `HSL1701`,
  course_title: `Language Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `Integrated MSc`,
  sem_elect: `1`,
  course_code: `HSL1901`,
  course_title: `Language Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `Computer Science Engineering`,
  sem_elect: `1`,
  course_code: `HS1401`,
  course_title: `Science Society and Ethical Values`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Electronics and Communication Engineering`,
  sem_elect: `1`,
  course_code: `HS1501`,
  course_title: `Science Society and Ethical Values`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Electrical Engineering`,
  sem_elect: `1`,
  course_code: `HS1601`,
  course_title: `Science Society and Ethical Values`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Computer Science Engineering`,
  sem_elect: `2`,
  course_code: `2HS2401`,
  course_title: `Communicative English`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Electronics and Communication Engineering`,
  sem_elect: `2`,
  course_code: `2HS2501`,
  course_title: `Communicative English`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Electrical Engineering`,
  sem_elect: `2`,
  course_code: `2HS2601`,
  course_title: `Communicative English`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Computer Science Engineering`,
  sem_elect: `2`,
  course_code: `HSL2401`,
  course_title: `Language Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `Electronics and Communication Engineering`,
  sem_elect: `2`,
  course_code: `HSL2501`,
  course_title: `Language Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `Electrical Engineering`,
  sem_elect: `2`,
  course_code: `HSL2601`,
  course_title: `Language Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `Mechanical Engineering`,
  sem_elect: `2`,
  course_code: `HS2801`,
  course_title: `Science Society and Ethical Value`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Civil Engineering`,
  sem_elect: `2`,
  course_code: `HS2301`,
  course_title: `Science Society and Ethical Value`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Architecture`,
  sem_elect: `2`,
  course_code: `HS2101`,
  course_title: `Science Society and Ethical Value`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Integrated MSc`,
  sem_elect: `2`,
  course_code: `HS2201`,
  course_title: `Science Society and Ethical Value`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Integrated MSc`,
  sem_elect: `2`,
  course_code: `HS2701`,
  course_title: `Science Society and Ethical Value`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `Integrated MSc`,
  sem_elect: `2`,
  course_code: `HS2901`,
  course_title: `Science Society and Ethical Value`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
]
export default hssCourseStructure
