const phd = [
 {
  "Sl. No.": "1",
  coursecode: "PDHSXX01",
  coursetitle: "Research Methodology",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "2",
  coursecode: "PDHSXX02",
  coursetitle: "Seminar and Technical Report Writing",
  l: 0,
  t: 0,
  p: 3,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "3",
  coursecode: "PDHSXX03",
  coursetitle: "Comprehensive Viva",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: "",
 },
 {
  "Sl. No.": "4",
  coursecode: "PDHSXX04",
  coursetitle: "Research Seminar",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: "",
 },
 {
  "Sl. No.": "5",
  coursecode: "PDHSXX05",
  coursetitle: "Human Resource Management",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "6",
  coursecode: "PDHSXX06",
  coursetitle: "Industrial Relations and Labour Legislations",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "7",
  coursecode: "PDHSXX07",
  coursetitle: "Introduction to British Romantic Poetry",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "8",
  coursecode: "PDHSXX08",
  coursetitle: "Twentieth Century Poetry",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "9",
  coursecode: "PDHSXX09",
  coursetitle: "Twentieth Century Novel/Short Story and Drama",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "10",
  coursecode: "PDHSXX10",
  coursetitle: "Introduction to Non-British Literature in English",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "11",
  coursecode: "PDHSXX11",
  coursetitle: "Advanced Microeconomics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "12",
  coursecode: "PDHSXX12",
  coursetitle: "Advanced Macroeconomics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "13",
  coursecode: "PDHSXX13",
  coursetitle: "Intellectual Property Rights",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "14",
  coursecode: "PDHSXX14",
  coursetitle: "Indian Rural Development",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "15",
  coursecode: "PDHSXX15",
  coursetitle: "Sociology: Development & Environment",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "16",
  coursecode: "PDHSXX16",
  coursetitle: "Econometrics",
  l: 3,
  t: 0,
  p: 3,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "17",
  coursecode: "PDHSXX17",
  coursetitle: "Postcolonial Literature",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  "Sl. No.": "18",
  coursecode: "PDHSXX18",
  coursetitle: "Computer Application Lab",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
  Total: "",
 },
]

export default phd
