export const Scholarship = [
 {
  no: "1.",
  scholarship: "Minority-1",
  authority: "Minority Commission, Ranchi",
  amount: 17000,
 },
 {
  no: "2.",
  scholarship: "Ex-seerviceman-1",
  authority: "Uttar Pradesh Sainik Kalyan",
  amount: 2500,
 },
 {
  no: "3.",
  scholarship: "SC-2",
  authority: "ST & SC Development Deptt. Orrissa",
  amount: 49760,
 },
 {
  no: "4.",
  scholarship: "SC-1",
  authority: "Indian Oil, New Delhi",
  amount: 12000,
 },
 {
  no: "5.",
  scholarship: "SC-3",
  authority: "Indian Oil, New Delhi",
  amount: 108000,
 },
 {
  no: "6.",
  scholarship: "ST-2",
  authority: "ST & SC Development Deptt. Orrissa",
  amount: 49760,
 },
 {
  no: "7.",
  scholarship: "Gen-1",
  authority: "SitaRam Jindal Foundation, New Delhi",
  amount: 2400,
 },
 {
  no: "8.",
  scholarship: "SC-1",
  authority: "Indian Oil, New Delhi",
  amount: 12000,
 },
 {
  no: "9.",
  scholarship: "SC-2",
  authority: "ST & SC Development Deptt. Orrissa",
  amount: 41600,
 },
 {
  no: "10.",
  scholarship: "ST-3",
  authority: "Director of Tech. Edn., Itanagar",
  amount: 17800,
 },
 {
  no: "11.",
  scholarship: "BCE-1",
  authority: "BC Welfare, WB",
  amount: 15880,
 },
 {
  no: "12.",
  scholarship: "SC-2",
  authority: "Welfare of SC, Assam",
  amount: 27368,
 },
 {
  no: "13.",
  scholarship: "SC-1",
  authority: "Tech. Edn., HP",
  amount: 6000,
 },
 {
  no: "14.",
  scholarship: "SC-1",
  authority: "Social Welfare Dept., Karnataka",
  amount: 50000,
 },
 {
  no: "15.",
  scholarship: "Minority-1",
  authority: "Director of Tech. Edn., Thiruvanthpuran",
  amount: 20000,
 },
 {
  no: "16.",
  scholarship: "OBC-1",
  authority: "ST Dept. Chhattisgarh, Raipur",
  amount: 13260,
 },
 {
  no: "17.",
  scholarship: "SC-1",
  authority: "Director of Tech. Edn., H.P.",
  amount: 6000,
 },
 {
  no: "18.",
  scholarship: "ST-2",
  authority: "Engineers India, New Delhi",
  amount: 18000,
 },
 {
  no: "19.",
  scholarship: "ST-1",
  authority: "ST Development, U.P.",
  amount: 15300,
 },
 {
  no: "20.",
  scholarship: "Gen-1",
  authority: "Director of Tech. Edn., Tripura",
  amount: 4500,
 },
 {
  no: "21.",
  scholarship: "OBC-1",
  authority: "District Welfare Nagpur, M.P.",
  amount: 21060,
 },
 {
  no: "22.",
  scholarship: "Gen-1",
  authority: "Director of Tech. Edn., Assam",
  amount: 10600,
 },
 {
  no: "23.",
  scholarship: "ST-1",
  authority: "Director of Tech. Edn., Assam",
  amount: 14630,
 },
 {
  no: "24.",
  scholarship: "Gen-2",
  authority: "Director of Tech. Edn., Tripura",
  amount: 18000,
 },
 {
  no: "25.",
  scholarship: "ST-2",
  authority: "Engineers India, New Delhi",
  amount: 18000,
 },
 {
  no: "26.",
  scholarship: "ST-3",
  authority: "Director of Tech. Edn., Kohima",
  amount: 34800,
 },
 {
  no: "27.",
  scholarship: "ST-1",
  authority: "Director of Tech. Edn., Andhra Pradesh",
  amount: 10600,
 },
 {
  no: "28.",
  scholarship: "SC-1",
  authority: "Social welfare, Krishna Dist. A.P.",
  amount: 17044,
 },
 {
  no: "29.",
  scholarship: "SC-2",
  authority: "District Welfare U.P.",
  amount: 24510,
 },
 {
  no: "30.",
  scholarship: "Gen-1",
  authority: "Director of Tech. Edn., Tripura",
  amount: 3600,
 },
 {
  no: "31.",
  scholarship: "SC-158",
  authority: "District Welfare, Patna",
  amount: 3165600,
 },
 {
  no: "32.",
  scholarship: "ST-53",
  authority: "District Welfare, Patna",
  amount: 857000,
 },
 {
  no: "33.",
  scholarship: "OBC-21",
  authority: "District Welfare, Patna",
  amount: 490810,
 },
 {
  no: "34.",
  scholarship: "Minority-14",
  authority: "Bihar State Minority Fin. Corp., Patna",
  amount: 39500,
 },
 {
  no: "Total ₹",
  scholarship: "-",
  authority: "-",
  amount: 5214882,
 },
]
export const tabledata = [
 {
  no: "1.",
  village: "Sabalpur",
  district: "Patna",
 },
 {
  no: "2.",
  village: "Juthli",
  district: "Patna",
 },
 {
  no: "3.",
  village: "Panapur",
  district: "patna",
 },
 {
  no: "4.",
  village: "Nakta Diara",
  district: "Patna",
 },
 {
  no: "5.",
  village: "Nadauri",
  district: "Patna",
 },
]
