export const MtechDesignEngineering = [
 {
  deptt: "Semester I",
  "Specialization Code": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "Core",
  sem_elect: 1,
  course_code: "ME721",
  course_title: "Advanced Mechanical Engineering Design",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "Core",
  sem_elect: 1,
  course_code: "ME722",
  course_title: "Advanced Mechanics of Solids",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-1",
  sem_elect: 1,
  course_code: "ME6xx",
  course_title: "Elective I",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-2",
  sem_elect: 1,
  course_code: "ME6xx",
  course_title: "Elective II",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-3",
  sem_elect: 1,
  course_code: "ME6xx",
  course_title: "Elective III",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "Lab",
  sem_elect: 1,
  course_code: "ME688",
  course_title: "Impact Mechanics Lab/Advance MOS Lab",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "",
  sem_elect: 1,
  course_code: "",
  course_title: "Total Semester Credits",
  l: 15,
  t: 0,
  p: 6,
  credits: 19,
 },
 {
  deptt: "Semester II",
  "Specialization Code": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "Core",
  sem_elect: 2,
  course_code: "ME723",
  course_title: "Computer Methods in Mechanical Design",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-4",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective IV",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-5",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective  V",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-6",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective VI",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-7",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective VII",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "Lab",
  sem_elect: 2,
  course_code: "ME689",
  course_title: "Advance MOS Lab-2",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "Lab",
  sem_elect: 2,
  course_code: "ME694",
  course_title: "Seminar",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "",
  sem_elect: 2,
  course_code: "",
  course_title: "Total Semester Credit",
  l: 15,
  t: 0,
  p: 9,
  credits: 21,
 },
 {
  deptt: "Semester III",
  "Specialization Code": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "Lab",
  sem_elect: 3,
  course_code: "ME695",
  course_title: "Seminar and Comprehensive Viva I",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "Lab",
  sem_elect: 3,
  course_code: "ME697",
  course_title: "Dissertation (to be continued in 4th Sem)",
  l: 0,
  t: 0,
  p: 12,
  credits: 8,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "",
  sem_elect: 3,
  course_code: "",
  course_title: "Total Semester Credit",
  l: 0,
  t: 0,
  p: 15,
  credits: 10,
 },
 {
  deptt: "Semester IV",
  "Specialization Code": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "Lab",
  sem_elect: 4,
  course_code: "ME696",
  course_title: "Seminar and Comprehensive Viva II",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "Lab",
  sem_elect: 4,
  course_code: "ME698",
  course_title: "Dissertation",
  l: 0,
  t: 0,
  p: 15,
  credits: 10,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "",
  sem_elect: 4,
  course_code: "",
  course_title: "Total Semester Credit",
  l: 0,
  t: 0,
  p: 18,
  credits: 12,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "",
  sem_elect: 4,
  course_code: "",
  course_title: "Cumulative Total Credit",
  l: null,
  t: null,
  p: null,
  credits: 62,
 },
 {
  deptt: "List Of Electives",
  "Specialization Code": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-1",
  sem_elect: 1,
  course_code: "MA601",
  course_title: "Mathematical Methods of Engineering",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-1",
  sem_elect: 1,
  course_code: "ME724",
  course_title: "Advanced Materials and Processing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-2",
  sem_elect: 1,
  course_code: "ME637",
  course_title: "Advances in Engineering Optimization",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-2",
  sem_elect: 1,
  course_code: "ME726",
  course_title: "Mechanical Behaviour of Materials",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-3",
  sem_elect: 1,
  course_code: "ME728",
  course_title: "Pressure Vessel and Piping Design",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-3",
  sem_elect: 1,
  course_code: "ME613",
  course_title: "Finite Element Analysis",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-4",
  sem_elect: 2,
  course_code: "ME733",
  course_title: "Reverse Engineering and Rapid Prototyping",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-4",
  sem_elect: 2,
  course_code: "ME734",
  course_title: "Mechanics of Composite Materials",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-5",
  sem_elect: 2,
  course_code: "ME735",
  course_title: "Robotics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-5",
  sem_elect: 2,
  course_code: "ME736",
  course_title: "Instrumentation and Automatic Control Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-5",
  sem_elect: 2,
  course_code: "ME737",
  course_title: "Product Life Cycle Management",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-6",
  sem_elect: 2,
  course_code: "ME729",
  course_title: "Fracture Mechanics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-6",
  sem_elect: 2,
  course_code: "ME730",
  course_title: "Micro Electro Mechanical Systems",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-7",
  sem_elect: 2,
  course_code: "ME731",
  course_title: "Non-linear Dynamics and Chaos",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Specialization Code": "DSGN",
  Group: "EL-7",
  sem_elect: 2,
  course_code: "ME727",
  course_title: "Advanced Theory of Vibrations",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
]

export const MtechProductionEngineering = [
 {
  deptt: "Semester-I",
  "Special ization": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "Core",
  sem_elect: 1,
  course_code: "ME641",
  course_title: "Modern Manufacturing Process",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "Core",
  sem_elect: 1,
  course_code: "ME642",
  course_title: "Production Planning and Control",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-1",
  sem_elect: 1,
  course_code: "ME6xx",
  course_title: "Elective I",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-2",
  sem_elect: 1,
  course_code: "ME6xx",
  course_title: "Elective II",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-3",
  sem_elect: 1,
  course_code: "ME6xx",
  course_title: "Elective  III",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "Lab",
  sem_elect: 1,
  course_code: "ME682",
  course_title: "Manufacturing Lab-I",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "",
  sem_elect: 1,
  course_code: "",
  course_title: "Total Semester Credits",
  l: 15,
  t: 0,
  p: 6,
  credits: 19,
 },
 {
  deptt: "SemesterII",
  "Special ization": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "Core",
  sem_elect: 2,
  course_code: "ME643",
  course_title: "Computer Integrated Manufacturing and CAM",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-4",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective IV",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-5",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective V",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-6",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective VI",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-7",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective VII",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "Lab",
  sem_elect: 2,
  course_code: "ME685",
  course_title: "Manufacturing Lab-II",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "Lab",
  sem_elect: 2,
  course_code: "ME694",
  course_title: "Seminar",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "",
  sem_elect: 2,
  course_code: "",
  course_title: "Total Semester Credit",
  l: 15,
  t: 0,
  p: 9,
  credits: 21,
 },
 {
  deptt: "Semester III",
  "Special ization": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "Lab",
  sem_elect: 3,
  course_code: "ME695",
  course_title: "Seminar and Comprehensive Viva I",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "Lab",
  sem_elect: 3,
  course_code: "ME697",
  course_title: "Dissertation (to be continued in 4th Sem)",
  l: 0,
  t: 0,
  p: 12,
  credits: 8,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "",
  sem_elect: 3,
  course_code: "",
  course_title: "Total Semester Credit",
  l: 0,
  t: 0,
  p: 15,
  credits: 10,
 },
 {
  deptt: "Semester IV",
  "Special ization": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "Lab",
  sem_elect: 4,
  course_code: "ME696",
  course_title: "Seminar and Comprehensive Viva  II",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "Lab",
  sem_elect: 4,
  course_code: "ME698",
  course_title: "Dissertation",
  l: 0,
  t: 0,
  p: 15,
  credits: 10,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "",
  sem_elect: 4,
  course_code: "",
  course_title: "Total Semester Credit",
  l: 0,
  t: 0,
  p: 18,
  credits: 12,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "",
  sem_elect: 4,
  course_code: "",
  course_title: "Cumulative Total Credit",
  l: null,
  t: null,
  p: null,
  credits: 62,
 },
 {
  deptt: "List    Of  Electives",
  "Special ization": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-1",
  sem_elect: 1,
  course_code: "ME645",
  course_title: "Project Management",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-1",
  sem_elect: 1,
  course_code: "ME646",
  course_title: "Surface Engineering",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-2",
  sem_elect: 1,
  course_code: "ME637",
  course_title: "Advances in Engineering Optimization",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-2",
  sem_elect: 1,
  course_code: "ME649",
  course_title: "Modeling and Simulation of system",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-3",
  sem_elect: 1,
  course_code: "ME644",
  course_title: "Composite material & Processing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-3",
  sem_elect: 1,
  course_code: "ME613",
  course_title: "Finite Element Analysis",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-4",
  sem_elect: 2,
  course_code: "ME654",
  course_title: "Nano-technology and Micro-machining",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-4",
  sem_elect: 2,
  course_code: "ME655",
  course_title: "Mechatronics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-5",
  sem_elect: 2,
  course_code: "ME656",
  course_title: "Supply Chain and Logistics Management",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-5",
  sem_elect: 2,
  course_code: "ME658",
  course_title: "Industrial Organization and behavior",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-6",
  sem_elect: 2,
  course_code: "ME650",
  course_title: "Quality Engineering",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-6",
  sem_elect: 2,
  course_code: "ME651",
  course_title: "Advanced Fabrication Technology",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-7",
  sem_elect: 2,
  course_code: "ME652",
  course_title: "Lean Manufacturing",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-7",
  sem_elect: 2,
  course_code: "ME653",
  course_title: "Metal forming & casting",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "Special ization": "PROD",
  Group: "EL-7",
  sem_elect: 2,
  course_code: "ME657",
  course_title: "Machining Science",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
]

export const MtechThermalEngineering = [
 {
  deptt: "Semester I",
  "CCMT Code": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "Core",
  sem_elect: 1,
  course_code: "ME601",
  course_title: "Advanced Thermodynamics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "Core",
  sem_elect: 1,
  course_code: "ME602",
  course_title: "Advanced Heat and Mass Transfer",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-1",
  sem_elect: 1,
  course_code: "ME6xx",
  course_title: "Elective  I",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-2",
  sem_elect: 1,
  course_code: "ME6xx",
  course_title: "Elective II",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-3",
  sem_elect: 1,
  course_code: "ME6xx",
  course_title: "Elective III",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "Lab",
  sem_elect: 1,
  course_code: "ME681",
  course_title: "Advanced Mechanical Engineering Lab - I",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "",
  sem_elect: 1,
  course_code: "",
  course_title: "Total Semester Credits",
  l: 15,
  t: 0,
  p: 6,
  credits: 19,
 },
 {
  deptt: "Semester II",
  "CCMT Code": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "Core",
  sem_elect: 2,
  course_code: "ME631",
  course_title: "Design of Thermal System",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-4",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective IV",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-5",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective V",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-6",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective VI",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-7",
  sem_elect: 2,
  course_code: "ME6xx",
  course_title: "Elective VII",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "Lab",
  sem_elect: 2,
  course_code: "ME685",
  course_title: "Advanced Mechanical Engineering Lab - II",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "Lab",
  sem_elect: 2,
  course_code: "ME694",
  course_title: "Seminar",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "",
  sem_elect: 2,
  course_code: "",
  course_title: "Total Semester Credit",
  l: 15,
  t: 0,
  p: 9,
  credits: 21,
 },
 {
  deptt: "Semester III",
  "CCMT Code": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "Lab",
  sem_elect: 3,
  course_code: "ME695",
  course_title: "Seminar and Comprehensive Viva I",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "Lab",
  sem_elect: 3,
  course_code: "ME697",
  course_title: "Dissertation (to be continued in 4th Sem)",
  l: 0,
  t: 0,
  p: 12,
  credits: 8,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "",
  sem_elect: 3,
  course_code: "",
  course_title: "Total Semester Credit",
  l: 0,
  t: 0,
  p: 15,
  credits: 10,
 },
 {
  deptt: "Semester IV",
  "CCMT Code": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "Lab",
  sem_elect: 4,
  course_code: "ME696",
  course_title: "Seminar and Comprehensive Viva  II",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "Lab",
  sem_elect: 4,
  course_code: "ME698",
  course_title: "Dissertation",
  l: 0,
  t: 0,
  p: 15,
  credits: 10,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "",
  sem_elect: 4,
  course_code: "",
  course_title: "Total Semester Credit",
  l: 0,
  t: 0,
  p: 18,
  credits: 12,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "",
  sem_elect: 4,
  course_code: "",
  course_title: "Cumulative Total Credit",
  l: null,
  t: null,
  p: null,
  credits: 62,
 },
 {
  deptt: "List Of Electives",
  "CCMT Code": "",
  Group: "",
  sem_elect: null,
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-1",
  sem_elect: 1,
  course_code: "MA601",
  course_title: "Mathematical Methods of Engineering",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-1",
  sem_elect: 1,
  course_code: "ME614",
  course_title: "Computational Fluid Dynamics (CFD)",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-2",
  sem_elect: 1,
  course_code: "ME637",
  course_title: "Advances in Engineering optimization",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-2",
  sem_elect: 1,
  course_code: "ME632",
  course_title: "Advanced IC Engines",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-3",
  sem_elect: 1,
  course_code: "ME613",
  course_title: "Finite Element Analysis",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-3",
  sem_elect: 1,
  course_code: "ME611",
  course_title: "Solar Energy",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-4",
  sem_elect: 2,
  course_code: "ME612",
  course_title: "Fuel Cell Technology",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-4",
  sem_elect: 2,
  course_code: "ME633",
  course_title: "Advanced Refrigeration",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-5",
  sem_elect: 2,
  course_code: "ME638",
  course_title: "Advanced Gas Turbine",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-5",
  sem_elect: 2,
  course_code: "ME626",
  course_title: "Combustion generated pollution",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-5",
  sem_elect: 2,
  course_code: "ME639",
  course_title: "Advance Fluid Mechanics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-6",
  sem_elect: 2,
  course_code: "ME624",
  course_title: "Gas Dynamics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-6",
  sem_elect: 2,
  course_code: "ME635",
  course_title: "Turbo machine",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-7",
  sem_elect: 2,
  course_code: "ME636",
  course_title: "Power Plant Engineering",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
 {
  deptt: "MEPG",
  "CCMT Code": "THR",
  Group: "EL-7",
  sem_elect: 2,
  course_code: "ME634",
  course_title: "Fuel and Combustion",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
 },
]
