import React from "react"

export const MEBTechCourseStructure = [
 {
  deptt: `MEUG`,
  sem_elect: `3`,
  course_code: `ME 3804`,
  course_title: `Kinematics of Machinery`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `3`,
  course_code: `ME 3803`,
  course_title: `Manufacturing Process`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `3`,
  course_code: `MEL 3801`,
  course_title: `Manufacturing Process Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `3`,
  course_code: `CE 3801`,
  course_title: `Environmental Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `CE`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `3`,
  course_code: `ME 3802`,
  course_title: `Thermodynamics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `3`,
  course_code: `ME 3801`,
  course_title: `Material Science & Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `3`,
  course_code: `ME 0000`,
  course_title: `MOOC/Swayam course`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `NPTEL/Swayam`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `3`,
  course_code: `MA 3801`,
  course_title: `Numerical Methods for Engineers`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `Math`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `4`,
  course_code: `EAA 3801`,
  course_title: `EAA (Sports/ITovative Project)`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `SAC/IC`,
 },
 {
  deptt: `-`,
  sem_elect: `3`,
  course_code: `Total`,
  course_title: `-`,
  l: `18`,
  t: `0`,
  p: `6`,
  credits: `20`,
  dept: `-`,
 },

 {
  deptt: `MEUG`,
  sem_elect: `4`,
  course_code: `ME 4803`,
  course_title: `Industrial Engineering and Management`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `4`,
  course_code: `ME 4801`,
  course_title: `Applied Thermodynamics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `4`,
  course_code: `MEL 4801`,
  course_title: `Applied Thermodynamics Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `4`,
  course_code: `ME 4802`,
  course_title: `Fluid Mechanics & Machinery`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `4`,
  course_code: `MEL 4802`,
  course_title: `Fluid Mechanics & Machinery Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `4`,
  course_code: `ME 480x`,
  course_title: `Professional Electives-I`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `4`,
  course_code: `ME 480x`,
  course_title: `Professional Electives-II`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `4`,
  course_code: `OE0xy1`,
  course_title: `Open Electives-I`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `-`,
 },

 {
  deptt: `MEUG`,
  sem_elect: `4`,
  course_code: `ME 0000`,
  course_title: `MOOC/Swayam course`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `NPTEL/Swayam`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `4`,
  course_code: `Total`,
  course_title: `-`,
  l: `18`,
  t: `0`,
  p: `6`,
  credits: `20`,
  dept: `-`,
 },

 {
  deptt: `MEUG`,
  sem_elect: `EL1`,
  course_code: `ME 4804`,
  course_title: `Advanced Strength of Materials`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL1`,
  course_code: `ME 4805`,
  course_title: `Statistical Quality Control`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },

 {
  deptt: `MEUG`,
  sem_elect: `EL2`,
  course_code: `ME 4806`,
  course_title: `Mechatronics and Robotics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL2`,
  course_code: `ME 4807`,
  course_title: `Renewable Energy Systems`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },

 {
  deptt: `MEUG`,
  sem_elect: `5`,
  course_code: `ME 5803`,
  course_title: `Dynamics of Machinery`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `5`,
  course_code: `MEL 5803`,
  course_title: `Dynamics of Machinery Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `5`,
  course_code: `ME 5801`,
  course_title: `Heat Transfer`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `1`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `5`,
  course_code: `MEL 5801`,
  course_title: `Heat Transfer Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `5`,
  course_code: `ME 5802`,
  course_title: `Machine Design-I`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `5`,
  course_code: `ME 580x`,
  course_title: `Professional Elective-III`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `5`,
  course_code: `ME 580x`,
  course_title: `Professional Elective-IV`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `5`,
  course_code: `OE0xy2`,
  course_title: `Open Elective-II`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `-`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `5`,
  course_code: `ME 0000`,
  course_title: `MOOC/Swayam course`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `5`,
  course_code: `Total`,
  course_title: `-`,
  l: `18`,
  t: `0`,
  p: `6`,
  credits: `20`,
  dept: `-`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 3`,
  course_code: `ME 5804`,
  course_title: `Measurements & Instrumentation`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 3`,
  course_code: `ME 5805`,
  course_title: `Power Plant Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 4`,
  course_code: `ME 5806`,
  course_title: `Operations Research`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 3`,
  course_code: `ME 5807`,
  course_title: `Metal Forming Process`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `6`,
  course_code: `ME 6801`,
  course_title: `Internal Combustion Engine`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `6`,
  course_code: `MEL 6801`,
  course_title: `Internal Combustion Engine Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `6`,
  course_code: `ME 6802`,
  course_title: `Machine Design-II`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `6`,
  course_code: `ME 6803`,
  course_title: `Machine Tools & Machining`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `6`,
  course_code: `MEL 6803`,
  course_title: `Machine Tools & Machining Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `6`,
  course_code: `ME 680x`,
  course_title: `Professional Elective V`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `6`,
  course_code: `ME 680x`,
  course_title: `Professional Elective VI`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `6`,
  course_code: `OE0xy3`,
  course_title: `Open Elective-III`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `-`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `6`,
  course_code: `ME 0000`,
  course_title: `MOOC/Swayam course`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `NPTEL/Swayam`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 5`,
  course_code: `ME 6804`,
  course_title: `Computational Fluid Dynamics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 5`,
  course_code: `ME 6805`,
  course_title: `Advanced Materials & Tools`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 5`,
  course_code: `ME 6806`,
  course_title: `Introduction to Engineering Optimisations`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 6`,
  course_code: `ME 6807`,
  course_title: `Finite Element Methods`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 6`,
  course_code: `ME 6808`,
  course_title: `CAD/CAM`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 6`,
  course_code: `ME 6809`,
  course_title: `Mechanical Vibration`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `7`,
  course_code: `ME 7801`,
  course_title: `Refridgeration and Air-Conditioning`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `7`,
  course_code: `ME 780x`,
  course_title: `Professional Elective-VII`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `7`,
  course_code: `ME 780x`,
  course_title: `Professional Elective-VIII`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `7`,
  course_code: `OE0xy4`,
  course_title: `Open Elective-IV`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `7`,
  course_code: `ME 0000`,
  course_title: `MOOC/Swayam course`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `NPTEL/Swayam`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `7`,
  course_code: `MEL 7801`,
  course_title: `Minor Project`,
  l: `0`,
  t: `0`,
  p: `15`,
  credits: `5`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `7`,
  course_code: `MEL 7802`,
  course_title: `Industrial Training`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `2`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `7`,
  course_code: `MEL 7803`,
  course_title: `Refrigeration and Air-Conditioning Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `7`,
  course_code: `MEL 7804`,
  course_title: `Seminar & Technical Writing`,
  l: `0`,
  t: `0`,
  p: `6`,
  credits: `2`,
  dept: `ME`,
 },
 {
  deptt: `-`,
  sem_elect: `7`,
  course_code: `Total`,
  course_title: `-`,
  l: `12`,
  t: `0`,
  p: `24`,
  credits: `22`,
  dept: `-`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 7`,
  course_code: `ME 7802`,
  course_title: `Automobile Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 7`,
  course_code: `ME 7803`,
  course_title: `Nonlinear Vibrations`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 7`,
  course_code: `ME 7804`,
  course_title: `Gas Turbine & Jet Propulsion`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 7`,
  course_code: `ME 7805`,
  course_title: `Material Handling`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 8`,
  course_code: `ME 7806`,
  course_title: `Non-Conventional Manufacturing`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 8`,
  course_code: `ME 7807`,
  course_title: `Total Productive Maintenance`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 8`,
  course_code: `ME 7808`,
  course_title: `Tribology`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 8`,
  course_code: `ME 7809`,
  course_title: `Advances in Fabrication Processes`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `8`,
  course_code: `ME 880x`,
  course_title: `Professional Elective-IX`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `8`,
  course_code: `ME 880x`,
  course_title: `Professional Elective-X`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `8`,
  course_code: `ME 8801`,
  course_title: `Major Project`,
  l: `0`,
  t: `0`,
  p: `30`,
  credits: `10`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `8`,
  course_code: `MEL 8803`,
  course_title: `Comprehensive Viva-Voca`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `2`,
  dept: `ME`,
 },
 {
  deptt: `-`,
  sem_elect: `8`,
  course_code: `Total`,
  course_title: `-`,
  l: `6`,
  t: `0`,
  p: `36`,
  credits: `20`,
  dept: `-`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 9`,
  course_code: `ME 8801`,
  course_title: `Product Design & Development`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 9`,
  course_code: `ME 8802`,
  course_title: `Heat Exchanger Design`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 9`,
  course_code: `ME 8803`,
  course_title: `Additive Manufacturing & 3D printing`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 9`,
  course_code: `ME 8804`,
  course_title: `Ergonomics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 10`,
  course_code: `ME 8805`,
  course_title: `Machine Condition Monitoring`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 10`,
  course_code: `ME 8806`,
  course_title: `Production and Operations Management`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 10`,
  course_code: `ME 8807`,
  course_title: `Aerodynamics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `EL 10`,
  course_code: `ME 8808`,
  course_title: `Total Quality Management`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `OPEL`,
  course_code: `OE 0801`,
  course_title: `Elements of Mechanical Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `OPEL`,
  course_code: `OE 0802`,
  course_title: `Renewable Energy`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `OPEL`,
  course_code: `OE 0803`,
  course_title: `Introduction to Operations Research`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
 {
  deptt: `MEUG`,
  sem_elect: `OPEL`,
  course_code: `OE 0804`,
  course_title: `Introduction to Power Plants`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `ME`,
 },
]

export default MEBTechCourseStructure
