export const PhdCourse = [
 {
  deptt: "Mandatory Courses",
  "Sl. No.": "Mandatory Courses",
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: "",
 },

 {
  deptt: "MEPhD",
  "Sl. No.": "1",
  course_code: "1ME901",
  course_title: "Research Methodology",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  deptt: "MEPhD",
  "Sl. No.": "2",
  course_code: "1ME990",
  course_title: "Seminar and Technical report Writing",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
  Total: "",
 },
]
