const ECEPhd = [
 {
  deptt: "ECE",
  "Sl. No.": "Mandatory Courses",
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: "",
 },
 {
  deptt: "ECE",
  "Sl. No.": "1",
  course_code: "xxxx",
  course_title: "Research Methodology",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  deptt: "ECE",
  "Sl. No.": "2",
  course_code: "xxxx",
  course_title: "Seminar and Technical report Writing",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
  Total: "",
 },
 {
  deptt: "ECE",
  "Sl. No.": "3",
  course_code: "xxxx",
  course_title: "Comprehensive Viva & Presentation",
  l: 0,
  t: 0,
  p: 2,
  credits: 1,
  Total: "",
 },
 {
  deptt: "ECE",
  "Sl. No.": "Departmental Courses",
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: "",
 },
 {
  deptt: "ECE",
  "Sl. No.": "1",
  course_code: "xxxx",
  course_title: "Course - I",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  deptt: "ECE",
  "Sl. No.": "2",
  course_code: "xxxx",
  course_title: "Course - II",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  deptt: "ECE",
  "Sl. No.": "3",
  course_code: "xxxx",
  course_title: "Lab Course",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
  Total: "",
 },
 {
  deptt: "ECE",
  "Sl. No.": "4",
  course_code: "xxxx",
  course_title: "Course - III",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  deptt: "ECE",
  "Sl. No.": "5",
  course_code: "xxxx",
  course_title: "Course - IV",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  deptt: "ECE",
  "Sl. No.": "6",
  course_code: "xxxx",
  course_title: "Course - V",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: "",
 },
 {
  deptt: "ECE",
  "Sl. No.":
   "Course from (4) to (6) shall be for candidates having only B. Tech/ B. Arch Degree i.e. without Master’s degree in Technology/ Engineering/ Architecture/ Planning.",
  course_code: "",
  course_title: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: "",
 },
]

export default ECEPhd
