import React from "react"

const ChemistryPhdCourse = [
 {
  semester: <strong>Department Elective</strong>,
  course_code: ` `,
  course_title: ` `,
  l: ` `,
  t: ` `,
  p: ` `,
  credit: ``,
 },

 {
  semester: ` `,
  course_code: `PDME0101 `,
  course_title: `RESEARCH METHODOLOGY`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credit: `3 `,
 },

 {
  semester: ` `,
  course_code: `PDCHXX01 `,
  course_title: ` RESEARCH SEMINAR`,
  l: ` `,
  t: ` `,
  p: ` `,
  credit: ` `,
 },

 {
  semester: ` `,
  course_code: `PDCHXX02 `,
  course_title: `SEMINAR AND TECHNICAL REPORT WRITING `,
  l: `0 `,
  t: `0 `,
  p: `3`,
  credit: `2 `,
 },
 {
  semester: ` `,
  course_code: `PDCHXX03 `,
  course_title: ` COMPREHENSIVE VIVA`,
  l: ` `,
  t: ` `,
  p: ``,
  credit: ` `,
 },
 {
  semester: ` `,
  course_code: `PDCHXX04 `,
  course_title: ` SPECTROSCOPIC METHODS LABORATORY `,
  l: `0 `,
  t: `0 `,
  p: `4 `,
  credit: `4 `,
 },

 {
  semester: ` `,
  course_code: `PDCHXX05 `,
  course_title: `COORDINATION CHEMISTRY `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credit: `3 `,
 },
 {
  semester: ` `,
  course_code: `PDCHXX06 `,
  course_title: ` ART IN ORGANIC SYNTHESIS `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credit: `3 `,
 },
 {
  semester: ` `,
  course_code: `PDCHXX07 `,
  course_title: `CHEMISTRY OF NATURAL PRODUCTS `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credit: `3 `,
 },
 {
  semester: ` `,
  course_code: `PDCHXX08 `,
  course_title: `PLASMONIC NANOMATERIALS: PROPERTIES & APPLICATION `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credit: `3 `,
 },
 {
  semester: ` `,
  course_code: `PDCHXX09 `,
  course_title: ` PHOTOPHYSICS`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credit: `3 `,
 },

 {
  semester: ` `,
  course_code: `PDCHXX10 `,
  course_title: ` BIOPHYSICAL CHEMISTRY`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credit: `3 `,
 },
 {
  semester: ` `,
  course_code: `PDCHXX11 `,
  course_title: ` SUPRAMOLECULAR CHEMISTRY`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credit: `3 `,
 },
 {
  semester: ` `,
  course_code: `PDCHXX12 `,
  course_title: ` CHEMISTRY OF HETEROCYCLIC COMPOUNDS`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credit: `3 `,
 },
 {
  semester: ` `,
  course_code: `PDCHXX13 `,
  course_title: `ADVANCED QUANTUM MECHANICS `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credit: `3 `,
 },
 {
  semester: ` `,
  course_code: `PDCHXX14 `,
  course_title: ` MEDICINAL CHEMISTRY`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credit: `3 `,
 },
 {
  semester: ` `,
  course_code: `PDCHXX15 `,
  course_title: ` SYNTHETIC & PURIFICATION METHODS LABORATORY`,
  l: `3 `,
  t: `0 `,
  p: `6 `,
  credit: `4 `,
 },
]
export default ChemistryPhdCourse
