import React from "react"

const IMScMathCourseStructure = [
 {
  course_code: `HS1701`,
  course_title: `Communicative English`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
  dept: `HSS`,
  type: `Foundation`,
 },
 {
  course_code: `HSL1701`,
  course_title: `Language Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `HSS`,
  type: `Lab`,
 },
 {
  course_code: `MA1701`,
  course_title: `Mathematics-I`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `MA`,
  type: `Foundation`,
 },
 {
  course_code: `PH1701`,
  course_title: `Engineering Physics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `PH`,
  type: `Foundation`,
 },
 {
  course_code: `PHL1701`,
  course_title: `Physics Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `PH`,
  type: `Lab`,
 },
 {
  course_code: `CS1701`,
  course_title: `Introduction To Computing`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `CSE`,
  type: `Foundation`,
 },
 {
  course_code: `CSL1701`,
  course_title: `Computing Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `CSE`,
  type: `Lab`,
 },
 {
  course_code: `CE1701`,
  course_title: `Engineering Mechanics`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
  dept: `CE`,
  type: `Foundation`,
 },
 {
  course_code: `MEL1701`,
  course_title: `Workshop Practice`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `ME`,
  type: `Lab`,
 },
 {
  course_code: `EAA1701`,
  course_title: `EAA-Swachha Bharat Mission`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `MA/SAC`,
  type: `Lab`,
 },
 {
  course_code: `-`,
  course_title: `Total Credit`,
  l: `13`,
  t: `2`,
  p: `15`,
  credits: `20`,
  dept: `-`,
  type: `-`,
 },
 {
  course_code: `HS2701`,
  course_title: `Science, Society and Ethical Values`,
  l: `1`,
  t: `1`,
  p: `0`,
  credits: `3`,
  dept: `HSS`,
  type: `Foundation`,
 },
 {
  course_code: `MA2701`,
  course_title: `Mathematics II`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `MA`,
  type: `Foundation`,
 },
 {
  course_code: `CH2701`,
  course_title: `Engineering Chemistry`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `CH`,
  type: `Foudation`,
 },
 {
  course_code: `CHL2701`,
  course_title: `Chemistry Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `CH`,
  type: `Lab`,
 },
 {
  course_code: `ME2701`,
  course_title: `Engineering Graphics`,
  l: `2`,
  t: `0`,
  p: `0`,
  credits: `2`,
  dept: `ME`,
  type: `Lab`,
 },
 {
  course_code: `MEL2701`,
  course_title: `Engineering Graphics Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `ME`,
  type: `Lab`,
 },
 {
  course_code: `MA2702`,
  course_title: `Complex Variable and Partial Differential Equation`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `PH2701`,
  course_title: `Continuum Mechanics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `PH`,
  type: `Foundation`,
 },
 {
  course_code: `PHL2701`,
  course_title: `Continuum Mechanics Lab(Physics)`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `PH`,
  type: `Lab`,
 },
 {
  course_code: `EAA2701`,
  course_title: `EAA-Sports/Icovation Project`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `MA/IC/SAC`,
  type: `Lab`,
 },
 {
  course_code: `-`,
  course_title: `Total Credit`,
  l: `16`,
  t: `1`,
  p: `12`,
  credits: `21`,
  dept: `-`,
  type: `-`,
 },
 {
  course_code: `MA3701`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA3701.docx`,
  course_title: `Discrete Mathematics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA3702`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA3702.docx`,
  course_title: `Analysis-I`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA3703`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA3703.docx`,
  course_title: `Algebra-I`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `CS3701`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/CS3701.docx`,
  course_title: `Object oriented Methodology`,
  l: `l3`,
  t: `t0`,
  p: `p0`,
  credits: `c3`,
  dept: `mmCSE`,
  type: `Foundation`,
 },
 {
  course_code: `CSL3701`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/CSL3701.docx`,
  course_title: `Object oriented Methodology lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `CSE`,
  type: `Lab`,
 },
 {
  course_code: `HS3701`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/HS3701.docx`,
  course_title: `Industrial Economics and Financial Management`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `HSS`,
  type: `Foundation`,
 },
 {
  course_code: `-`,
  course_title: `Total Credit`,
  l: `15`,
  t: `3`,
  p: `3`,
  credits: `19`,
  dept: `-`,
  type: `-`,
 },
 {
  course_code: `MA4701`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA4701.docx`,
  course_title: `Probability & Statistics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA4702`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA4702.docx`,
  course_title: `Theory of Linear Algebra`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA4703`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA4703.docx`,
  course_title: `Ordinary Differential Equation`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA4704`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA4704.docx`,
  course_title: `Introduction to Data Structures and Algorithms`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MAL4701`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MAL4701.docx`,
  course_title: `Data Structure and Algorithms Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `MA`,
  type: `Lab`,
 },
 {
  course_code: `OE****`,
  course_title: `Open Elective-I`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `Other`,
  type: `OE`,
 },
 {
  course_code: `-`,
  course_title: `Total Credit`,
  l: `15`,
  t: `3`,
  p: `3`,
  credits: `19`,
  dept: `-`,
  type: `-`,
 },
 {
  course_code: `MA5701`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA5701.docx`,
  course_title: `Topology`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA5702`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA5702.docx`,
  course_title: `Analysis-II`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA5703`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA5703.docx`,
  course_title: `Mathematical Methods-I`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA5704`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA5704.docx`,
  course_title: `Functional Analysis`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA5705`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA5705.docx`,
  course_title: `Numerical Analysis`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MAL5705`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA5705.docx`,
  course_title: `Numerical Analysis Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `MA`,
  type: `Lab`,
 },
 {
  course_code: `-`,
  course_title: `Total Credit`,
  l: `15`,
  t: `5`,
  p: `3`,
  credits: `21`,
  dept: `-`,
  type: `-`,
 },
 {
  course_code: `MA6701`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA6701.docx`,
  course_title: `Linear Programming Problem and Game Theory`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA6702`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA6702.docx`,
  course_title: `Measure Theory and Integration`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA6703`,
  course_title: `Seminar`,
  l: `0`,
  t: `0`,
  p: `6`,
  credits: `2`,
  dept: `MA`,
  type: `Seminar`,
 },
 {
  course_code: `MA****`,
  course_title: `Elective-I`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `MA`,
  type: `Dept. Elective`,
 },
 {
  course_code: `MA****`,
  course_title: `Elective - II`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `MA`,
  type: `Dept. Elective`,
 },
 {
  course_code: `OE****`,
  course_title: `Open Elective-II`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `Other`,
  type: `OE`,
 },
 {
  course_code: `-`,
  course_title: `Total Credit`,
  l: `12`,
  t: `2`,
  p: `6`,
  credits: `19`,
  dept: `-`,
  type: `-`,
 },
 {
  course_code: `MA7701`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA7701.docx`,
  course_title: `Integral Equation and Calculus of Variation`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA7702`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA7702.docx`,
  course_title: `Numerical Solutions of Ordinary and Partial Differentiation Equations`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MAL7701`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MAL7701.docx`,
  course_title: `Numerical ODE and PDE lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
  dept: `MA`,
  type: `Lab`,
 },
 {
  course_code: `MA****`,
  course_title: `Elective-III`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `MA`,
  type: `Dept. Elective`,
 },
 {
  course_code: `MA****`,
  course_title: `Elective-IV`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `MA`,
  type: `Dept. Elective`,
 },
 {
  course_code: `OE****`,
  course_title: `Open Elective-III`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `Other`,
  type: `OE`,
 },
 {
  course_code: `-`,
  course_title: `Total Credit`,
  l: `15`,
  t: `2`,
  p: `3`,
  credits: `18`,
  dept: `-`,
  type: `-`,
 },
 {
  course_code: `MA8701`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA8701.docx`,
  course_title: `Theory of Computation`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA8702`,
  url: `${process.env.GATSBY_BASE_URL}math/syllabus/MA8702.docx`,
  course_title: `Complex Analysis`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
  dept: `MA`,
  type: `Core`,
 },
 {
  course_code: `MA****`,
  course_title: `Elective-V`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `MA`,
  type: `Dept. Elective`,
 },
 {
  course_code: `MA****`,
  course_title: `Elective-VI`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `MA`,
  type: `Dept. Elective`,
 },
 {
  course_code: `MA8703`,
  course_title: `Minor Project`,
  l: `0`,
  t: `0`,
  p: `6`,
  credits: `4`,
  dept: `MA`,
  type: `Project`,
 },
 {
  course_code: `OE****`,
  course_title: `Open Elective-IV`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
  dept: `Other`,
  type: `OE`,
 },
 {
  course_code: `-`,
  course_title: `Total Credit`,
  l: `15`,
  t: `2`,
  p: `6`,
  credits: `21`,
  dept: `-`,
  type: `-`,
 },
 {
  course_code: `****`,
  course_title: `Electives/Open Elective/Swayam/MOOC course`,
  l: `0`,
  t: `3`,
  p: `0`,
  credits: `3`,
  dept: `-`,
  type: `Online`,
 },
 {
  course_code: `MA9701`,
  course_title: `Seminar and Comprehensive Viva-I`,
  l: `0`,
  t: `0`,
  p: `6`,
  credits: `2`,
  dept: `MA`,
  type: `Seminar`,
 },
 {
  course_code: `MA9702`,
  course_title: `Thesis(to be continued)`,
  l: `0`,
  t: `0`,
  p: `48`,
  credits: `16`,
  dept: `MA`,
  type: `Project`,
 },
 {
  course_code: `-`,
  course_title: `Total Credit`,
  l: `0`,
  t: `3`,
  p: `54`,
  credits: `21`,
  dept: `-`,
  type: `-`,
 },
 {
  course_code: `****`,
  course_title: `Electives/Open Elective/Swayam/MOOC course`,
  l: `0`,
  t: `3`,
  p: `0`,
  credits: `3`,
  dept: `-`,
  type: `Online`,
 },
 {
  course_code: `MA10701`,
  course_title: `Seminar and Comprehensive Viva-II`,
  l: `0`,
  t: `0`,
  p: `6`,
  credits: `2`,
  dept: `MA`,
  type: `Seminar`,
 },
 {
  course_code: `MA10702`,
  course_title: `Thesis`,
  l: `0`,
  t: `0`,
  p: `48`,
  credits: `16`,
  dept: `MA`,
  type: `Project`,
 },
 {
  course_code: `-`,
  course_title: `Total Credit`,
  l: `0`,
  t: `3`,
  p: `54`,
  credits: `21`,
  dept: `-`,
  type: `-`,
 },
]
export default IMScMathCourseStructure
