import React from "react"

const ArchitectureCourse = [
 {
  dept: `ARUG`,
  sem_elect: `1`,
  course_code: `GE101`,
  coursetitle: `PARICHAY`,
  l: `0`,
  t: `0`,
  p: `1`,
  credits: `0`,
 },
 {
  dept: `ARUG`,
  sem_elect: `1`,
  course_code: `1HS101`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/HS101.docx`,
  coursetitle: `English Literature`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `ARUG`,
  sem_elect: `1`,
  course_code: `1MA103`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/MA101.docx`,
  coursetitle: `Enginlring Mathematics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `ARUG`,
  sem_elect: `1`,
  course_code: `1CS101`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/CS101.docx`,
  coursetitle: `Introduction to computing`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `1`,
  course_code: `1CS102`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/CS102.docx`,
  coursetitle: `Computing Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `ARUG`,
  sem_elect: `1`,
  course_code: `1ME102`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/ME102.docx`,
  coursetitle: `Workshop Practice`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `ARUG`,
  sem_elect: `1`,
  course_code: `1AR101`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR101.docx`,
  coursetitle: `Basic Design 1`,
  l: `2`,
  t: `0`,
  p: `4`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `1`,
  course_code: `1AR102`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR102.docx`,
  coursetitle: `Architectural Graphics 1`,
  l: `1`,
  t: `0`,
  p: `6`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `1`,
  course_code: `1AR103`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR103.docx`,
  coursetitle: `History of Art,Architectural & Culture`,
  l: `2`,
  t: `0`,
  p: `2`,
  credits: `3`,
 },

 {
  dept: `ARUG`,
  sem_elect: `2`,
  course_code: `2HS102`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/HS102.docx`,
  coursetitle: `Communication Skills Development & Technical Writing`,
  l: `0`,
  t: `1`,
  p: `3`,
  credits: `2`,
 },
 {
  dept: `ARUG`,
  sem_elect: `2`,
  course_code: `2CE101`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/CE101.docx`,
  coursetitle: `Enginlring Mechanics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `ARUG`,
  sem_elect: `2`,
  course_code: `2HS105`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/HS105.docx`,
  coursetitle: `Science Society and Ethical Values`,
  l: `1`,
  t: `1`,
  p: `0`,
  credits: `2`,
 },
 {
  dept: `ARUG`,
  sem_elect: `2`,
  course_code: `2AR111`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR111.docx`,
  coursetitle: `Basic Design II`,
  l: `1`,
  t: `1`,
  p: `6`,
  credits: `4`,
 },
 {
  dept: `ARUG`,
  sem_elect: `2`,
  course_code: `2AR112`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR112.docx`,
  coursetitle: `Architectural Graphics II`,
  l: `1`,
  t: `0`,
  p: `6`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `2`,
  course_code: `2AR113`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR113.docx`,
  coursetitle: `Architectural workshop`,
  l: `0`,
  t: `0`,
  p: `4`,
  credits: `1`,
 },
 {
  dept: `ARUG`,
  sem_elect: `2`,
  course_code: `2AR114`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR114.docx`,
  coursetitle: `History of Architecture-I`,
  l: `2`,
  t: `0`,
  p: `2`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `2`,
  course_code: `2AR115`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR115.docx`,
  coursetitle: `Principal of Architecture`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `ARUG`,
  sem_elect: `2`,
  course_code: `2AR119`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR119.docx`,
  coursetitle: `Seminar/Educational Tour/NASA/Zonasa-I`,
  l: `0`,
  t: `0`,
  p: `0`,
  credits: `0`,
 },

 {
  dept: `ARUG`,
  sem_elect: `2`,
  course_code: `2GE105`,
  coursetitle: `E"dept"-II NSS`,
  l: `0`,
  t: `0`,
  p: `1`,
  credits: `0`,
 },

 {
  dept: `ARUG`,
  sem_elect: `3`,
  course_code: `3AR121`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR121.docx`,
  coursetitle: `Architectural Design-I & Field Study`,
  l: `3`,
  t: `0`,
  p: `6`,
  credits: `5`,
 },
 {
  dept: `ARUG`,
  sem_elect: `3`,
  course_code: `3AR122`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR122.docx`,
  coursetitle: `Building Construction-I`,
  l: `2`,
  t: `0`,
  p: `4`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `3`,
  course_code: `3AR123`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR123.docx`,
  coursetitle: `History of Architecture-II`,
  l: `2`,
  t: `0`,
  p: `2`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `3`,
  course_code: `3AR124`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR124.docx`,
  coursetitle: `Building Materials(Material Science & Technology)`,
  l: `1`,
  t: `1`,
  p: `0`,
  credits: `2`,
 },
 {
  dept: `ARUG`,
  sem_elect: `3`,
  course_code: `3AR125`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR125.docx`,
  coursetitle: `Climatology and Solar Passive Architecture`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `3`,
  course_code: `3AR127`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR127.docx`,
  coursetitle: `Structure,Form & Architecture`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `3`,
  course_code: `3AR126`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR126.docx`,
  coursetitle: `Computer Application in Architecture`,
  l: `0`,
  t: `0`,
  p: `4`,
  credits: `1`,
 },

 {
  dept: `ARUG`,
  sem_elect: `3`,
  course_code: `3CH104`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/CE102.docx`,
  coursetitle: `Grln Technology(Environmental Science)`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `ARUG`,
  sem_elect: `3`,
  course_code: `3GE105`,
  coursetitle: `E"dept"-III NSS`,
  l: `0`,
  t: `0`,
  p: `1`,
  credits: `0`,
 },

 {
  dept: `ARUG`,
  sem_elect: `4`,
  course_code: `4AR131`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR131.docx`,
  coursetitle: `Architectural Design - II & field study`,
  l: `3`,
  t: `0`,
  p: `6`,
  credits: `5`,
 },
 {
  dept: `ARUG`,
  sem_elect: `4`,
  course_code: `4AR132`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR132.docx`,
  coursetitle: `Building Construction - II`,
  l: `2`,
  t: `0`,
  p: `4`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `4`,
  course_code: `4AR133`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR133.docx`,
  coursetitle: `Contemporary Architecture`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `4`,
  course_code: `4AR142`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR142.docx`,
  coursetitle: `Building Services(Water Supply and Sanitation)`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `4`,
  course_code: `4AR149`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR149.docx`,
  coursetitle: `Seminar/Educational Tour/NASA/Zonasa-II`,
  l: `0`,
  t: `0`,
  p: `1`,
  credits: `0`,
 },
 {
  dept: `ARUG`,
  sem_elect: `4`,
  course_code: `4CE201`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/CE108.docx`,
  coursetitle: ` Basic Surveying`,
  l: `3`,
  t: `0`,
  p: `3`,
  credits: `4`,
 },
 {
  dept: `ARUG`,
  sem_elect: `4`,
  course_code: `4CE202`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/CE116.docx`,
  coursetitle: ` Structural Mechanics `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `4`,
  course_code: `4CH105`,
  coursetitle: `Bio Science`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `ARUG`,
  sem_elect: `4`,
  course_code: `GE105`,
  coursetitle: `E"dept"-IV NSS`,
  l: `0`,
  t: `0`,
  p: `1`,
  credits: `0`,
 },

 {
  dept: `ARUG`,
  sem_elect: `5`,
  course_code: `5AR141`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR141.docx`,
  coursetitle: `Architectural Design - III & Field Study`,
  l: `3`,
  t: `0`,
  p: `6`,
  credits: `5`,
 },
 {
  dept: `ARUG`,
  sem_elect: `5`,
  course_code: `5AR143`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR143.docx`,
  coursetitle: `Building Construction - III`,
  l: `1`,
  t: `0`,
  p: `4`,
  credits: `2`,
 },
 {
  dept: `ARUG`,
  sem_elect: `5`,
  course_code: `5AR144`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR144.docx`,
  coursetitle: `Human Settlement & Vernacular Architecture`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `5`,
  course_code: `5AR145`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR145.docx`,
  coursetitle: `Building Services(Illumination,Electrical Services and Acoustics)`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `5`,
  course_code: `5AR146`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR146.docx`,
  coursetitle: `Quantity Survey & Specifications`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `5`,
  course_code: `5HS106`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/HS106.docx`,
  coursetitle: `Sociology and Building Economics `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `ARUG`,
  sem_elect: `5`,
  course_code: `5CE203`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/CE107.docx`,
  coursetitle: `Indeterminate Structures`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `ARUG`,
  sem_elect: `5`,
  course_code: `GE105`,
  coursetitle: `E"dept"-V NSS`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `0`,
 },

 {
  dept: `ARUG`,
  sem_elect: `6`,
  course_code: `AR 151`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR151.docx`,
  coursetitle: `Architectural Design - IV & Field Study`,
  l: `3`,
  t: `0`,
  p: `6`,
  credits: `5`,
 },
 {
  dept: `ARUG`,
  sem_elect: `6`,
  course_code: `AR152`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR152.docx`,
  coursetitle: `Building Construction-IV`,
  l: `1`,
  t: `0`,
  p: `4`,
  credits: `2`,
 },
 {
  dept: `ARUG`,
  sem_elect: `6`,
  course_code: `AR153`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR153.docx`,
  coursetitle: `Housing`,
  l: `2`,
  t: `0`,
  p: `2`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `6`,
  course_code: `AR154`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR154.docx`,
  coursetitle: `Departmental Elective-I `,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `6`,
  course_code: `ME120`,
  url: ` ./archi/ME120.docx`,
  coursetitle: `Building Services (HVAC) `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `6`,
  course_code: `AR155`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR155.docx`,
  coursetitle: `Building Byelaws and Codes of Practice `,
  l: `2`,
  t: `0`,
  p: `0`,
  credits: `2`,
 },
 {
  dept: `ARUG`,
  sem_elect: `6`,
  course_code: `CE123`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/CE123.docx`,
  coursetitle: `Concrete Structure `,
  l: `0`,
  t: `0`,
  p: `2`,
  credits: `1`,
 },
 {
  dept: `ARUG`,
  sem_elect: `6`,
  course_code: `XX1XX`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/XX1XX.docx`,
  coursetitle: `Enginlring/HSS/Science/department (Elective-1)  `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `6`,
  course_code: `GE106`,
  coursetitle: `E"dept"-VI NSS`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `0`,
 },

 {
  dept: `ARUG`,
  sem_elect: `7`,
  course_code: `AR161`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR161.docx`,
  coursetitle: `Architectural Design - V & Field Study`,
  l: `3`,
  t: `0`,
  p: `6`,
  credits: `5`,
 },
 {
  dept: `ARUG`,
  sem_elect: `7`,
  course_code: `AR162`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR162.docx`,
  coursetitle: `Architectural Detailing`,
  l: `2`,
  t: `0`,
  p: `4`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `7`,
  course_code: `AR163`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR163.docx`,
  coursetitle: `City Planning`,
  l: `2`,
  t: `0`,
  p: `2`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `7`,
  course_code: `AR164`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR164.docx`,
  coursetitle: `Urban Design`,
  l: `2`,
  t: `0`,
  p: `3`,
  credits: `4`,
 },
 {
  dept: `ARUG`,
  sem_elect: `7`,
  course_code: `CE129`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/CE129.docx`,
  coursetitle: `Design of Stll Structure / Concrete str.`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `7`,
  course_code: `XX1XX`,
  coursetitle: `Enginlring/HSS/Science/Department (elective-2)`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `ARUG`,
  sem_elect: `8`,
  course_code: `AR171`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR171.docx`,
  coursetitle: `Architectural Design - VI & Field Study`,
  l: `3`,
  t: `0`,
  p: `6`,
  credits: `5`,
 },
 {
  dept: `ARUG`,
  sem_elect: `8`,
  course_code: `AR172`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR172.docx`,
  coursetitle: `Working Drawing`,
  l: `1`,
  t: `0`,
  p: `4`,
  credits: `2`,
 },
 {
  dept: `ARUG`,
  sem_elect: `8`,
  course_code: `AR173`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR173.docx`,
  coursetitle: `Landscape Design & Ecological Architecture`,
  l: `2`,
  t: `0`,
  p: `2`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `8`,
  course_code: `AR174`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/Ar174.docx`,
  coursetitle: `Disaster Resistant Architecture & Management`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `8`,
  course_code: `AR2xx`,
  coursetitle: `Departmental Elective-III`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `8`,
  course_code: `AR175`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR175.docx`,
  coursetitle: `Project Planning & Management`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `8`,
  course_code: `xx1xx`,
  coursetitle: `Enginlring/HSS/Science/Department (Elective-3)`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `8`,
  course_code: `GE107`,
  coursetitle: `E"dept"-III NSS`,
  l: `0`,
  t: `0`,
  p: `0`,
  credits: `0`,
 },

 {
  dept: `ARUG`,
  sem_elect: `9`,
  course_code: `AR192`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR192.docx`,
  coursetitle: `Architectural Training`,
  l: `0`,
  t: `0`,
  p: `60`,
  credits: `20`,
 },

 {
  dept: `ARUG`,
  sem_elect: `10`,
  course_code: `AR194`,
  coursetitle: `Project (Thesis)`,
  l: `0`,
  t: `0`,
  p: `60`,
  credits: `20`,
 },
 {
  dept: `ARUG`,
  sem_elect: `10`,
  course_code: `AR193`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR193.docx`,
  coursetitle: `Professional Practice,Valuation & Management`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `10`,
  course_code: `AR2XX`,
  coursetitle: `Departmental elective-IV`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `ARUG`,
  sem_elect: `EL I`,
  course_code: `AR201`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR201.docx`,
  coursetitle: `Design for Barrier Frl Environment`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL I`,
  course_code: `AR202`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/Ar202.docx`,
  coursetitle: `Building Software lab`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL I`,
  course_code: `AR203`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR203.docx`,
  coursetitle: `Vastushastra`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL II`,
  course_code: `AR204`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR204.docx`,
  coursetitle: `Art In Architecture`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL II`,
  course_code: `AR211`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR211.docx`,
  coursetitle: `Architectural Conservation`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL II`,
  course_code: `AR212`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR212.docx`,
  coursetitle: `Sustainable Architecture`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL III`,
  course_code: `AR213`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/Ar213.docx`,
  coursetitle: `Visual Semantics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL III`,
  course_code: `AR214`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/Ar214.docx`,
  coursetitle: `Modular Co-ordination`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL III`,
  course_code: `AR215`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR215.docx`,
  coursetitle: `Facility planning and Specialized Building Design`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL III`,
  course_code: `AR221`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR221.docx`,
  coursetitle: `Interior Design`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL III`,
  course_code: `AR222`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR222.docx`,
  coursetitle: `Intelligent Buildings`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL III`,
  course_code: `AR223`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR223.docx`,
  coursetitle: `Building Automation and Management System`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL III`,
  course_code: `AR224`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR224.docx`,
  coursetitle: `Behavioral Studies in Architecture`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL III`,
  course_code: `AR225`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR225.docx`,
  coursetitle: `Ergonomics and Product Design`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL IV`,
  course_code: `AR231`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR231.docx`,
  coursetitle: `Energy Conscious Architecture`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL IV`,
  course_code: `AR232`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR232.docx`,
  coursetitle: `Appropriate Building Technology`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL IV`,
  course_code: `AR233`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR233.docx`,
  coursetitle: `Futuristic Architecture`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `ARUG`,
  sem_elect: `EL III`,
  course_code: `AR234`,
  url: `${process.env.GATSBY_BASE_URL}arch/syllabus/AR234.docx`,
  coursetitle: `Marketing skill`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
]
export default ArchitectureCourse
