import React from "react"

const ArchitectureCourse = [
  {
    deptt: `ARUG`,
    sem_elect: `1`,
    course_code: `GE101`,
    course_title: `PARICHAY`,
    l: `0`,
    t: `0`,
    p: `1`,
    credits: `0`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `1`,
    course_code: `1HS101`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/HS101.docx`,
    course_title: `English Literature`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `1`,
    course_code: `1MA103`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/MA101.docx`,
    course_title: `Enginlring Mathematics`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `1`,
    course_code: `1CS101`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/CS101.docx`,
    course_title: `Introduction to computing`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `1`,
    course_code: `1CS102`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/CS102.docx`,
    course_title: `Computing Lab`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `1`,
    course_code: `1ME102`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/ME102.docx`,
    course_title: `Workshop Practice`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `1`,
    course_code: `1AR101`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR101.docx`,
    course_title: `Basic Design 1`,
    l: `2`,
    t: `0`,
    p: `4`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `1`,
    course_code: `1AR102`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR102.docx`,
    course_title: `Architectural Graphics 1`,
    l: `1`,
    t: `0`,
    p: `6`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `1`,
    course_code: `1AR103`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR103.docx`,
    course_title: `History of Art,Architectural & Culture`,
    l: `2`,
    t: `0`,
    p: `2`,
    credits: `3`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `2`,
    course_code: `2HS102`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/HS102.docx`,
    course_title: `Communication Skills Development & Technical Writing`,
    l: `0`,
    t: `1`,
    p: `3`,
    credits: `2`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `2`,
    course_code: `2CE101`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/CE101.docx`,
    course_title: `Enginlring Mechanics`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `2`,
    course_code: `2HS105`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/HS105.docx`,
    course_title: `Science Society and Ethical Values`,
    l: `1`,
    t: `1`,
    p: `0`,
    credits: `2`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `2`,
    course_code: `2AR111`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR111.docx`,
    course_title: `Basic Design II`,
    l: `1`,
    t: `1`,
    p: `6`,
    credits: `4`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `2`,
    course_code: `2AR112`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR112.docx`,
    course_title: `Architectural Graphics II`,
    l: `1`,
    t: `0`,
    p: `6`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `2`,
    course_code: `2AR113`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR113.docx`,
    course_title: `Architectural workshop`,
    l: `0`,
    t: `0`,
    p: `4`,
    credits: `1`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `2`,
    course_code: `2AR114`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR114.docx`,
    course_title: `History of Architecture-I`,
    l: `2`,
    t: `0`,
    p: `2`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `2`,
    course_code: `2AR115`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR115.docx`,
    course_title: `Principal of Architecture`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `2`,
    course_code: `2AR119`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR119.docx`,
    course_title: `Seminar/Educational Tour/NASA/Zonasa-I`,
    l: `0`,
    t: `0`,
    p: `0`,
    credits: `0`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `2`,
    course_code: `2GE105`,
    course_title: `Edeptt-II NSS`,
    l: `0`,
    t: `0`,
    p: `1`,
    credits: `0`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `3`,
    course_code: `3AR121`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR121.docx`,
    course_title: `Architectural Design-I & Field Study`,
    l: `3`,
    t: `0`,
    p: `6`,
    credits: `5`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `3`,
    course_code: `3AR122`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR122.docx`,
    course_title: `Building Construction-I`,
    l: `2`,
    t: `0`,
    p: `4`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `3`,
    course_code: `3AR123`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR123.docx`,
    course_title: `History of Architecture-II`,
    l: `2`,
    t: `0`,
    p: `2`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `3`,
    course_code: `3AR124`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR124.docx`,
    course_title: `Building Materials(Material Science & Technology)`,
    l: `1`,
    t: `1`,
    p: `0`,
    credits: `2`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `3`,
    course_code: `3AR125`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR125.docx`,
    course_title: `Climatology and Solar Passive Architecture`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `3`,
    course_code: `3AR127`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR127.docx`,
    course_title: `Structure,Form & Architecture`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `3`,
    course_code: `3AR126`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR126.docx`,
    course_title: `Computer Application in Architecture`,
    l: `0`,
    t: `0`,
    p: `4`,
    credits: `1`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `3`,
    course_code: `3CH104`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/CE102.docx`,
    course_title: `Grln Technology(Environmental Science)`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `3`,
    course_code: `3GE105`,
    course_title: `Edeptt-III NSS`,
    l: `0`,
    t: `0`,
    p: `1`,
    credits: `0`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `4`,
    course_code: `4AR131`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR131.docx`,
    course_title: `Architectural Design - II & field study`,
    l: `3`,
    t: `0`,
    p: `6`,
    credits: `5`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `4`,
    course_code: `4AR132`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR132.docx`,
    course_title: `Building Construction - II`,
    l: `2`,
    t: `0`,
    p: `4`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `4`,
    course_code: `4AR133`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR133.docx`,
    course_title: `Contemporary Architecture`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `4`,
    course_code: `4AR142`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR142.docx`,
    course_title: `Building Services(Water Supply and Sanitation)`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `4`,
    course_code: `4AR149`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR149.docx`,
    course_title: `Seminar/Educational Tour/NASA/Zonasa-II`,
    l: `0`,
    t: `0`,
    p: `1`,
    credits: `0`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `4`,
    course_code: `4CE201`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/CE108.docx`,
    course_title: ` Basic Surveying`,
    l: `3`,
    t: `0`,
    p: `3`,
    credits: `4`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `4`,
    course_code: `4CE202`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/CE116.docx`,
    course_title: ` Structural Mechanics `,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `4`,
    course_code: `4CH105`,
    course_title: `Bio Science`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `4`,
    course_code: `GE105`,
    course_title: `Edeptt-IV NSS`,
    l: `0`,
    t: `0`,
    p: `1`,
    credits: `0`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `5`,
    course_code: `5AR141`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR141.docx`,
    course_title: `Architectural Design - III & Field Study`,
    l: `3`,
    t: `0`,
    p: `6`,
    credits: `5`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `5`,
    course_code: `5AR143`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR143.docx`,
    course_title: `Building Construction - III`,
    l: `1`,
    t: `0`,
    p: `4`,
    credits: `2`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `5`,
    course_code: `5AR144`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR144.docx`,
    course_title: `Human Settlement & Vernacular Architecture`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `5`,
    course_code: `5AR145`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR145.docx`,
    course_title: `Building Services(Illumination,Electrical Services and Acoustics)`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `5`,
    course_code: `5AR146`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR146.docx`,
    course_title: `Quantity Survey & Specifications`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `5`,
    course_code: `5HS106`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/HS106.docx`,
    course_title: `Sociology and Building Economics `,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `5`,
    course_code: `5CE203`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/CE107.docx`,
    course_title: `Indeterminate Structures`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `5`,
    course_code: `GE105`,
    course_title: `Edeptt-V NSS`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `0`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `6`,
    course_code: `AR 151`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR151.docx`,
    course_title: `Architectural Design - IV & Field Study`,
    l: `3`,
    t: `0`,
    p: `6`,
    credits: `5`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `6`,
    course_code: `AR152`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR152.docx`,
    course_title: `Building Construction-IV`,
    l: `1`,
    t: `0`,
    p: `4`,
    credits: `2`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `6`,
    course_code: `AR153`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR153.docx`,
    course_title: `Housing`,
    l: `2`,
    t: `0`,
    p: `2`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `6`,
    course_code: `AR154`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR154.docx`,
    course_title: `Departmental Elective-I `,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `6`,
    course_code: `ME120`,
    url: ` ./archi/ME120.docx`,
    course_title: `Building Services (HVAC) `,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `6`,
    course_code: `AR155`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR155.docx`,
    course_title: `Building Byelaws and Codes of Practice `,
    l: `2`,
    t: `0`,
    p: `0`,
    credits: `2`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `6`,
    course_code: `CE123`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/CE123.docx`,
    course_title: `Concrete Structure `,
    l: `0`,
    t: `0`,
    p: `2`,
    credits: `1`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `6`,
    course_code: `XX1XX`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/XX1XX.docx`,
    course_title: `Enginlring/HSS/Science/department (Elective-1)  `,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `6`,
    course_code: `GE106`,
    course_title: `Edeptt-VI NSS`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `0`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `7`,
    course_code: `AR161`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR161.docx`,
    course_title: `Architectural Design - V & Field Study`,
    l: `3`,
    t: `0`,
    p: `6`,
    credits: `5`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `7`,
    course_code: `AR162`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR162.docx`,
    course_title: `Architectural Detailing`,
    l: `2`,
    t: `0`,
    p: `4`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `7`,
    course_code: `AR163`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR163.docx`,
    course_title: `City Planning`,
    l: `2`,
    t: `0`,
    p: `2`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `7`,
    course_code: `AR164`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR164.docx`,
    course_title: `Urban Design`,
    l: `2`,
    t: `0`,
    p: `3`,
    credits: `4`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `7`,
    course_code: `CE129`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/CE129.docx`,
    course_title: `Design of Stll Structure / Concrete str.`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `7`,
    course_code: `XX1XX`,
    course_title: `Enginlring/HSS/Science/Department (elective-2)`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `8`,
    course_code: `AR171`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR171.docx`,
    course_title: `Architectural Design - VI & Field Study`,
    l: `3`,
    t: `0`,
    p: `6`,
    credits: `5`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `8`,
    course_code: `AR172`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR172.docx`,
    course_title: `Working Drawing`,
    l: `1`,
    t: `0`,
    p: `4`,
    credits: `2`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `8`,
    course_code: `AR173`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR173.docx`,
    course_title: `Landscape Design & Ecological Architecture`,
    l: `2`,
    t: `0`,
    p: `2`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `8`,
    course_code: `AR174`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/Ar174.docx`,
    course_title: `Disaster Resistant Architecture & Management`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `8`,
    course_code: `AR2xx`,
    course_title: `Departmental Elective-III`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `8`,
    course_code: `AR175`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR175.docx`,
    course_title: `Project Planning & Management`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `8`,
    course_code: `xx1xx`,
    course_title: `Enginlring/HSS/Science/Department (Elective-3)`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `8`,
    course_code: `GE107`,
    course_title: `Edeptt-III NSS`,
    l: `0`,
    t: `0`,
    p: `0`,
    credits: `0`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `9`,
    course_code: `AR192`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR192.docx`,
    course_title: `Architectural Training`,
    l: `0`,
    t: `0`,
    p: `60`,
    credits: `20`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `10`,
    course_code: `AR194`,
    course_title: `Project (Thesis)`,
    l: `0`,
    t: `0`,
    p: `60`,
    credits: `20`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `10`,
    course_code: `AR193`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR193.docx`,
    course_title: `Professional Practice,Valuation & Management`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `10`,
    course_code: `AR2XX`,
    course_title: `Departmental elective-IV`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },

  {
    deptt: `ARUG`,
    sem_elect: `EL I`,
    course_code: `AR201`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR201.docx`,
    course_title: `Design for Barrier Frl Environment`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL I`,
    course_code: `AR202`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/Ar202.docx`,
    course_title: `Building Software lab`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL I`,
    course_code: `AR203`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR203.docx`,
    course_title: `Vastushastra`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL II`,
    course_code: `AR204`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR204.docx`,
    course_title: `Art In Architecture`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL II`,
    course_code: `AR211`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR211.docx`,
    course_title: `Architectural Conservation`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL II`,
    course_code: `AR212`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR212.docx`,
    course_title: `Sustainable Architecture`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL III`,
    course_code: `AR213`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/Ar213.docx`,
    course_title: `Visual Semantics`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL III`,
    course_code: `AR214`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/Ar214.docx`,
    course_title: `Modular Co-ordination`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL III`,
    course_code: `AR215`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR215.docx`,
    course_title: `Facility planning and Specialized Building Design`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL III`,
    course_code: `AR221`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR221.docx`,
    course_title: `Interior Design`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL III`,
    course_code: `AR222`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR222.docx`,
    course_title: `Intelligent Buildings`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL III`,
    course_code: `AR223`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR223.docx`,
    course_title: `Building Automation and Management System`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL III`,
    course_code: `AR224`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR224.docx`,
    course_title: `Behavioral Studies in Architecture`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL III`,
    course_code: `AR225`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR225.docx`,
    course_title: `Ergonomics and Product Design`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL IV`,
    course_code: `AR231`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR231.docx`,
    course_title: `Energy Conscious Architecture`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL IV`,
    course_code: `AR232`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR232.docx`,
    course_title: `Appropriate Building Technology`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL IV`,
    course_code: `AR233`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR233.docx`,
    course_title: `Futuristic Architecture`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    deptt: `ARUG`,
    sem_elect: `EL III`,
    course_code: `AR234`,
    url: `https://web.nitp.ac.in/dept/arch/syllabus/AR234.docx`,
    course_title: `Marketing skill`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
]
export default ArchitectureCourse
