const MTech = [
 {
  dept: "MURP Semester- I",
  Group: "",
  sem_elect: null,
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 1,
  coursecode: "AR601",
  coursetitle: "Planning Principles & Techniques",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 1,
  coursecode: "AR602",
  coursetitle: "Infrastructure Planning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 1,
  coursecode: "AR605",
  coursetitle: "Traffic and Transportaion Planning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-1",
  sem_elect: 1,
  coursecode: "MA6xx/AR6ww",
  coursetitle: "Elective-I",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-2",
  sem_elect: 1,
  coursecode: "AR6xx",
  coursetitle: "Elective - II",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Lab",
  sem_elect: 1,
  coursecode: "AR691",
  coursetitle: "Urban & Regional Planning Workshop-I",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
  TOTAL: 19,
 },
 {
  dept: "MURP Semester- II",
  Group: "",
  sem_elect: null,
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 2,
  coursecode: "AR604",
  coursetitle: "Urban & Regional Planning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 2,
  coursecode: "AR648",
  coursetitle: "Planning legislation and Professional Practice",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 2,
  coursecode: "AR608",
  coursetitle: "Development Management and Finance",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 2,
  coursecode: "AR6YY",
  coursetitle: "Elective - III",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 2,
  coursecode: "AR6zz",
  coursetitle: "Elective - IV",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 2,
  coursecode: "AR692",
  coursetitle: "Urban and Planning Workshop- II",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 2,
  coursecode: "AR693",
  coursetitle: "Seminar",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
  TOTAL: 21,
 },
 {
  dept: "MURP Semester- III",
  Group: "",
  sem_elect: null,
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Lab",
  sem_elect: 3,
  coursecode: "AR694",
  coursetitle: "Seminar and Comprehensive Viva - I",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 3,
  coursecode: "ME 701",
  coursetitle: "Research Methodology",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Core",
  sem_elect: 3,
  coursecode: "AR695",
  coursetitle: "Dissertation (to be continued in 4th Sem)",
  l: 0,
  t: 0,
  p: 12,
  credits: 8,
  TOTAL: 13,
 },
 {
  dept: "MURP Semester- IV",
  Group: "",
  sem_elect: null,
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Lab",
  sem_elect: 4,
  coursecode: "AR696",
  coursetitle: "Seminar and Comprehensive Viva - II",
  l: 3,
  t: 0,
  p: 3,
  credits: 2,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Lab",
  sem_elect: 4,
  coursecode: "AR697",
  coursetitle: "Dissertation",
  l: 0,
  t: 0,
  p: 15,
  credits: 10,
  TOTAL: 12,
 },
 {
  dept: "Elective Papers",
  Group: "",
  sem_elect: null,
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "",
  sem_elect: null,
  coursecode: "",
  coursetitle: "Elective- I (WW)*",
  l: null,
  t: null,
  p: null,
  credits: null,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-1",
  sem_elect: 1,
  coursecode: "MA603",
  coursetitle: "Statics and Computer Programming",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-1",
  sem_elect: 1,
  coursecode: "MA604",
  coursetitle: "Probability and Statics",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-1",
  sem_elect: 1,
  coursecode: "MA605",
  coursetitle: "Linear Programming",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-1",
  sem_elect: 1,
  coursecode: "AR641",
  coursetitle: "Demography and Quantitative Techniques",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "",
  sem_elect: null,
  coursecode: "",
  coursetitle: "Elective- II (XX)*",
  l: null,
  t: null,
  p: null,
  credits: null,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-2",
  sem_elect: 1,
  coursecode: "AR644",
  coursetitle: "Settlement System Planning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-2",
  sem_elect: 1,
  coursecode: "AR648",
  coursetitle: "Rural Area Planning and Management",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-2",
  sem_elect: 1,
  coursecode: "AR650",
  coursetitle: "Regional Analysis and Programming",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-2",
  sem_elect: 1,
  coursecode: "AR651",
  coursetitle: "Urban Design and Landscape Planning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "",
  sem_elect: null,
  coursecode: "",
  coursetitle: "Elective- III (YY)*",
  l: null,
  t: null,
  p: null,
  credits: null,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-3",
  sem_elect: 2,
  coursecode: "AR649",
  coursetitle: "City and Metropolitan Planning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-3",
  sem_elect: 2,
  coursecode: "AR652",
  coursetitle: "Housing and Community Planning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-3",
  sem_elect: 2,
  coursecode: "AR653",
  coursetitle: "Heritage and Urban Conservation",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "",
  sem_elect: null,
  coursecode: "",
  coursetitle: "Elective- IV (ZZ)*",
  l: null,
  t: null,
  p: null,
  credits: null,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-4",
  sem_elect: 2,
  coursecode: "AR654",
  coursetitle: "Sustainable Development",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-2",
  sem_elect: 1,
  coursecode: "AR655",
  coursetitle: "Remote Sensing and GIS in Planning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "EL-4",
  sem_elect: 2,
  coursecode: "AR656",
  coursetitle: "Rsilient Urban Planning",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
 {
  dept: "Audit Course",
  Group: "",
  sem_elect: null,
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  TOTAL: null,
 },
 {
  dept: "MURP",
  Group: "Audit",
  sem_elect: null,
  coursecode: "",
  coursetitle: "Refer notes at**",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  TOTAL: null,
 },
]

export default MTech
