const source = "http://www.nitp.ac.in/php/"
import React from "react"

const StructuralEngg = [
 {
  dept: null,
  ccmt: "CESU ",
  grp: "Core ",
  sem_elect: null,
  coursecode: null,
  url: null,
  coursetitle: <strong>Structural Engineering</strong>,
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "Core ",
  sem_elect: "1 ",
  coursecode: "CE601 ",
  url: source + "civil_Mtech/ce601.docx",
  coursetitle: "Advanced Structural Analysis",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "Core ",
  sem_elect: "1 ",
  coursecode: "CE602 ",
  url: source + "civil_Mtech/ce602.docx",
  coursetitle: "Theory of Elasticity and Plasticity",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "EL-1 ",
  sem_elect: "1 ",
  coursecode: "CE6xx ",
  coursetitle: "Elective  I ",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "EL-2 ",
  sem_elect: "1 ",
  coursecode: "CE6xx ",
  coursetitle: "Elective II ",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },

 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "EL-3 ",
  sem_elect: "1 ",
  coursecode: "CE6xx ",
  coursetitle: "Elective III/Open Elective ",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },

 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "Lab ",
  sem_elect: "1 ",
  coursecode: "CE681 ",
  coursetitle: "Advanced Civil Engineering Lab I ",
  l: "0 ",
  t: "0 ",
  p: "6 ",
  credits: "4 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "Core ",
  sem_elect: "2 ",
  coursecode: "CE603 ",
  url: source + "civil_Mtech/ce603.docx",
  coursetitle: "Advanced Design of Concrete and Steel Structures",
  l: "0 ",
  t: "0 ",
  p: "3 ",
  credits: "2 ",
 },

 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "EL-4 ",
  sem_elect: "2 ",
  coursecode: "CE6xx ",
  coursetitle: "Elective IV ",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },

 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "EL-5 ",
  sem_elect: "2 ",
  coursecode: "CE6xx ",
  coursetitle: "Elective  V ",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "EL-6 ",
  sem_elect: "2 ",
  coursecode: "CE6xx ",
  coursetitle: "Elective  VI ",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "EL-7 ",
  sem_elect: "2 ",
  coursecode: "CE6xx ",
  coursetitle: "Elective VII/Open Elective ",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },

 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "Lab ",
  sem_elect: "2 ",
  coursecode: "CE690 ",
  coursetitle: "seminar",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "Lab ",
  sem_elect: "2 ",
  coursecode: "CE686 ",
  coursetitle: "Advanced Civil Engineering Lab  II ",
  l: "0 ",
  t: "0 ",
  p: "6 ",
  credits: "4 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "Lab ",
  sem_elect: "3 ",
  coursecode: "CE691 ",
  coursetitle: "seminar and Comprehensive Viva  I ",
  l: "0 ",
  t: "0 ",
  p: "3 ",
  credits: "2 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "Lab ",
  sem_elect: "3 ",
  coursecode: "CE692 ",
  coursetitle: "Dissertation (to be continued in 4th sem",
  l: "0 ",
  t: "0 ",
  p: "12 ",
  credits: "8 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "Lab ",
  sem_elect: "4 ",
  coursecode: "CE693 ",
  coursetitle: "seminar and Comprehensive Viva II ",
  l: "0 ",
  t: "0 ",
  p: "3 ",
  credits: "2 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  grp: "Lab ",
  sem_elect: "4 ",
  coursecode: "CE694 ",
  coursetitle: "Dissertation ",
  l: "0 ",
  t: "0 ",
  p: "15 ",
  credits: "10 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x",
  coursecode: "CE604 ",
  url: source + "civil_Mtech/ce604.docx",
  coursetitle: "Advance Concrete Technology",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x",
  coursecode: "CE605 ",
  coursetitle: "Pre-Stressed Concrete Structure",
  url: source + "civil_Mtech/ce605.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x",
  coursecode: "CE606 ",
  coursetitle: "Bridge Engineering",
  url: source + "civil_Mtech/ce606.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x",
  coursecode: "CE607 ",
  coursetitle: "Theory of Plates and Shells",
  url: source + "civil_Mtech/ce607.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x",
  coursecode: "CE608 ",
  coursetitle: "Structural Stability",
  url: source + "civil_Mtech/ce608.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x",
  coursecode: "CE609 ",
  coursetitle: "Earthquake Resistant Design of Structures",
  url: source + "civil_Mtech/ce609.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x ",
  coursecode: "CE610 ",
  coursetitle: "Finite Element Method",
  url: source + "civil_Mtech/ce610.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x ",
  coursecode: "CE611 ",
  coursetitle: "Structural Dynamics",
  url: source + "civil_Mtech/ce611.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x ",
  coursecode: "CE612 ",
  coursetitle: "Construction Technology and Management",
  url: source + "civil_Mtech/ce612.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x ",
  coursecode: "CE613 ",
  coursetitle: "Mechanics of Composite Materials",
  url: source + "civil_Mtech/ce613.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x ",
  coursecode: "CE614 ",
  coursetitle: "Reliability Engineering",
  url: source + "civil_Mtech/ce614.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x ",
  coursecode: "CE615 ",
  coursetitle: "Fracture Mechanics",
  url: source + "civil_Mtech/ce615.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x ",
  coursecode: "CE616 ",
  coursetitle: "Structural Health Monitoring",
  url: source + "civil_Mtech/ce616.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x ",
  coursecode: "CE617 ",
  coursetitle: "Optimization Techniques in Civil Engineering",
  url: source + "civil_Mtech/ce617.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },

 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x ",
  coursecode: "CE618 ",
  coursetitle:
   "Fuzzy Logic and Artificial Intelligence in Civil Engineering Applications",
  url: source + "civil_Mtech/ce618.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },

 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x",
  coursecode: "CE619 ",
  coursetitle: "Computational plasticity",
  url: source + "civil_Mtech/ce619.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },

 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x ",
  coursecode: "CE620 ",
  coursetitle: "Advanced Finite Element Method",
  url: source + "civil_Mtech/ce620.docx",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
 {
  dept: "CEPG ",
  ccmt: "CESU ",
  sem_elect: "EL-x ",
  coursecode: "MA604 ",
  coursetitle: "Probability and Statistics",
  l: "3 ",
  t: "0 ",
  p: "0 ",
  credits: "3 ",
 },
]

const GeoEngg = [
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `Core `,
  sem_elect: `1 `,
  coursecode: `CE731 `,
  url: `${source}Geo/1CE731.docx`,
  coursetitle: `Advanced Foundation Engineering `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `Core `,
  sem_elect: `1 `,
  coursecode: `CE732 `,
  url: `${source}Geo/1CE732.docx`,
  coursetitle: `Geotechnical Investigations and Ground Improvement Techniques `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-1 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective I `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-2 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective II `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-3 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective III/Open Elective `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `Lab `,
  sem_elect: `1 `,
  coursecode: `CE681 `,
  url: `${source}Geo/1CE681.docx`,
  coursetitle: `Advanced Civil Engineering Lab -I `,
  l: `0 `,
  t: `0 `,
  p: `6 `,
  credits: `4 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: ``,
  sem_elect: `1`,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit </strong>,
  l: `12 `,
  t: `0 `,
  p: `6 `,
  credits: `16 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `Core `,
  sem_elect: `2 `,
  coursecode: `CE733 `,
  url: `${source}Geo/2CE733.docx`,
  coursetitle: `Rock Mechanics and Tunnel Engineering `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-3 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective IV `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-4 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective V `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-5 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  VI `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 // {
 //   "dept": `CEPG `,
 //   ccmt: `CEGE `,
 //   grp: `EL-6 `,
 //   "sem_elect": `2 `,
 //   "coursecode": `CE6xx `,
 //   "coursetitle": `Elective VI `,
 //   l: `3 `,
 //   t: `0 `,
 //   p: `0 `,
 //   credits: `3 `,
 // },

 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-7 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective VII/Open Elective `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `Lab `,
  sem_elect: `2 `,
  coursecode: `CE686 `,
  url: `${source}Geo/2CE686.docx`,
  coursetitle: `Advanced Civil Engineering Lab - II `,
  l: `0 `,
  t: `0 `,
  p: `6 `,
  credits: `4 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `Lab `,
  sem_elect: `2 `,
  coursecode: `CE690 `,
  coursetitle: `"sem_elect"inar `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: ``,
  sem_elect: `2 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,

  l: `12 `,
  t: `0 `,
  p: `9 `,
  credits: `18 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `Lab `,
  sem_elect: `3 `,
  coursecode: `CE691 `,
  coursetitle: `"sem_elect"inar and Comprehensive Viva I `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `Lab `,
  sem_elect: `3 `,
  coursecode: `CE692 `,
  coursetitle: `Dissertation (to be continued in 4th "sem_elect") `,
  l: `0 `,
  t: `0 `,
  p: `12 `,
  credits: `8 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: ``,
  sem_elect: `3 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,

  l: `0 `,
  t: `0 `,
  p: `15 `,
  credits: `10 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `Lab `,
  sem_elect: `4 `,
  coursecode: `CE693 `,
  coursetitle: `"sem_elect"inar and Comprehensive Viva II `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `Lab `,
  sem_elect: `4 `,
  coursecode: `CE694 `,
  coursetitle: `Dissertation `,
  l: `0 `,
  t: `0 `,
  p: `15 `,
  credits: `10 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: ``,
  sem_elect: `4 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,

  l: `0 `,
  t: `0 `,
  p: `18 `,
  credits: `12 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: ``,
  sem_elect: ``,
  coursecode: ``,
  coursetitle: <strong>Cumulative Credit </strong>,
  l: ``,
  t: ``,
  p: ``,
  credits: `62 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE617 `,
  url: `${source}Geo/xCE617.docx`,
  coursetitle: `Optimization Techniques in Civil Engineering `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE734 `,
  url: `${source}Geo/xCE734.docx`,
  coursetitle: `Soil Stabilization `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE735 `,
  url: `${source}Geo/xCE735.docx`,
  coursetitle: `Earth Pressure and retaining structures `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE737 `,
  url: `${source}Geo/xCE737.docx`,
  coursetitle: `Earth and Rock-fill Dams `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE738 `,
  url: `${source}Geo/xCE738.docx`,
  coursetitle: `Soil Structure Interaction `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE739 `,
  url: `${source}Geo/xCE739.docx`,
  coursetitle: `Geo-environmental Engineering `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE740 `,
  url: `${source}Geo/xCE740.docx`,
  coursetitle: `Soil Dynamics and Geotechnical Earthquake Engineering `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE741 `,
  url: `${source}Geo/xCE741.docx`,
  coursetitle: `Reinforced Earth and Geotextiles `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE742 `,
  url: `${source}Geo/xCE742.docx`,
  coursetitle: `Continuum Mechanics `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE743 `,
  url: `${source}Geo/xCE743.docx`,
  coursetitle: `Slope Stability and Earthen Dams`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEGE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `MA604 `,
  coursetitle: `Probability and Statistics `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
]

const TransPortEngineering = [
 {
  dept: null,
  ccmt: "CESU ",
  grp: "Core ",
  sem_elect: null,
  coursecode: null,
  url: null,
  coursetitle: <strong>TransPort Engineering</strong>,
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `Core `,
  sem_elect: `1 `,
  coursecode: `CE631 `,

  url: `${source}civil_Mtech/T1CE631.docx`,
  coursetitle: `Transportation Planning `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `Core `,
  sem_elect: `1 `,
  coursecode: `CE632 `,

  url: `${source}civil_Mtech/T1CE632.docx`,
  coursetitle: `Pavement Analysis and Design `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-1 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  I `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-2 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  II `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-3 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  III/Open Elective `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `Lab `,
  sem_elect: `1 `,
  coursecode: `CE681 `,
  coursetitle: `Advanced Civil Engineering Lab -I `,
  l: `0 `,
  t: `0 `,
  p: `6 `,
  credits: `4 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: ``,
  sem_elect: `1`,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,
  l: `15 `,
  t: `0 `,
  p: `6 `,
  credits: `19 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `Core `,
  sem_elect: `2 `,
  coursecode: `CE633 `,

  url: `${source}civil_Mtech/T1CE633.docx`,
  coursetitle: `Traffic Engineering and Management `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-4 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective IV  `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-5 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective V  `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-6 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective VI `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-7 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective VII/Open Elective `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `Lab `,
  sem_elect: `2 `,
  coursecode: `CE686 `,
  coursetitle: `Advanced Civil Engineering Lab - II `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `Lab `,
  sem_elect: `2 `,
  coursecode: `CE690 `,
  coursetitle: `"sem_elect"inar `,
  l: `0 `,
  t: `0 `,
  p: `6 `,
  credits: `4 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: ``,
  sem_elect: `2 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit </strong>,
  l: `15 `,
  t: `0 `,
  p: `9 `,
  credits: `21 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `Lab `,
  sem_elect: `3 `,
  coursecode: `CE691 `,
  coursetitle: `"sem_elect"inar and Comprehensive Viva - I `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `Lab `,
  sem_elect: `3 `,
  coursecode: `CE692 `,
  coursetitle: `Dissertation (to be continued in 4th "sem_elect") `,
  l: `0 `,
  t: `0 `,
  p: `12 `,
  credits: `8 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: ``,
  sem_elect: `3 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,
  l: `0 `,
  t: `0 `,
  p: `15 `,
  credits: `10 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `Lab `,
  sem_elect: `4 `,
  coursecode: `CE693 `,
  coursetitle: `"sem_elect"inar and Comprehensive Viva II `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `Lab `,
  sem_elect: `4 `,
  coursecode: `CE694 `,
  coursetitle: `Dissertation `,
  l: `0 `,
  t: `0 `,
  p: `15 `,
  credits: `10 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: ``,
  sem_elect: `4 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,
  l: `0 `,
  t: `0 `,
  p: `18 `,
  credits: `12 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: ``,
  sem_elect: ``,
  coursecode: ``,
  coursetitle: <strong>Cumulative Total Credit</strong>,
  l: ``,
  t: ``,
  p: ``,
  credits: `62 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE634 `,

  url: `${source}civil_Mtech/T1CE634.docx`,
  coursetitle: `Airport Planning and Desingn `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE635 `,

  url: `${source}civil_Mtech/T1CE635.docx`,
  coursetitle: `Highway Economics `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE636 `,

  url: `${source}civil_Mtech/T1CE636.docx`,
  coursetitle: `Railway Engineering `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE637 `,

  url: `${source}civil_Mtech/T1CE637.docx`,
  coursetitle: `Remote Sensing and GIS and their Applications `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE638 `,

  url: `${source}civil_Mtech/T1CE638.docx`,
  coursetitle: `Highway Construction Practices and Maintenance `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE639 `,

  url: `${source}civil_Mtech/T1CE639.docx`,
  coursetitle: `Multi-modal Transportation System Planning and Design `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE640 `,

  url: `${source}civil_Mtech/T1CE640.docx`,
  coursetitle: `Intelligent Transportation Systems `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE641 `,

  url: `${source}civil_Mtech/T1CE641.docx`,
  coursetitle: `Advance Highway Design `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE642 `,

  url: `${source}civil_Mtech/T1CE642.docx`,
  coursetitle: `Traffic Flow Theory `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE643 `,

  url: `${source}civil_Mtech/T1CE643.docx`,
  coursetitle: `Highway Subgrade and Foundation `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE644 `,

  url: `${source}civil_Mtech/T1CE644.docx`,
  coursetitle: `Pavement Materials `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE645 `,

  url: `${source}civil_Mtech/T1CE645.docx`,
  coursetitle: `Urban Transportation Planning `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE646 `,

  url: `${source}civil_Mtech/T1CE646.docx`,
  coursetitle: `Pavement Management System `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE647 `,

  url: `${source}civil_Mtech/T1CE647.docx`,
  coursetitle: `System Analysis and Optimization Techniques `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE648 `,

  url: `${source}civil_Mtech/T1CE648.docx`,
  coursetitle: `Environmental Impact Assessment `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `MA604 `,
  coursetitle: `Probability and Statistics  `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CETE `,
  grp: `EL-X `,
  sem_elect: ` `,
  coursecode: `CE649 `,

  url: `${source}civil_Mtech/T1CE649.docx`,
  coursetitle: `Ground Improvement Technique `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
]

const WaterRes = [
 {
  dept: null,
  ccmt: "CESU ",
  grp: "Core ",
  sem_elect: null,
  coursecode: null,
  url: null,
  coursetitle: <strong>Water Resources Engineering</strong>,
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `Core `,
  sem_elect: `1 `,
  coursecode: `CE661 `,

  url: `${source}civil_Mtech/W1CE661.docx`,
  coursetitle: `Advanced Hydraulics `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `Core `,
  sem_elect: `1 `,
  coursecode: `CE662 `,

  url: `${source}civil_Mtech/W1CE662.docx`,
  coursetitle: `Advanced Hydrology `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-1 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective I `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-2 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  II `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-3 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  III/Open Elective `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `Lab `,
  sem_elect: `1 `,
  coursecode: `CE681 `,

  url: `${source}civil_Mtech/W1CE681.docx`,
  coursetitle: `Advanced Civil Engineering Lab I `,
  l: `0 `,
  t: `0 `,
  p: `6 `,
  credits: `4 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: ``,
  sem_elect: `1 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,
  l: `15 `,
  t: `0 `,
  p: `6 `,
  credits: `19`,
 },

 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `Core `,
  sem_elect: `2 `,
  coursecode: `CE663 `,

  url: `${source}civil_Mtech/W1CE663.docx`,
  coursetitle: `Advanced Ground Water Engineering `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-4 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  IV `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-5 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective V `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-6 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective VI `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-7 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective VII/Open Elective `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `Lab `,
  sem_elect: `2 `,
  coursecode: `CE686 `,

  url: `${source}civil_Mtech/W1CE686.docx`,
  coursetitle: `Advanced Civil Engineering Lab - II `,
  l: `0 `,
  t: `0 `,
  p: `6 `,
  credits: `4 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `Lab `,
  sem_elect: `2 `,
  coursecode: `CE690 `,
  coursetitle: `"sem_elect"inar `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: ``,
  sem_elect: `2 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit </strong>,
  l: `15 `,
  t: `0 `,
  p: `9 `,
  credits: `21 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `Lab `,
  sem_elect: `3 `,
  coursecode: `CE691 `,
  coursetitle: `"sem_elect"inar and Comprehensive Viva  I `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `Lab `,
  sem_elect: `3 `,
  coursecode: `CE692 `,
  coursetitle: `Dissertation (to be continued in 4th "sem_elect") `,
  l: `0 `,
  t: `0 `,
  p: `12 `,
  credits: `8 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: ``,
  sem_elect: `3 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit </strong>,
  l: `0 `,
  t: `0 `,
  p: `15 `,
  credits: `10 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `Lab `,
  sem_elect: `4 `,
  coursecode: `CE693 `,
  coursetitle: `"sem_elect"inar and Comprehensive Viva  II `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `Lab `,
  sem_elect: `4 `,
  coursecode: `CE694 `,
  coursetitle: `Dissertation `,
  l: `0 `,
  t: `0 `,
  p: `15 `,
  credits: `10 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: ``,
  sem_elect: `4 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit </strong>,
  l: `0 `,
  t: `0 `,
  p: `18 `,
  credits: `12 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: ``,
  sem_elect: ``,
  coursecode: ``,
  coursetitle: <strong>Cumulative Total Credit </strong>,
  l: ``,
  t: ``,
  p: ``,
  credits: `62 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE664 `,

  url: `${source}civil_Mtech/W1CE664.docx`,
  coursetitle: `Water Resources System's Planning and Economic Analysis `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE665 `,

  url: `${source}civil_Mtech/W1CE665.docx`,
  coursetitle: `Optimization Techniquies `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE666 `,

  url: `${source}civil_Mtech/W1CE666.docx`,
  coursetitle: `Unsteady Flows `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE667 `,

  url: `${source}civil_Mtech/W1CE667.docx`,
  coursetitle: `River Engineering `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE668 `,

  url: `${source}civil_Mtech/W1CE668.docx`,
  coursetitle: `Reservoir Operation and Planning `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE669 `,

  url: `${source}civil_Mtech/W1CE669.docx`,
  coursetitle: `River Pollution and Control `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE670 `,

  url: `${source}civil_Mtech/W1CE670.docx`,
  coursetitle: `Remote Sensing and GIS for Water Resources `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE671 `,

  url: `${source}civil_Mtech/W1CE671.docx`,
  coursetitle: `Hydro Power Engineering `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE672 `,

  url: `${source}civil_Mtech/W1CE672.docx`,
  coursetitle: `Irrigation Water Management `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE673 `,

  url: `${source}civil_Mtech/W1CE673.docx`,
  coursetitle: `Advanced Land Drainage `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE674 `,

  url: `${source}civil_Mtech/W1CE674.docx`,
  coursetitle: `Hydrodynamics `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE675 `,

  url: `${source}civil_Mtech/W1CE675.docx`,
  coursetitle: `Floods and Droughts `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE676 `,

  url: `${source}civil_Mtech/W1CE676.docx`,
  coursetitle: `Design of Hydraulic Structures `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE677 `,

  url: `${source}civil_Mtech/W1CE677.docx`,
  coursetitle: `Contaminant Transport in Porous Media`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `CE678 `,

  url: `${source}civil_Mtech/W1CE678.docx`,
  coursetitle: `Finite element analysis`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEWR `,
  grp: `EL-x `,
  sem_elect: ` `,
  coursecode: `MA604 `,
  coursetitle: `Probability and Statistics `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
]

const EnvEngg = [
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `Core `,
  sem_elect: `1 `,
  coursecode: `CE701 `,
  url: `${source}Enviro/1CE701.docx`,
  coursetitle: `Environmental Chemistry and Microbiology `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `Core `,
  sem_elect: `1 `,
  coursecode: `CE702 `,
  url: `${source}Enviro/xCE702.docx`,
  coursetitle: `Water and Wastewater Treatment `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EL-1 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  I `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EL-2 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  II `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EL-3 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective III /Open Elective`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `Lab `,
  sem_elect: `1 `,
  coursecode: `CE681 `,
  coursetitle: `Advanced Civil Engineering Lab  I `,
  l: `0 `,
  t: `0 `,
  p: `6 `,
  credits: `4 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: ``,
  sem_elect: `1 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,
  l: `12 `,
  t: `0 `,
  p: `6 `,
  credits: `16 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `Core `,
  sem_elect: `2 `,
  coursecode: `CE703 `,
  url: `${source}Enviro/2CE703.docx`,
  coursetitle: `Air and Noise Pollution `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EL-4 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective IV `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EL-5 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  V `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EL-6 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  VI `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EL-7 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective  VII/Open Elective `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `Lab `,
  sem_elect: `2 `,
  coursecode: `CE686 `,
  coursetitle: `Advanced Civil Engineering Lab  II `,
  l: `0 `,
  t: `0 `,
  p: `6 `,
  credits: `4 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `Lab `,
  sem_elect: `2 `,
  coursecode: `CE690 `,
  coursetitle: `"sem_elect"inar `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: ``,
  sem_elect: `2 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,
  l: `15 `,
  t: `0 `,
  p: `9 `,
  credits: `21 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `Lab `,
  sem_elect: `3 `,
  coursecode: `CE691 `,
  coursetitle: `"sem_elect"inar and Comprehensive Viva  I `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `Lab `,
  sem_elect: `3 `,
  coursecode: `CE692 `,
  coursetitle: `Dissertation (to be continued in 4th "sem_elect") `,
  l: `0 `,
  t: `0 `,
  p: `12 `,
  credits: `8 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: ``,
  sem_elect: `3 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,
  l: `0 `,
  t: `0 `,
  p: `15 `,
  credits: `10 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `Lab `,
  sem_elect: `4 `,
  coursecode: `CE693 `,
  coursetitle: `"sem_elect"inar and Comprehensive Viva II `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `Lab `,
  sem_elect: `4 `,
  coursecode: `CE694 `,
  coursetitle: `Dissertation `,
  l: `0 `,
  t: `0 `,
  p: `15 `,
  credits: `10 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: ``,
  sem_elect: `4 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,
  l: `0 `,
  t: `0 `,
  p: `18 `,
  credits: `12 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: ``,
  sem_elect: ``,
  coursecode: ``,
  coursetitle: <strong>Cumulative Total Credit </strong>,
  l: ``,
  t: ``,
  p: ``,
  credits: `62 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE704 `,
  url: `${source}Enviro/xCE704.docx`,
  coursetitle: `Environmental Management `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE705 `,
  url: `${source}Enviro/xCE705.docx`,
  coursetitle: `Ecology `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE706 `,
  url: `${source}Enviro/xCE706.docx`,
  coursetitle: `Environmental Impact Assessment `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE707 `,
  url: `${source}Enviro/xCE707.docx`,
  coursetitle: `Environmental Sanitation `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE708 `,
  url: `${source}Enviro/xCE708.docx`,
  coursetitle: `Air Quality Modelling `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE709 `,
  url: `${source}Enviro/xCE709.docx`,
  coursetitle: `Advance Industrial Waste Management `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE710 `,
  url: `${source}Enviro/xCE710.docx`,
  coursetitle: `Hazardous and Nuclear Waste Management `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE711 `,
  url: `${source}Enviro/xCE711.docx`,
  coursetitle: `Chemo Dynamics `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE712 `,
  url: `${source}Enviro/xCE712.docx`,
  coursetitle: `Solid Waste Management`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE713 `,
  url: `${source}Enviro/xCE713.docx`,
  coursetitle: `Environmental Management in Construction Projects `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE714 `,
  url: `${source}Enviro/xCE714.docx`,
  coursetitle: `Advance Biological Processes and Treatment `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `CE716 `,
  url: `${source}Enviro/xCE716.docx`,
  coursetitle: `Environmental Fluid Mechanics `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CEEV `,
  grp: `EK-x `,
  sem_elect: ` `,
  coursecode: `MA604 `,
  coursetitle: `Probability and Statistics `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
]

const RiverEngg = [
 {
  dept: null,
  ccmt: "CESU ",
  grp: "Core ",
  sem_elect: null,
  coursecode: null,
  url: null,
  coursetitle: <strong>River Engineering</strong>,
  l: null,
  t: null,
  p: null,
  credits: null,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `Core `,
  sem_elect: `1 `,
  coursecode: `CE761 `,
  url: `${source}river/xCE761.docx`,
  coursetitle: `River Morphology and Hydraulics `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `Core `,
  sem_elect: `1 `,
  coursecode: `CE662 `,
  url: `${source}river/xCE761.docx`,
  coursetitle: `Advanced Hydrology  `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-1 `,
  sem_elect: `1 `,
  coursecode: `CExxx `,
  coursetitle: `Elective I `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-2 `,
  sem_elect: `1 `,
  coursecode: `CExxx `,
  coursetitle: `Elective II `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-3 `,
  sem_elect: `1 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective III/Open Elective `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `Lab `,
  sem_elect: `1 `,
  coursecode: `CE681 `,
  url: `${source}river/1CE681.docx`,
  coursetitle: `Advanced Civil Engineering Lab –Ia:  `,
  l: `0 `,
  t: `0 `,
  p: `6 `,
  credits: `4 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: ``,
  sem_elect: `1`,
  coursecode: ``,
  coursetitle: <strong>Total "sem_elect"ester Credit </strong>,
  l: `15 `,
  t: `0 `,
  p: `6 `,
  credits: `19 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `Core `,
  sem_elect: `2 `,
  coursecode: `CE762 `,
  url: `${source}river/xCE762.docx`,
  coursetitle: `River training and flood control `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-4 `,
  sem_elect: `2 `,
  coursecode: `CExxx `,
  coursetitle: `Elective IV `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-5 `,
  sem_elect: `2 `,
  coursecode: `CExxx `,
  coursetitle: `Elective  V `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-6 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective VI `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-7 `,
  sem_elect: `2 `,
  coursecode: `CE6xx `,
  coursetitle: `Elective VII/Open Elective `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `Lab `,
  sem_elect: `2 `,
  coursecode: `CE686 `,
  coursetitle: `Advanced Civil Engineering Lab- II `,
  l: `0 `,
  t: `0 `,
  p: `6 `,
  credits: `4 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `Lab `,
  sem_elect: `2 `,
  coursecode: `CE690 `,
  coursetitle: `"sem_elect"inar `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: ``,
  sem_elect: `2 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,
  l: `12 `,
  t: `0 `,
  p: `9 `,
  credits: `18 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `Lab `,
  sem_elect: `3 `,
  coursecode: `CE691 `,
  coursetitle: `"sem_elect"inar and Comprehensive Viva - I`,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `Lab `,
  sem_elect: `3 `,
  coursecode: `CE692 `,
  coursetitle: `Dissertation (to be continued in 4th "sem_elect")  `,
  l: `0 `,
  t: `0 `,
  p: `12 `,
  credits: `8 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: ``,
  sem_elect: `3 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,
  l: `0 `,
  t: `0 `,
  p: `15 `,
  credits: `10 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `Lab `,
  sem_elect: `4 `,
  coursecode: `CE693 `,
  coursetitle: `"sem_elect"inar and Comprehensive Viva II `,
  l: `0 `,
  t: `0 `,
  p: `3 `,
  credits: `2 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `Lab `,
  sem_elect: `4 `,
  coursecode: `CE694 `,
  coursetitle: `Dissertation (Final) `,
  l: `0 `,
  t: `0 `,
  p: `15 `,
  credits: `10 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: ``,
  sem_elect: `4 `,
  coursecode: ``,
  coursetitle: <strong>Total semester Credit</strong>,
  l: `0 `,
  t: `0 `,
  p: `18 `,
  credits: `12 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: ``,
  sem_elect: ``,
  coursecode: ``,
  coursetitle: <strong>Cumulative Total Credit </strong>,
  l: ``,
  t: ``,
  p: ``,
  credits: `62 `,
 },

 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE661 `,
  url: `${source}river/1CE661.docx`,
  coursetitle: `Advanced Hydraulics`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE663 `,
  url: `${source}river/1CE663.docx`,
  coursetitle: `Advanced Groundwater Engineering `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE668 `,
  url: `${source}river/1CE668.docx`,
  coursetitle: `Reservoir Operation and Planning `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE669 `,
  url: `${source}river/xCE669.docx`,
  coursetitle: `River Pollution and control`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE670 `,
  url: `${source}river/1CE670.docx`,
  coursetitle: `Remote Sensing and GIS for Water Resources  `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE671 `,
  url: `${source}river/1CE671.docx`,
  coursetitle: `Hydro Power Engineering  `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE672 `,
  url: `${source}river/1CE672.docx`,
  coursetitle: `Irrigation Water Management `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE675 `,
  url: `${source}river/1CE675.docx`,
  coursetitle: `Flood and Drought Management `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE676 `,
  url: `${source}river/1CE676.docx`,
  coursetitle: `Design of Hydraulic Structures  `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE764 `,
  url: `${source}river/xCE764.docx`,
  coursetitle: `Environmental Impact Assessment of River Valley Projects `,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE765 `,
  url: `${source}river/xCE765.docx`,
  coursetitle: `Climate Change Implications on River Flows`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE766 `,
  url: `${source}river/xCE764.docx`,
  coursetitle: `Computational Hydraulics`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
 {
  dept: `CEPG `,
  ccmt: `CERE `,
  grp: `EL-x `,
  sem_elect: `  `,
  coursecode: `CE767 `,
  url: `${source}river/1CE767.docx`,
  coursetitle: `River Ecology and Environmental Flows`,
  l: `3 `,
  t: `0 `,
  p: `0 `,
  credits: `3 `,
 },
]

const Mtech = [
 StructuralEngg,
 TransPortEngineering,
 RiverEngg,
 EnvEngg,
 GeoEngg,
 WaterRes,
]
export default Mtech
