import React from "react"

const Cemtech = [
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Core ",
    sem: "1 ",
    course_code: "CE601 ",
    url: "./civil_Mtech/ce601.docx",
    course_title: "Advanced Structural Analysis",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Core ",
    sem: "1 ",
    course_code: "CE602 ",
    url: "./civil_Mtech/ce602.docx",
    course_title: "Theory of Elasticity and Plasticity",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-1 ",
    sem: "1 ",
    course_code: "CE6xx ",
    course_title: "Elective  I ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-2 ",
    sem: "1 ",
    course_code: "CE6xx ",
    course_title: "Elective II ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-3 ",
    sem: "1 ",
    course_code: "CE6xx ",
    course_title: "Elective III/Open Elective ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "1 ",
    course_code: "CE681 ",
    course_title: "Advanced Civil Engineering Lab I ",
    l: "0 ",
    t: "0 ",
    p: "6 ",
    credits: "4 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Core ",
    sem: "2 ",
    course_code: "CE603 ",
    url: "./civil_Mtech/ce603.docx",
    course_title: "Advanced Design of Concrete and Steel Structures",
    l: "0 ",
    t: "0 ",
    p: "3 ",
    credits: "2 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-4 ",
    sem: "2 ",
    course_code: "CE6xx ",
    course_title: "Elective IV ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-5 ",
    sem: "2 ",
    course_code: "CE6xx ",
    course_title: "Elective  V ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-6 ",
    sem: "2 ",
    course_code: "CE6xx ",
    course_title: "Elective  VI ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-7 ",
    sem: "2 ",
    course_code: "CE6xx ",
    course_title: "Elective VII/Open Elective ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "2 ",
    course_code: "CE690 ",
    course_title: "Seminar ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "2 ",
    course_code: "CE686 ",
    course_title: "Advanced Civil Engineering Lab  II ",
    l: "0 ",
    t: "0 ",
    p: "6 ",
    credits: "4 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "3 ",
    course_code: "CE691 ",
    course_title: "Seminar and Comprehensive Viva  I ",
    l: "0 ",
    t: "0 ",
    p: "3 ",
    credits: "2 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "3 ",
    course_code: "CE692 ",
    course_title: "Dissertation (to be continued in 4th Sem) ",
    l: "0 ",
    t: "0 ",
    p: "12 ",
    credits: "8 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "4 ",
    course_code: "CE693 ",
    course_title: "Seminar and Comprehensive Viva II ",
    l: "0 ",
    t: "0 ",
    p: "3 ",
    credits: "2 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "4 ",
    course_code: "CE694 ",
    course_title: "Dissertation ",
    l: "0 ",
    t: "0 ",
    p: "15 ",
    credits: "10 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE604 ",
    url: "./civil_Mtech/ce604.docx",
    course_title: "Advance Concrete Technology",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE605 ",
    course_title: "Pre-Stressed Concrete Structure",
    url: "./civil_Mtech/ce605.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE606 ",
    course_title: "Bridge Engineering",
    url: "./civil_Mtech/ce606.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE607 ",
    course_title: "Theory of Plates and Shells",
    url: "./civil_Mtech/ce607.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE608 ",
    course_title: "Structural Stability",
    url: "./civil_Mtech/ce608.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE609 ",
    course_title: "Earthquake Resistant Design of Structures",
    url: "./civil_Mtech/ce609.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE610 ",
    course_title: "Finite Element Method",
    url: "./civil_Mtech/ce610.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE611 ",
    course_title: "Structural Dynamics",
    url: "./civil_Mtech/ce611.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE612 ",
    course_title: "Construction Technology and Management",
    url: "./civil_Mtech/ce612.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE613 ",
    course_title: "Mechanics of Composite Materials",
    url: "./civil_Mtech/ce613.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE614 ",
    course_title: "Reliability Engineering",
    url: "./civil_Mtech/ce614.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE615 ",
    course_title: "Fracture Mechanics",
    url: "./civil_Mtech/ce615.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE616 ",
    course_title: "Structural Health Monitoring",
    url: "./civil_Mtech/ce616.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE617 ",
    course_title: "Optimization Techniques in Civil Engineering",
    url: "./civil_Mtech/ce617.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE618 ",
    course_title:
      "Fuzzy Logic and Artificial Intelligence in Civil Engineering Applications",
    url: "./civil_Mtech/ce618.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE619 ",
    course_title: "Computational plasticity",
    url: "./civil_Mtech/ce619.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE620 ",
    course_title: "Advanced Finite Element Method",
    url: "./civil_Mtech/ce620.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "MA604 ",
    course_title: "Probability and Statistics",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
]

export default Cemtech
