const source = "http://www.nitp.ac.in/php/"

export const StructuralEngg = [
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Core ",
    sem: "1 ",
    course_code: "CE601 ",
    url: source + "civil_Mtech/ce601.docx",
    course_title: "Advanced Structural Analysis",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Core ",
    sem: "1 ",
    course_code: "CE602 ",
    url: source + "civil_Mtech/ce602.docx",
    course_title: "Theory of Elasticity and Plasticity",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-1 ",
    sem: "1 ",
    course_code: "CE6xx ",
    course_title: "Elective  I ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-2 ",
    sem: "1 ",
    course_code: "CE6xx ",
    course_title: "Elective II ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-3 ",
    sem: "1 ",
    course_code: "CE6xx ",
    course_title: "Elective III/Open Elective ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "1 ",
    course_code: "CE681 ",
    course_title: "Advanced Civil Engineering Lab I ",
    l: "0 ",
    t: "0 ",
    p: "6 ",
    credits: "4 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Core ",
    sem: "2 ",
    course_code: "CE603 ",
    url: source + "civil_Mtech/ce603.docx",
    course_title: "Advanced Design of Concrete and Steel Structures",
    l: "0 ",
    t: "0 ",
    p: "3 ",
    credits: "2 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-4 ",
    sem: "2 ",
    course_code: "CE6xx ",
    course_title: "Elective IV ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-5 ",
    sem: "2 ",
    course_code: "CE6xx ",
    course_title: "Elective  V ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-6 ",
    sem: "2 ",
    course_code: "CE6xx ",
    course_title: "Elective  VI ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "EL-7 ",
    sem: "2 ",
    course_code: "CE6xx ",
    course_title: "Elective VII/Open Elective ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "2 ",
    course_code: "CE690 ",
    course_title: "Seminar ",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "2 ",
    course_code: "CE686 ",
    course_title: "Advanced Civil Engineering Lab  II ",
    l: "0 ",
    t: "0 ",
    p: "6 ",
    credits: "4 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "3 ",
    course_code: "CE691 ",
    course_title: "Seminar and Comprehensive Viva  I ",
    l: "0 ",
    t: "0 ",
    p: "3 ",
    credits: "2 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "3 ",
    course_code: "CE692 ",
    course_title: "Dissertation (to be continued in 4th Sem) ",
    l: "0 ",
    t: "0 ",
    p: "12 ",
    credits: "8 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "4 ",
    course_code: "CE693 ",
    course_title: "Seminar and Comprehensive Viva II ",
    l: "0 ",
    t: "0 ",
    p: "3 ",
    credits: "2 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    grp: "Lab ",
    sem: "4 ",
    course_code: "CE694 ",
    course_title: "Dissertation ",
    l: "0 ",
    t: "0 ",
    p: "15 ",
    credits: "10 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE604 ",
    url: source + "civil_Mtech/ce604.docx",
    course_title: "Advance Concrete Technology",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE605 ",
    course_title: "Pre-Stressed Concrete Structure",
    url: source + "civil_Mtech/ce605.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE606 ",
    course_title: "Bridge Engineering",
    url: source + "civil_Mtech/ce606.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE607 ",
    course_title: "Theory of Plates and Shells",
    url: source + "civil_Mtech/ce607.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE608 ",
    course_title: "Structural Stability",
    url: source + "civil_Mtech/ce608.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE609 ",
    course_title: "Earthquake Resistant Design of Structures",
    url: source + "civil_Mtech/ce609.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE610 ",
    course_title: "Finite Element Method",
    url: source + "civil_Mtech/ce610.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE611 ",
    course_title: "Structural Dynamics",
    url: source + "civil_Mtech/ce611.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE612 ",
    course_title: "Construction Technology and Management",
    url: source + "civil_Mtech/ce612.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE613 ",
    course_title: "Mechanics of Composite Materials",
    url: source + "civil_Mtech/ce613.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE614 ",
    course_title: "Reliability Engineering",
    url: source + "civil_Mtech/ce614.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE615 ",
    course_title: "Fracture Mechanics",
    url: source + "civil_Mtech/ce615.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE616 ",
    course_title: "Structural Health Monitoring",
    url: source + "civil_Mtech/ce616.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE617 ",
    course_title: "Optimization Techniques in Civil Engineering",
    url: source + "civil_Mtech/ce617.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE618 ",
    course_title:
      "Fuzzy Logic and Artificial Intelligence in Civil Engineering Applications",
    url: source + "civil_Mtech/ce618.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x",
    course_code: "CE619 ",
    course_title: "Computational plasticity",
    url: source + "civil_Mtech/ce619.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },

  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "CE620 ",
    course_title: "Advanced Finite Element Method",
    url: source + "civil_Mtech/ce620.docx",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
  {
    prog: "CEPG ",
    ccmt: "CESU ",
    sem: "EL-x ",
    course_code: "MA604 ",
    course_title: "Probability and Statistics",
    l: "3 ",
    t: "0 ",
    p: "0 ",
    credits: "3 ",
  },
]

export const GeoEngg = [
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `Core `,
    sem: `1 `,
    course_code: `CE731 `,
    url: `${source}Geo/1CE731.docx`,
    course_title: `Advanced Foundation Engineering `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `Core `,
    sem: `1 `,
    course_code: `CE732 `,
    url: `${source}Geo/1CE732.docx`,
    course_title: `Geotechnical Investigations and Ground Improvement Techniques `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-1 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective I `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-2 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective II `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-3 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective III/Open Elective `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `Lab `,
    sem: `1 `,
    course_code: `CE681 `,
    url: `${source}Geo/1CE681.docx`,
    course_title: `Advanced Civil Engineering Lab -I `,
    l: `0 `,
    t: `0 `,
    p: `6 `,
    credits: `4 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: ``,
    sem: `1`,
    course_code: ``,
    course_title: <strong>Total Semester Credit </strong>,
    l: `12 `,
    t: `0 `,
    p: `6 `,
    credits: `16 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `Core `,
    sem: `2 `,
    course_code: `CE733 `,
    url: `${source}Geo/2CE733.docx`,
    course_title: `Rock Mechanics and Tunnel Engineering `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-3 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective IV `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-4 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective V `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-5 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective  VI `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  // {
  //   prog: `CEPG `,
  //   ccmt: `CEGE `,
  //   grp: `EL-6 `,
  //   sem: `2 `,
  //   course_code: `CE6xx `,
  //   course_title: `Elective VI `,
  //   l: `3 `,
  //   t: `0 `,
  //   p: `0 `,
  //   credits: `3 `,
  // },

  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-7 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective VII/Open Elective `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `Lab `,
    sem: `2 `,
    course_code: `CE686 `,
    url: `${source}Geo/2CE686.docx`,
    course_title: `Advanced Civil Engineering Lab - II `,
    l: `0 `,
    t: `0 `,
    p: `6 `,
    credits: `4 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `Lab `,
    sem: `2 `,
    course_code: `CE690 `,
    course_title: `Seminar `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: ``,
    sem: `2 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,

    l: `12 `,
    t: `0 `,
    p: `9 `,
    credits: `18 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `Lab `,
    sem: `3 `,
    course_code: `CE691 `,
    course_title: `Seminar and Comprehensive Viva I `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `Lab `,
    sem: `3 `,
    course_code: `CE692 `,
    course_title: `Dissertation (to be continued in 4th Sem) `,
    l: `0 `,
    t: `0 `,
    p: `12 `,
    credits: `8 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: ``,
    sem: `3 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,

    l: `0 `,
    t: `0 `,
    p: `15 `,
    credits: `10 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `Lab `,
    sem: `4 `,
    course_code: `CE693 `,
    course_title: `Seminar and Comprehensive Viva II `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `Lab `,
    sem: `4 `,
    course_code: `CE694 `,
    course_title: `Dissertation `,
    l: `0 `,
    t: `0 `,
    p: `15 `,
    credits: `10 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: ``,
    sem: `4 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,

    l: `0 `,
    t: `0 `,
    p: `18 `,
    credits: `12 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: ``,
    sem: ``,
    course_code: ``,
    course_title: <strong>Cumulative Credit </strong>,
    l: ``,
    t: ``,
    p: ``,
    credits: `62 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE617 `,
    url: `${source}Geo/xCE617.docx`,
    course_title: `Optimization Techniques in Civil Engineering `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE734 `,
    url: `${source}Geo/xCE734.docx`,
    course_title: `Soil Stabilization `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE735 `,
    url: `${source}Geo/xCE735.docx`,
    course_title: `Earth Pressure and retaining structures `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE737 `,
    url: `${source}Geo/xCE737.docx`,
    course_title: `Earth and Rock-fill Dams `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE738 `,
    url: `${source}Geo/xCE738.docx`,
    course_title: `Soil Structure Interaction `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE739 `,
    url: `${source}Geo/xCE739.docx`,
    course_title: `Geo-environmental Engineering `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE740 `,
    url: `${source}Geo/xCE740.docx`,
    course_title: `Soil Dynamics and Geotechnical Earthquake Engineering `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE741 `,
    url: `${source}Geo/xCE741.docx`,
    course_title: `Reinforced Earth and Geotextiles `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE742 `,
    url: `${source}Geo/xCE742.docx`,
    course_title: `Continuum Mechanics `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE743 `,
    url: `${source}Geo/xCE743.docx`,
    course_title: `Slope Stability and Earthen Dams`,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEGE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `MA604 `,
    course_title: `Probability and Statistics `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
]

export const TransPortEngineering = [
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `Core `,
    sem: `1 `,
    course_code: `CE631 `,

    url: `${source}civil_Mtech/T1CE631.docx`,
    course_title: `Transportation Planning `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `Core `,
    sem: `1 `,
    course_code: `CE632 `,

    url: `${source}civil_Mtech/T1CE632.docx`,
    course_title: `Pavement Analysis and Design `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-1 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective  I `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-2 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective  II `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-3 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective  III/Open Elective `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `Lab `,
    sem: `1 `,
    course_code: `CE681 `,
    course_title: `Advanced Civil Engineering Lab -I `,
    l: `0 `,
    t: `0 `,
    p: `6 `,
    credits: `4 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: ``,
    sem: `1`,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,
    l: `15 `,
    t: `0 `,
    p: `6 `,
    credits: `19 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `Core `,
    sem: `2 `,
    course_code: `CE633 `,

    url: `${source}civil_Mtech/T1CE633.docx`,
    course_title: `Traffic Engineering and Management `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-4 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective IV  `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-5 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective V  `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-6 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective VI `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-7 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective VII/Open Elective `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `Lab `,
    sem: `2 `,
    course_code: `CE686 `,
    course_title: `Advanced Civil Engineering Lab - II `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `Lab `,
    sem: `2 `,
    course_code: `CE690 `,
    course_title: `Seminar `,
    l: `0 `,
    t: `0 `,
    p: `6 `,
    credits: `4 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: ``,
    sem: `2 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit </strong>,
    l: `15 `,
    t: `0 `,
    p: `9 `,
    credits: `21 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `Lab `,
    sem: `3 `,
    course_code: `CE691 `,
    course_title: `Seminar and Comprehensive Viva - I `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `Lab `,
    sem: `3 `,
    course_code: `CE692 `,
    course_title: `Dissertation (to be continued in 4th Sem) `,
    l: `0 `,
    t: `0 `,
    p: `12 `,
    credits: `8 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: ``,
    sem: `3 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,
    l: `0 `,
    t: `0 `,
    p: `15 `,
    credits: `10 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `Lab `,
    sem: `4 `,
    course_code: `CE693 `,
    course_title: `Seminar and Comprehensive Viva II `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `Lab `,
    sem: `4 `,
    course_code: `CE694 `,
    course_title: `Dissertation `,
    l: `0 `,
    t: `0 `,
    p: `15 `,
    credits: `10 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: ``,
    sem: `4 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,
    l: `0 `,
    t: `0 `,
    p: `18 `,
    credits: `12 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: ``,
    sem: ``,
    course_code: ``,
    course_title: <strong>Cumulative Total Credit</strong>,
    l: ``,
    t: ``,
    p: ``,
    credits: `62 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE634 `,

    url: `${source}civil_Mtech/T1CE634.docx`,
    course_title: `Airport Planning and Desingn `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE635 `,

    url: `${source}civil_Mtech/T1CE635.docx`,
    course_title: `Highway Economics `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE636 `,

    url: `${source}civil_Mtech/T1CE636.docx`,
    course_title: `Railway Engineering `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE637 `,

    url: `${source}civil_Mtech/T1CE637.docx`,
    course_title: `Remote Sensing and GIS and their Applications `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE638 `,

    url: `${source}civil_Mtech/T1CE638.docx`,
    course_title: `Highway Construction Practices and Maintenance `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE639 `,

    url: `${source}civil_Mtech/T1CE639.docx`,
    course_title: `Multi-modal Transportation System Planning and Design `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE640 `,

    url: `${source}civil_Mtech/T1CE640.docx`,
    course_title: `Intelligent Transportation Systems `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE641 `,

    url: `${source}civil_Mtech/T1CE641.docx`,
    course_title: `Advance Highway Design `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE642 `,

    url: `${source}civil_Mtech/T1CE642.docx`,
    course_title: `Traffic Flow Theory `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE643 `,

    url: `${source}civil_Mtech/T1CE643.docx`,
    course_title: `Highway Subgrade and Foundation `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE644 `,

    url: `${source}civil_Mtech/T1CE644.docx`,
    course_title: `Pavement Materials `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE645 `,

    url: `${source}civil_Mtech/T1CE645.docx`,
    course_title: `Urban Transportation Planning `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE646 `,

    url: `${source}civil_Mtech/T1CE646.docx`,
    course_title: `Pavement Management System `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE647 `,

    url: `${source}civil_Mtech/T1CE647.docx`,
    course_title: `System Analysis and Optimization Techniques `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE648 `,

    url: `${source}civil_Mtech/T1CE648.docx`,
    course_title: `Environmental Impact Assessment `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `MA604 `,
    course_title: `Probability and Statistics  `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CETE `,
    grp: `EL-X `,
    sem: ` `,
    course_code: `CE649 `,

    url: `${source}civil_Mtech/T1CE649.docx`,
    course_title: `Ground Improvement Technique `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
]

export const WaterRes = [
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `Core `,
    sem: `1 `,
    course_code: `CE661 `,

    url: `${source}civil_Mtech/W1CE661.docx`,
    course_title: `Advanced Hydraulics `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `Core `,
    sem: `1 `,
    course_code: `CE662 `,

    url: `${source}civil_Mtech/W1CE662.docx`,
    course_title: `Advanced Hydrology `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-1 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective I `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-2 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective  II `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-3 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective  III/Open Elective `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `Lab `,
    sem: `1 `,
    course_code: `CE681 `,

    url: `${source}civil_Mtech/W1CE681.docx`,
    course_title: `Advanced Civil Engineering Lab I `,
    l: `0 `,
    t: `0 `,
    p: `6 `,
    credits: `4 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: ``,
    sem: `1 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,
    l: `15 `,
    t: `0 `,
    p: `6 `,
    credits: `19`,
  },

  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `Core `,
    sem: `2 `,
    course_code: `CE663 `,

    url: `${source}civil_Mtech/W1CE663.docx`,
    course_title: `Advanced Ground Water Engineering `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-4 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective  IV `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-5 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective V `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-6 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective VI `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-7 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective VII/Open Elective `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `Lab `,
    sem: `2 `,
    course_code: `CE686 `,

    url: `${source}civil_Mtech/W1CE686.docx`,
    course_title: `Advanced Civil Engineering Lab - II `,
    l: `0 `,
    t: `0 `,
    p: `6 `,
    credits: `4 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `Lab `,
    sem: `2 `,
    course_code: `CE690 `,
    course_title: `Seminar `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: ``,
    sem: `2 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit </strong>,
    l: `15 `,
    t: `0 `,
    p: `9 `,
    credits: `21 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `Lab `,
    sem: `3 `,
    course_code: `CE691 `,
    course_title: `Seminar and Comprehensive Viva  I `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `Lab `,
    sem: `3 `,
    course_code: `CE692 `,
    course_title: `Dissertation (to be continued in 4th Sem) `,
    l: `0 `,
    t: `0 `,
    p: `12 `,
    credits: `8 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: ``,
    sem: `3 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit </strong>,
    l: `0 `,
    t: `0 `,
    p: `15 `,
    credits: `10 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `Lab `,
    sem: `4 `,
    course_code: `CE693 `,
    course_title: `Seminar and Comprehensive Viva  II `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `Lab `,
    sem: `4 `,
    course_code: `CE694 `,
    course_title: `Dissertation `,
    l: `0 `,
    t: `0 `,
    p: `15 `,
    credits: `10 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: ``,
    sem: `4 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit </strong>,
    l: `0 `,
    t: `0 `,
    p: `18 `,
    credits: `12 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: ``,
    sem: ``,
    course_code: ``,
    course_title: <strong>Cumulative Total Credit </strong>,
    l: ``,
    t: ``,
    p: ``,
    credits: `62 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE664 `,

    url: `${source}civil_Mtech/W1CE664.docx`,
    course_title: `Water Resources System's Planning and Economic Analysis `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE665 `,

    url: `${source}civil_Mtech/W1CE665.docx`,
    course_title: `Optimization Techniquies `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE666 `,

    url: `${source}civil_Mtech/W1CE666.docx`,
    course_title: `Unsteady Flows `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE667 `,

    url: `${source}civil_Mtech/W1CE667.docx`,
    course_title: `River Engineering `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE668 `,

    url: `${source}civil_Mtech/W1CE668.docx`,
    course_title: `Reservoir Operation and Planning `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE669 `,

    url: `${source}civil_Mtech/W1CE669.docx`,
    course_title: `River Pollution and Control `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE670 `,

    url: `${source}civil_Mtech/W1CE670.docx`,
    course_title: `Remote Sensing and GIS for Water Resources `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE671 `,

    url: `${source}civil_Mtech/W1CE671.docx`,
    course_title: `Hydro Power Engineering `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE672 `,

    url: `${source}civil_Mtech/W1CE672.docx`,
    course_title: `Irrigation Water Management `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE673 `,

    url: `${source}civil_Mtech/W1CE673.docx`,
    course_title: `Advanced Land Drainage `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE674 `,

    url: `${source}civil_Mtech/W1CE674.docx`,
    course_title: `Hydrodynamics `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE675 `,

    url: `${source}civil_Mtech/W1CE675.docx`,
    course_title: `Floods and Droughts `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE676 `,

    url: `${source}civil_Mtech/W1CE676.docx`,
    course_title: `Design of Hydraulic Structures `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE677 `,

    url: `${source}civil_Mtech/W1CE677.docx`,
    course_title: `Contaminant Transport in Porous Media`,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `CE678 `,

    url: `${source}civil_Mtech/W1CE678.docx`,
    course_title: `Finite element analysis`,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEWR `,
    grp: `EL-x `,
    sem: ` `,
    course_code: `MA604 `,
    course_title: `Probability and Statistics `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
]

export const EnvEngg = [
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `Core `,
    sem: `1 `,
    course_code: `CE701 `,
    url: `${source}Enviro/1CE701.docx`,
    course_title: `Environmental Chemistry and Microbiology `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `Core `,
    sem: `1 `,
    course_code: `CE702 `,
    url: `${source}Enviro/xCE702.docx`,
    course_title: `Water and Wastewater Treatment `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EL-1 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective  I `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EL-2 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective  II `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EL-3 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective III /Open Elective`,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `Lab `,
    sem: `1 `,
    course_code: `CE681 `,
    course_title: `Advanced Civil Engineering Lab  I `,
    l: `0 `,
    t: `0 `,
    p: `6 `,
    credits: `4 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: ``,
    sem: `1 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,
    l: `12 `,
    t: `0 `,
    p: `6 `,
    credits: `16 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `Core `,
    sem: `2 `,
    course_code: `CE703 `,
    url: `${source}Enviro/2CE703.docx`,
    course_title: `Air and Noise Pollution `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EL-4 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective IV `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EL-5 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective  V `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EL-6 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective  VI `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EL-7 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective  VII/Open Elective `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `Lab `,
    sem: `2 `,
    course_code: `CE686 `,
    course_title: `Advanced Civil Engineering Lab  II `,
    l: `0 `,
    t: `0 `,
    p: `6 `,
    credits: `4 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `Lab `,
    sem: `2 `,
    course_code: `CE690 `,
    course_title: `Seminar `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: ``,
    sem: `2 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,
    l: `15 `,
    t: `0 `,
    p: `9 `,
    credits: `21 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `Lab `,
    sem: `3 `,
    course_code: `CE691 `,
    course_title: `Seminar and Comprehensive Viva  I `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `Lab `,
    sem: `3 `,
    course_code: `CE692 `,
    course_title: `Dissertation (to be continued in 4th Sem) `,
    l: `0 `,
    t: `0 `,
    p: `12 `,
    credits: `8 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: ``,
    sem: `3 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,
    l: `0 `,
    t: `0 `,
    p: `15 `,
    credits: `10 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `Lab `,
    sem: `4 `,
    course_code: `CE693 `,
    course_title: `Seminar and Comprehensive Viva II `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `Lab `,
    sem: `4 `,
    course_code: `CE694 `,
    course_title: `Dissertation `,
    l: `0 `,
    t: `0 `,
    p: `15 `,
    credits: `10 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: ``,
    sem: `4 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,
    l: `0 `,
    t: `0 `,
    p: `18 `,
    credits: `12 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: ``,
    sem: ``,
    course_code: ``,
    course_title: <strong>Cumulative Total Credit </strong>,
    l: ``,
    t: ``,
    p: ``,
    credits: `62 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE704 `,
    url: `${source}Enviro/xCE704.docx`,
    course_title: `Environmental Management `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE705 `,
    url: `${source}Enviro/xCE705.docx`,
    course_title: `Ecology `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE706 `,
    url: `${source}Enviro/xCE706.docx`,
    course_title: `Environmental Impact Assessment `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE707 `,
    url: `${source}Enviro/xCE707.docx`,
    course_title: `Environmental Sanitation `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE708 `,
    url: `${source}Enviro/xCE708.docx`,
    course_title: `Air Quality Modelling `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE709 `,
    url: `${source}Enviro/xCE709.docx`,
    course_title: `Advance Industrial Waste Management `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE710 `,
    url: `${source}Enviro/xCE710.docx`,
    course_title: `Hazardous and Nuclear Waste Management `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE711 `,
    url: `${source}Enviro/xCE711.docx`,
    course_title: `Chemo Dynamics `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE712 `,
    url: `${source}Enviro/xCE712.docx`,
    course_title: `Solid Waste Management`,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE713 `,
    url: `${source}Enviro/xCE713.docx`,
    course_title: `Environmental Management in Construction Projects `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE714 `,
    url: `${source}Enviro/xCE714.docx`,
    course_title: `Advance Biological Processes and Treatment `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `CE716 `,
    url: `${source}Enviro/xCE716.docx`,
    course_title: `Environmental Fluid Mechanics `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CEEV `,
    grp: `EK-x `,
    sem: ` `,
    course_code: `MA604 `,
    course_title: `Probability and Statistics `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
]

export const RiverEngg = [
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `Core `,
    sem: `1 `,
    course_code: `CE761 `,
    url: `${source}river/xCE761.docx`,
    course_title: `River Morphology and Hydraulics `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `Core `,
    sem: `1 `,
    course_code: `CE662 `,
    url: `${source}river/xCE761.docx`,
    course_title: `Advanced Hydrology  `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-1 `,
    sem: `1 `,
    course_code: `CExxx `,
    course_title: `Elective I `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-2 `,
    sem: `1 `,
    course_code: `CExxx `,
    course_title: `Elective II `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-3 `,
    sem: `1 `,
    course_code: `CE6xx `,
    course_title: `Elective III/Open Elective `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `Lab `,
    sem: `1 `,
    course_code: `CE681 `,
    url: `${source}river/1CE681.docx`,
    course_title: `Advanced Civil Engineering Lab –Ia:  `,
    l: `0 `,
    t: `0 `,
    p: `6 `,
    credits: `4 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: ``,
    sem: `1`,
    course_code: ``,
    course_title: <strong>Total Semester Credit </strong>,
    l: `15 `,
    t: `0 `,
    p: `6 `,
    credits: `19 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `Core `,
    sem: `2 `,
    course_code: `CE762 `,
    url: `${source}river/xCE762.docx`,
    course_title: `River training and flood control `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-4 `,
    sem: `2 `,
    course_code: `CExxx `,
    course_title: `Elective IV `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-5 `,
    sem: `2 `,
    course_code: `CExxx `,
    course_title: `Elective  V `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-6 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective VI `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-7 `,
    sem: `2 `,
    course_code: `CE6xx `,
    course_title: `Elective VII/Open Elective `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `Lab `,
    sem: `2 `,
    course_code: `CE686 `,
    course_title: `Advanced Civil Engineering Lab- II `,
    l: `0 `,
    t: `0 `,
    p: `6 `,
    credits: `4 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `Lab `,
    sem: `2 `,
    course_code: `CE690 `,
    course_title: `Seminar `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: ``,
    sem: `2 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,
    l: `12 `,
    t: `0 `,
    p: `9 `,
    credits: `18 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `Lab `,
    sem: `3 `,
    course_code: `CE691 `,
    course_title: `Seminar and Comprehensive Viva - I`,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `Lab `,
    sem: `3 `,
    course_code: `CE692 `,
    course_title: `Dissertation (to be continued in 4th Sem)  `,
    l: `0 `,
    t: `0 `,
    p: `12 `,
    credits: `8 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: ``,
    sem: `3 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,
    l: `0 `,
    t: `0 `,
    p: `15 `,
    credits: `10 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `Lab `,
    sem: `4 `,
    course_code: `CE693 `,
    course_title: `Seminar and Comprehensive Viva II `,
    l: `0 `,
    t: `0 `,
    p: `3 `,
    credits: `2 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `Lab `,
    sem: `4 `,
    course_code: `CE694 `,
    course_title: `Dissertation (Final) `,
    l: `0 `,
    t: `0 `,
    p: `15 `,
    credits: `10 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: ``,
    sem: `4 `,
    course_code: ``,
    course_title: <strong>Total Semester Credit</strong>,
    l: `0 `,
    t: `0 `,
    p: `18 `,
    credits: `12 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: ``,
    sem: ``,
    course_code: ``,
    course_title: <strong>Cumulative Total Credit </strong>,
    l: ``,
    t: ``,
    p: ``,
    credits: `62 `,
  },

  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE661 `,
    url: `${source}river/1CE661.docx`,
    course_title: `Advanced Hydraulics`,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE663 `,
    url: `${source}river/1CE663.docx`,
    course_title: `Advanced Groundwater Engineering `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE668 `,
    url: `${source}river/1CE668.docx`,
    course_title: `Reservoir Operation and Planning `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE669 `,
    url: `${source}river/xCE669.docx`,
    course_title: `River Pollution and control`,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE670 `,
    url: `${source}river/1CE670.docx`,
    course_title: `Remote Sensing and GIS for Water Resources  `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE671 `,
    url: `${source}river/1CE671.docx`,
    course_title: `Hydro Power Engineering  `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE672 `,
    url: `${source}river/1CE672.docx`,
    course_title: `Irrigation Water Management `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE675 `,
    url: `${source}river/1CE675.docx`,
    course_title: `Flood and Drought Management `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE676 `,
    url: `${source}river/1CE676.docx`,
    course_title: `Design of Hydraulic Structures  `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE764 `,
    url: `${source}river/xCE764.docx`,
    course_title: `Environmental Impact Assessment of River Valley Projects `,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE765 `,
    url: `${source}river/xCE765.docx`,
    course_title: `Climate Change Implications on River Flows`,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE766 `,
    url: `${source}river/xCE764.docx`,
    course_title: `Computational Hydraulics`,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
  {
    prog: `CEPG `,
    ccmt: `CERE `,
    grp: `EL-x `,
    sem: `  `,
    course_code: `CE767 `,
    url: `${source}river/1CE767.docx`,
    course_title: `River Ecology and Environmental Flows`,
    l: `3 `,
    t: `0 `,
    p: `0 `,
    credits: `3 `,
  },
]
