import React from "react"

const Cephd = [
 {
  type: "Mandatory Course",
  coursecode: "xxxx",
  coursetitle: "Research Methodology",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
 },
 {
  type: "Mandatory Course",
  coursecode: "xxxx",
  coursetitle: "Seminar and Technical report Writing",
  l: "0",
  t: "0",
  p: "3",
  credits: "2",
 },
 {
  type: "Mandatory Course",
  coursecode: "xxxx",
  coursetitle: "Comprehensive Viva & Presentation ",
  l: "0",
  t: "0",
  p: "2",
  credits: "1",
 },
 {
  type: "Departmental Course",
  coursecode: "xxxx",
  coursetitle: "Course - I",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
 },
 {
  type: "Departmental Course",
  coursecode: "xxxx",
  coursetitle: "Course - II",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
 },
 {
  type: "Departmental Course",
  coursecode: "xxxx",
  coursetitle: "Lab Course",
  l: "0",
  t: "0",
  p: "6",
  credits: "4",
 },
 {
  type: "Departmental Course",
  coursecode: "xxxx",
  coursetitle: "Course - III",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
 },
 {
  type: "Departmental Course",
  coursecode: "xxxx",
  coursetitle: "Course - IV",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
 },
 {
  type: "Departmental Course",
  coursecode: "xxxx",
  coursetitle: "Course - V",
  l: "3",
  t: "0",
  p: "0",
  credits: "3",
 },
]
export default Cephd
