import React from "react"

const CivilBTechCourse = [
 {
  dept: `CEUG`,
  sem_elective: `1`,
  coursecode: `1HS101`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/English Literature.docx`,
  coursetitle: `English Literature`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `1`,
  coursecode: `MA101`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/Engineering Mathematics I.docx`,
  coursetitle: `Engineering Mathematics I`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `1`,
  coursecode: `1PH101`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ph101.docx`,
  coursetitle: `Engineering Physics TH `,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `1`,
  coursecode: `1PH102`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/Engineering Physics Lab.docx`,
  coursetitle: `Engineering Physics Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `1`,
  coursecode: `1CS101`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/Introduction to Computing.docx`,
  coursetitle: `Introduction to Computing`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `1`,
  coursecode: `1CS102`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/Computing Lab.docx`,
  coursetitle: `Computing Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `1`,
  coursecode: `1EE101`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ee101.docx`,
  coursetitle: `Elements of Electrical Engg`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `1`,
  coursecode: `1EE102`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ee102.docx`,
  coursetitle: `Elements of Electrical Engg Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `1`,
  coursecode: `1ME102`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/Workshop Practice.docx`,
  coursetitle: `Workshop Practice`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  dept: `CEUG`,
  sem_elective: `2`,
  coursecode: `2HS102`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/hs102.docx`,
  coursetitle: `Communication Skill Development & Technical Writing`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `2`,
  coursecode: `2MA102`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ma102.docx`,
  coursetitle: `Engineering Mathematics �II`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `2`,
  coursecode: `2CH101`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/Ch101.docx`,
  coursetitle: `Chemical Science`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `2`,
  coursecode: `2CH102`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/Ch102.docx`,
  coursetitle: `Chemical Science Lab`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `2`,
  coursecode: `2HS105`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/hs105.docx`,
  coursetitle: `Science, Society & Ethical Values`,
  l: `1`,
  t: `1`,
  p: `0`,
  credits: `2`,
 },
 {
  dept: `CEUG`,
  sem_elective: `2`,
  coursecode: `2CE101`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ce101.docx`,
  coursetitle: `Engineering Mechanics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `2`,
  coursecode: `2EC101`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ec101.docx`,
  coursetitle: `Elements of Electronics Engg`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `2`,
  coursecode: `2EC102`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ec102.docx`,
  coursetitle: `Elements of Electronics Engg Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `2`,
  coursecode: `2EC101`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/Engineering Graphics.docx`,
  coursetitle: `Engineering Graphics`,
  l: `1`,
  t: `0`,
  p: `3`,
  credits: `2`,
 },

 {
  dept: `CEUG`,
  sem_elective: `3`,
  coursecode: `CE105`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/3ce105.docx`,
  coursetitle: `Fluid Mechanics & Hydraulics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `3`,
  coursecode: `CE106`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/3ce106.docx`,
  coursetitle: `Fluid Mechanics & Hydraulics lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `3`,
  coursecode: `CE107`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/3ce105.docx`,
  coursetitle: `Mechanics of Solids`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `3`,
  coursecode: `CE108`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/3ce105.docx`,
  coursetitle: `Surveying`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `3`,
  coursecode: `CE109`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/3ce105.docx`,
  coursetitle: `Surveying Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `3`,
  coursecode: `CH104`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/3ce105.docx`,
  coursetitle: `Green Technology (Environmental Science)`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `3`,
  coursecode: `MA104`,
  url: `#`,
  coursetitle: `Tools of Applied Mathematics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `3`,
  coursecode: `PH104`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ph103.docx`,
  coursetitle: `Materials Science & Technology - 1`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `4`,
  coursecode: `CE110`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/4ce110.docx`,
  coursetitle: `Design of Concrete Structures`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `4`,
  coursecode: `CE111`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/4ce111.docx`,
  coursetitle: `Cement Concrete Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `4`,
  coursecode: `CE112`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/4ce112.docx`,
  coursetitle: `Geotechnical Engineering -I`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `4`,
  coursecode: `CE113`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/4ce113.docx`,
  coursetitle: `Geotechnical Engineering - I Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `4`,
  coursecode: `CE114`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/4ce114.docx`,
  coursetitle: `Environmental Engineering - I`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `4`,
  coursecode: `CH105A`,
  coursetitle: `Bio Science`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `4`,
  coursecode: `MA108`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ma108.docx`,
  coursetitle: `Numerical Methods for Engineers`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `4`,
  coursecode: `GE105`,
  url: `#`,
  coursetitle: `EAA - I NSS`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `-`,
 },

 {
  dept: `CEUG`,
  sem_elective: `5`,
  coursecode: `CE116`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/5ce116.docx`,
  coursetitle: `Design of steel structures`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `5`,
  coursecode: `CE117`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/5ce117.docx`,
  coursetitle: `Design of steel structures lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `5`,
  coursecode: `CE118`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/5ce118.docx`,
  coursetitle: `Geotechnical Engineering - II`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `5`,
  coursecode: `CE119`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/5ce119.docx`,
  coursetitle: `Material Testing Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `5`,
  coursecode: `CE121`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/5ce121.docx`,
  coursetitle: `Transportation Engineering -I`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `5`,
  coursecode: `CE122`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/5ce122.docx`,
  coursetitle: `Transportation Engineering –I Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `5`,
  coursecode: `CE1xx`,
  url: `#`,
  coursetitle: `Departmental Elective - I`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `5`,
  coursecode: `xx1xx`,
  url: `#`,
  coursetitle: `Engineering/Open- I (Elective)`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `6`,
  coursecode: `CE123`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/6ce125.docx`,
  coursetitle: `Hydrology and Open channel Flow`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `6`,
  coursecode: `CE124`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/6ce126.docx`,
  coursetitle: `Hydrology and OCF Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `6`,
  coursecode: `CE125`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/6ce128.docx`,
  coursetitle: `Environmental Engg-II`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },

 {
  dept: `CEUG`,
  sem_elective: `6`,
  coursecode: `CE126`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/6ce129.docx`,
  coursetitle: `Environmental Engg-II Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  dept: `CEUG`,
  sem_elective: `6`,
  coursecode: `CE127`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/6ce127.docx`,
  coursetitle: `Transportation Engg -II`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  dept: `CEUG`,
  sem_elective: `6`,
  coursecode: `CE191`,
  url: `#`,
  coursetitle: `Minor Project-I`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  dept: `CEUG`,
  sem_elective: `6`,
  coursecode: `CE1xx`,
  url: `#`,
  coursetitle: `Departmental Elective - II`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `6`,
  coursecode: `CE1xx`,
  url: `#`,
  coursetitle: `Engineering/Open- II (Elective)`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `6`,
  coursecode: `GE103`,
  url: `#`,
  coursetitle: `Industrial Interaction & Soft Skill Development`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `-`,
 },

 {
  dept: `CEUG`,
  sem_elective: `6`,
  coursecode: `GE106`,
  url: `#`,
  coursetitle: `EAA - II NSS`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `-`,
 },

 {
  dept: `CEUG`,
  sem_elective: `7`,
  coursecode: `CE1xx`,
  coursetitle: `Departmental Elective - III`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `7`,
  coursecode: `CE1xx`,
  coursetitle: `Departmental Elective - IV`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `7`,
  coursecode: `xx1xx`,
  coursetitle: `Engineering/Open -III/ HSS/ Science/(Elective)`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `7`,
  coursecode: `xx1xx`,
  coursetitle: `Engineering/Open -IV/HSS/ Science/(Elective)`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `7`,
  coursecode: `CE193`,
  coursetitle: `Minor Project-II`,
  l: `0`,
  t: `0`,
  p: `6`,
  credits: `2`,
 },
 {
  dept: `CEUG`,
  sem_elective: `7`,
  coursecode: `CE192`,
  coursetitle: `Industrial Training (4 to 6 weeks after 6th Sem)`,
  l: ``,
  t: ``,
  p: ``,
  credits: `1`,
 },
 {
  dept: `CEUG`,
  sem_elective: `7`,
  coursecode: `CE194`,
  coursetitle: `General Seminar`,
  l: `0`,
  t: `0`,
  p: `6`,
  credits: `2`,
 },

 {
  dept: `CEUG`,
  sem_elective: `8`,
  coursecode: `CE195`,
  coursetitle: `Major Project`,
  l: ``,
  t: ``,
  p: ``,
  credits: `20`,
 },
 {
  dept: `CEUG`,
  sem_elective: `8`,
  coursecode: `CE196`,
  coursetitle: `Comprehensive Viva`,
  l: ``,
  t: ``,
  p: ``,
  credits: `2`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE141`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ce145.docx`,
  coursetitle: `Advanced Design of Steel Structures`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE142`,
  url: `#`,
  coursetitle: `Prestressed Concrete Design`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE144`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/5ce141.docx`,
  coursetitle: `Design of Dams`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 145`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/8ce170.docx`,
  coursetitle: `Disaster Management and Mitigation`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 146`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/7ce159.docx`,
  coursetitle: `Finite Element Method `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE147`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/5ce148.docx`,
  coursetitle: `Computer Aided Design`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE148`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/5ce143.docx`,
  coursetitle: `Water and Land Management`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE149`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/6ce147.docx`,
  coursetitle: `Air Pollution Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE150`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/6ce152.docx`,
  coursetitle: `Traffic engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE151`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/6ce146.docx`,
  coursetitle: `Advanced Soil Mechanics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 153`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/8ce175.docx`,
  coursetitle: `Structural Dynamics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE154`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ce151.docx`,
  coursetitle: `River Hydraulics and Sediment Transport`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE155`,
  coursetitle: `Civil Engineering Drawing Using Auto CAD`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 156`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/8ce171.docx`,
  coursetitle: `Ground Water Engineering `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 157`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/7ce158.docx`,
  coursetitle: `Airport Planning and Design`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE158`,
  coursetitle: `Design of Plate and Shell`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 159`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/8ce170.docx`,
  coursetitle: `Industrial Waste Treatment`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 160`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/8ce177.docx`,
  coursetitle: `Water Resources Planning and Management `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 161`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/8ce170.docx`,
  coursetitle: `Soil Dynamics `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 162`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/8ce176.docx`,
  coursetitle: `System Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE163`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/6ce153.docx`,
  coursetitle: `Water Power Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 164`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/8ce168.docx`,
  coursetitle: `Bridge Engineering `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 165`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/ce160.docx`,
  coursetitle: `Floods and Droughts`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 166`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/7ce163.docx`,
  coursetitle: `Solid Waste Management `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 167`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/7ce155.docx`,
  coursetitle: `Advanced Foundation Engineering`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 168`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/7ce164.docx`,
  coursetitle: `Transportation Systems and Planning`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE169`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/6ce150.docx`,
  coursetitle: `Land Drainage`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE170`,
  coursetitle: `Building Science`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 171`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/7ce162.docx`,
  coursetitle: `Mechanics of Composite Materials `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 172`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/7ce157.docx`,
  coursetitle: `Advanced surveying `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 173`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/7ce161.docx`,
  coursetitle: `Irrigation Engineering and Hydraulic structure`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE 174`,
  url: `${process.env.GATSBY_BASE_URL}civil/syllabus/8ce170.docx`,
  coursetitle: `Rock Mechanics `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE175`,
  coursetitle: `Earthquake Resistant Structures`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE182`,
  coursetitle: `Enviormental Impact Assesments`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  dept: `CEUG`,
  sem_elective: `EL `,
  coursecode: `CE183`,
  coursetitle: `Structural Analysis`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
]

export default CivilBTechCourse
