const MtechPhy = [
 {
  deptt: "Physics",
  sem_elect: "NST",
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "1",
  coursecode: "PH601",
  coursetitle: "APPLIED SOLID STATE PHYSICS",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "1",
  coursecode: "PH602",
  coursetitle: "INTRODUCTION TO NANO TECHNOLOGY",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "1",
  coursecode: "PH603",
  coursetitle: "INTRODUCTION TO NANO PHOTONIC & PLASTICS",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "1",
  coursecode: "PH603",
  coursetitle: "SEMICONDUCTOR DEVICES AND IC TECHNOLOGY",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "1",
  coursecode: "PH604",
  coursetitle: "NANO MECHANICS & MICRO MECHANICS FOR MEMS TECHNOLOGY",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "1",
  coursecode: "PH605",
  coursetitle: "NANO MATERIAL SYNTHESIS & CHARACTERISTIC LAB",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "1",
  coursecode: "PH6XX",
  coursetitle: "OPEN ELECTIVE -I",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
  Total: 22,
 },
 {
  deptt: "Physics",
  sem_elect: "NST Semester-II",
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "2",
  coursecode: "PH610",
  coursetitle: "MICRO & NANO CHARECTERIZATION TECHNIQUES",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "2",
  coursecode: "PH612",
  coursetitle: "ADVANCED MEMS PACKING",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "2",
  coursecode: "PH611",
  coursetitle: "MATERIAL SYNTHESIS QUANTUM DOTS TO BULK CRYASTALS",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "2",
  coursecode: "PHxx",
  coursetitle: "Elective-I",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "2",
  coursecode: "xxPG",
  coursetitle: "Elective-II",
  l: 3,
  t: 0,
  p: 0,
  credits: 3,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "2",
  coursecode: "HS6XX",
  coursetitle: "ETHICAL VALUES & KNOWLEDGE TRANSFER",
  l: 0,
  t: 0,
  p: 6,
  credits: 4,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "2",
  coursecode: "PH615",
  coursetitle: "DEVICE FABRICATION LAB MODULES",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "2",
  coursecode: "PH616",
  coursetitle: "MODULATING LAB",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
  Total: 21,
 },
 {
  deptt: "Physics",
  sem_elect: "COMPUTATIONAL MATHEMATICS Semester-III",
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "3",
  coursecode: "xxPG",
  coursetitle: "Seminar & Comprehensive Viva",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "3",
  coursecode: "xxPG",
  coursetitle: "Dissertation",
  l: 0,
  t: 0,
  p: 12,
  credits: 8,
  Total: 10,
 },
 {
  deptt: "Physics",
  sem_elect: "COMPUTATIONAL MATHEMATICS ) Semester-IV",
  coursecode: "",
  coursetitle: "",
  l: null,
  t: null,
  p: null,
  credits: null,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "3",
  coursecode: "xxPG",
  coursetitle: "Seminar & Comprehensive Viva",
  l: 0,
  t: 0,
  p: 3,
  credits: 2,
  Total: null,
 },
 {
  deptt: "Physics",
  sem_elect: "3",
  coursecode: "xxPG",
  coursetitle: "Dissertation",
  l: 0,
  t: 0,
  p: 15,
  credits: 10,
  Total: 12,
 },
]

export default MtechPhy
