import React from "react"

const PhyCourseStructure = [
  {
    sem_elect: `1`,
    course_code: `1HS101`,
    coursetitle: `English Literature`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `1`,
    course_code: `MA101`,
    coursetitle: `Engineering Mathematics � I`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `1`,
    course_code: `1PH101`,
    coursetitle: `Engineering Physics TH `,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `1`,
    course_code: `1PH102`,
    coursetitle: `Engineering Physics Lab`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `1`,
    course_code: `1CS101`,
    coursetitle: `Introduction to Computing`,
    l: `2`,
    t: `1`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `1`,
    course_code: `1CS102`,
    coursetitle: `Computing Lab`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `1`,
    course_code: `1EE101`,
    coursetitle: `Elements of Electrical Engg`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `1`,
    course_code: `1EE102`,
    coursetitle: `Elements of Electrical Engg Lab`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `1`,
    course_code: `1ME102`,
    coursetitle: `Workshop Practice`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: ` Semester Total`,
    course_code: `-`,
    coursetitle: `-`,
    l: `-`,
    t: `-`,
    p: `-`,
    credits: `22`,
  },
  {
    sem_elect: `2`,
    course_code: `2HS102`,
    coursetitle: `CoCreditsunication Skill Development & Technical Writing`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `2`,
    course_code: `2MA102`,
    coursetitle: `Engineering Mathematics �II`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `2`,
    course_code: `2CH101`,
    coursetitle: `Chemical Science`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `2`,
    course_code: `2CH102`,
    coursetitle: `Chemical Science Lab`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `1`,
  },
  {
    sem_elect: `2`,
    course_code: `2HS105`,
    coursetitle: `Science, Society & Ethical Values`,
    l: `1`,
    t: `1`,
    p: `0`,
    credits: `2`,
  },
  {
    sem_elect: `2`,
    course_code: `2CE101`,
    coursetitle: `Engineering Mechanics`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `2`,
    course_code: `2EC101`,
    coursetitle: `Elements of Electronics Engg`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `2`,
    course_code: `2EC102`,
    coursetitle: `Elements of Electronics Engg Lab`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `2`,
    course_code: `2EC101`,
    coursetitle: `Engineering Graphics`,
    l: `1`,
    t: `0`,
    p: `3`,
    credits: `2`,
  },
  {
    sem_elect: ` Semester Total`,
    course_code: `-`,
    coursetitle: `-`,
    l: `-`,
    t: `-`,
    p: `-`,
    credits: `23`,
  },
  {
    sem_elect: `3`,
    course_code: `3MA111`,
    coursetitle: `Complex Variable and Partial Diffrentiation Equation:Mathematics-III`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `3`,
    course_code: `CH106`,
    coursetitle: `Physical Chemistry I:Physical Properties`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `3`,
    course_code: `3CH107`,
    coursetitle: `Physical Chemistry Lab I`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `3`,
    course_code: `PH104`,
    coursetitle: `Mechanics,Waves & Oscillation ,Continum Mechanics`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `3`,
    course_code: `3PH105`,
    coursetitle: `Computational Physics-I`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `3`,
    course_code: `3PH106`,
    coursetitle: `Computational Physics LAB-I`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `3`,
    course_code: `3PH107`,
    coursetitle: `Fundamentals of Bio-Science`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `3`,
    course_code: `3PH108`,
    coursetitle: `Physics Lab-II`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },

  {
    sem_elect: ` Semester Total`,
    course_code: `-`,
    coursetitle: `-`,
    l: `-`,
    t: `-`,
    p: `-`,
    credits: `20`,
  },
  {
    sem_elect: `4`,
    course_code: `4MA115`,
    coursetitle: `Numerical Technique,Statistical Methods: Mathematics -IV`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },

  {
    sem_elect: `4`,
    course_code: `4MA116`,
    coursetitle: `Mathematics- IV Computing LAB`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `4`,
    course_code: `4CH104`,
    coursetitle: `Green Technology(Environmental Science)`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `4`,
    course_code: `4PH164`,
    coursetitle: `Electricity & Magnetism`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `4`,
    course_code: `4CH110`,
    coursetitle: `Quantum Mechanism-I`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `4`,
    course_code: `4PH111`,
    coursetitle: `Thermodynamics`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `4`,
    course_code: `4PH114`,
    coursetitle: `Advanced Physics Lab-II`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },

  {
    sem_elect: ` Semester Total`,
    course_code: `-`,
    coursetitle: `-`,
    l: `-`,
    t: `-`,
    p: `-`,
    credits: `20`,
  },
  {
    sem_elect: `5`,
    course_code: `5PH115`,
    coursetitle: `Chemical Mechanics`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `5`,
    course_code: `5PH116`,
    coursetitle: `Quantum Mechanics-II`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `5`,
    course_code: `5PH117`,
    coursetitle: `Mthematical Methods In Physics-I`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `5`,
    course_code: `5PH118`,
    coursetitle: `Material Science `,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `5`,
    course_code: `5DD1Course_code`,
    coursetitle: `Open Elective`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `5`,
    course_code: `5PH120`,
    coursetitle: `Advanced Physics Lab-II`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },

  {
    sem_elect: ` Semester Total`,
    course_code: `-`,
    coursetitle: `-`,
    l: `-`,
    t: `-`,
    p: `-`,
    credits: `19`,
  },
  {
    sem_elect: `6`,
    course_code: `6PH121`,
    coursetitle: `Stastical Mathematics`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `6`,
    course_code: `6PH122`,
    coursetitle: `Mathematical Methods Physics II`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `6`,
    course_code: `6PH123`,
    coursetitle: `Modern Optics`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `6`,
    course_code: `6PH124`,
    coursetitle: `Electronics`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `6`,
    course_code: `6PH125`,
    coursetitle: `Condesed Matter Physics`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `6`,
    course_code: `6CH126`,
    coursetitle: `Advanced Physics Lab-III`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `6`,
    course_code: `6PH128`,
    coursetitle: `Physics Lab IV(Electronics)`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `6`,
    course_code: `6GE103`,
    coursetitle: `Industrial Interaction and Soft Skill Development`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `0`,
  },

  {
    sem_elect: ` Semester Total`,
    course_code: `-`,
    coursetitle: `-`,
    l: `-`,
    t: `-`,
    p: `-`,
    credits: `19`,
  },
  {
    sem_elect: `7`,
    course_code: `7PH131`,
    coursetitle: `Computational Physics -II`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `7`,
    course_code: `7PH132`,
    coursetitle: `Computational Physics Lab -II`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `7`,
    course_code: `7PH133`,
    coursetitle: `Nuclear Physics`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `7`,
    course_code: `7PH134`,
    coursetitle: `Atomic & Molecular Spectroscopy`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `7`,
    course_code: `7PH135`,
    coursetitle: `Electrodynamics`,
    l: `3`,
    t: `1`,
    p: `0`,
    credits: `4`,
  },
  {
    sem_elect: `7`,
    course_code: `7PH1Course_code1Course_code`,
    coursetitle: `Elective-I`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `7`,
    course_code: `7PH38`,
    coursetitle: `Advanced Physics Lab- V`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `7`,
    course_code: `7MA190`,
    coursetitle: `Industrial Training(4 to 6 weeks after 6th Sem)`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },

  {
    sem_elect: ` Semester Total`,
    course_code: `-`,
    coursetitle: `-`,
    l: `-`,
    t: `-`,
    p: `-`,
    credits: `19`,
  },
  {
    sem_elect: `8`,
    course_code: `8PH141`,
    coursetitle: `Particle Physics`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `8`,
    course_code: `8PH142`,
    coursetitle: `Modern Analytical Techniques`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `8`,
    course_code: `8PH143`,
    coursetitle: `Material Synthesis`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `8`,
    course_code: `8PH144`,
    coursetitle: `Material Synthesis Lab`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `8`,
    course_code: `8PH146`,
    coursetitle: `Modelling & Simulation Lab`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `8`,
    course_code: `PH190`,
    coursetitle: `Seminar and Comprehensive Viva-I`,
    l: `0`,
    t: `0`,
    p: `3`,
    credits: `1`,
  },
  {
    sem_elect: `8`,
    course_code: `8PH149`,
    coursetitle: `Advanced Physics Lab-VI`,
    l: `0`,
    t: `0`,
    p: `6`,
    credits: `2`,
  },

  {
    sem_elect: `8`,
    course_code: `8PH190`,
    coursetitle: `Minor Project`,
    l: `0`,
    t: `0`,
    p: `15`,
    credits: `5`,
  },
  {
    sem_elect: ` Semester Total`,
    course_code: `-`,
    coursetitle: `-`,
    l: `-`,
    t: `-`,
    p: `-`,
    credits: `20`,
  },
  {
    sem_elect: `9`,
    course_code: `9PH191`,
    coursetitle: `Seminar and Comprehensive Viva-Ii`,
    l: `0`,
    t: `0`,
    p: `6`,
    credits: `2`,
  },

  {
    sem_elect: `9`,
    course_code: `9PH192`,
    coursetitle: `Thesis(To be contd...)`,
    l: `0`,
    t: `0`,
    p: `15`,
    credits: `5`,
  },

  {
    sem_elect: ` Semester Total`,
    course_code: `-`,
    coursetitle: `-`,
    l: `-`,
    t: `-`,
    p: `-`,
    credits: `19`,
  },
  {
    sem_elect: `10`,
    course_code: `10PH193`,
    coursetitle: `Seminar and Comprehensive viva-III`,
    l: `0`,
    t: `0`,
    p: `6`,
    credits: `2`,
  },
  {
    sem_elect: `10`,
    course_code: `10PH194`,
    coursetitle: `Thesis`,
    l: `0`,
    t: `0`,
    p: `54`,
    credits: `18`,
  },

  {
    sem_elect: ` Semester Total`,
    course_code: `-`,
    coursetitle: `-`,
    l: `-`,
    t: `-`,
    p: `-`,
    credits: `20`,
  },

  {
    sem_elect: ` Grand Total`,
    course_code: `-`,
    coursetitle: `-`,
    l: `-`,
    t: `-`,
    p: `-`,
    credits: `200`,
  },
  {
    sem_elect: `EL `,
    course_code: `PH151`,
    coursetitle: `Smart Material`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `EL `,
    course_code: `PH152`,
    coursetitle: `Nano Technology`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `EL `,
    course_code: `PH153`,
    coursetitle: `Synthesis & Characteristic of Functional Material`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `EL `,
    course_code: `PH154`,
    coursetitle: `Material Characteristic Techniques`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `EL `,
    course_code: `PH155`,
    coursetitle: `Ion Beam Patterning & Nano-bio Technology `,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `EL `,
    course_code: `PH156`,
    coursetitle: `Quatum Information Computation & Cryptography `,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
  {
    sem_elect: `EL `,
    course_code: `PH157`,
    coursetitle: `Physics of the Universe`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },

  {
    sem_elect: `EL `,
    course_code: `PH158 `,
    coursetitle: `General Relativity and Black Hole Physics `,
    l: `3`,
    t: `0 `,
    p: `0 `,
    credits: `3`,
  },

  {
    sem_elect: `EL `,
    course_code: `PH159`,
    coursetitle: `Quantum field Theory and its Applications `,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },

  {
    sem_elect: `EL `,
    course_code: `PH160`,
    coursetitle: `Advanced Statistical Mechanics `,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },

  {
    sem_elect: `EL `,
    course_code: `PH161`,
    coursetitle: `Membrane Separations: Principles ,Design & Application`,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },

  {
    sem_elect: `EL `,
    course_code: `PH162`,
    coursetitle: `Electrochemical energy conversion and storage `,
    l: `3`,
    t: `0`,
    p: `0`,
    credits: `3`,
  },
]
export default PhyCourseStructure
