import React from "react"

const PhyCourseStructure = [
 {
  deptt: "Physics",
  sem_elect: `1`,
  coursecode: `1HS101`,
  coursetitle: `English Literature`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `1`,
  coursecode: `MA101`,
  coursetitle: `Engineering Mathematics � I`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `1`,
  coursecode: `1PH101`,
  coursetitle: `Engineering Physics TH `,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `1`,
  coursecode: `1PH102`,
  coursetitle: `Engineering Physics Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `1`,
  coursecode: `1CS101`,
  coursetitle: `Introduction to Computing`,
  l: `2`,
  t: `1`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `1`,
  coursecode: `1CS102`,
  coursetitle: `Computing Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `1`,
  coursecode: `1EE101`,
  coursetitle: `Elements of Electrical Engg`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `1`,
  coursecode: `1EE102`,
  coursetitle: `Elements of Electrical Engg Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `1`,
  coursecode: `1ME102`,
  coursetitle: `Workshop Practice`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: ` Semester Total`,
  coursecode: `-`,
  coursetitle: `-`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `22`,
 },
 {
  deptt: "Physics",
  sem_elect: `2`,
  coursecode: `2HS102`,
  coursetitle: `CoCreditsunication Skill Development & Technical Writing`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `2`,
  coursecode: `2MA102`,
  coursetitle: `Engineering Mathematics �II`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `2`,
  coursecode: `2CH101`,
  coursetitle: `Chemical Science`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `2`,
  coursecode: `2CH102`,
  coursetitle: `Chemical Science Lab`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `2`,
  coursecode: `2HS105`,
  coursetitle: `Science, Society & Ethical Values`,
  l: `1`,
  t: `1`,
  p: `0`,
  credits: `2`,
 },
 {
  deptt: "Physics",
  sem_elect: `2`,
  coursecode: `2CE101`,
  coursetitle: `Engineering Mechanics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `2`,
  coursecode: `2EC101`,
  coursetitle: `Elements of Electronics Engg`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `2`,
  coursecode: `2EC102`,
  coursetitle: `Elements of Electronics Engg Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `2`,
  coursecode: `2EC101`,
  coursetitle: `Engineering Graphics`,
  l: `1`,
  t: `0`,
  p: `3`,
  credits: `2`,
 },
 {
  deptt: "Physics",
  sem_elect: ` Semester Total`,
  coursecode: `-`,
  coursetitle: `-`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `23`,
 },
 {
  deptt: "Physics",
  sem_elect: `3`,
  coursecode: `3MA111`,
  coursetitle: `Complex Variable and Partial Diffrentiation Equation:Mathematics-III`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `3`,
  coursecode: `CH106`,
  coursetitle: `Physical Chemistry I:Physical Properties`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `3`,
  coursecode: `3CH107`,
  coursetitle: `Physical Chemistry Lab I`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `3`,
  coursecode: `PH104`,
  coursetitle: `Mechanics,Waves & Oscillation ,Continum Mechanics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `3`,
  coursecode: `3PH105`,
  coursetitle: `Computational Physics-I`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `3`,
  coursecode: `3PH106`,
  coursetitle: `Computational Physics LAB-I`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `3`,
  coursecode: `3PH107`,
  coursetitle: `Fundamentals of Bio-Science`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `3`,
  coursecode: `3PH108`,
  coursetitle: `Physics Lab-II`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  deptt: "Physics",
  sem_elect: ` Semester Total`,
  coursecode: `-`,
  coursetitle: `-`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `20`,
 },
 {
  deptt: "Physics",
  sem_elect: `4`,
  coursecode: `4MA115`,
  coursetitle: `Numerical Technique,Statistical Methods: Mathematics -IV`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  deptt: "Physics",
  sem_elect: `4`,
  coursecode: `4MA116`,
  coursetitle: `Mathematics- IV Computing LAB`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `4`,
  coursecode: `4CH104`,
  coursetitle: `Green Technology(Environmental Science)`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `4`,
  coursecode: `4PH164`,
  coursetitle: `Electricity & Magnetism`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `4`,
  coursecode: `4CH110`,
  coursetitle: `Quantum Mechanism-I`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `4`,
  coursecode: `4PH111`,
  coursetitle: `Thermodynamics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `4`,
  coursecode: `4PH114`,
  coursetitle: `Advanced Physics Lab-II`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  deptt: "Physics",
  sem_elect: ` Semester Total`,
  coursecode: `-`,
  coursetitle: `-`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `20`,
 },
 {
  deptt: "Physics",
  sem_elect: `5`,
  coursecode: `5PH115`,
  coursetitle: `Chemical Mechanics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `5`,
  coursecode: `5PH116`,
  coursetitle: `Quantum Mechanics-II`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `5`,
  coursecode: `5PH117`,
  coursetitle: `Mthematical Methods In Physics-I`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `5`,
  coursecode: `5PH118`,
  coursetitle: `Material Science `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `5`,
  coursecode: `5DD1Coursecode`,
  coursetitle: `Open Elective`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `5`,
  coursecode: `5PH120`,
  coursetitle: `Advanced Physics Lab-II`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  deptt: "Physics",
  sem_elect: ` Semester Total`,
  coursecode: `-`,
  coursetitle: `-`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `19`,
 },
 {
  deptt: "Physics",
  sem_elect: `6`,
  coursecode: `6PH121`,
  coursetitle: `Stastical Mathematics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `6`,
  coursecode: `6PH122`,
  coursetitle: `Mathematical Methods Physics II`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `6`,
  coursecode: `6PH123`,
  coursetitle: `Modern Optics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `6`,
  coursecode: `6PH124`,
  coursetitle: `Electronics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `6`,
  coursecode: `6PH125`,
  coursetitle: `Condesed Matter Physics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `6`,
  coursecode: `6CH126`,
  coursetitle: `Advanced Physics Lab-III`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `6`,
  coursecode: `6PH128`,
  coursetitle: `Physics Lab IV(Electronics)`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `6`,
  coursecode: `6GE103`,
  coursetitle: `Industrial Interaction and Soft Skill Development`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `0`,
 },

 {
  deptt: "Physics",
  sem_elect: ` Semester Total`,
  coursecode: `-`,
  coursetitle: `-`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `19`,
 },
 {
  deptt: "Physics",
  sem_elect: `7`,
  coursecode: `7PH131`,
  coursetitle: `Computational Physics -II`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `7`,
  coursecode: `7PH132`,
  coursetitle: `Computational Physics Lab -II`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `7`,
  coursecode: `7PH133`,
  coursetitle: `Nuclear Physics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `7`,
  coursecode: `7PH134`,
  coursetitle: `Atomic & Molecular Spectroscopy`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `7`,
  coursecode: `7PH135`,
  coursetitle: `Electrodynamics`,
  l: `3`,
  t: `1`,
  p: `0`,
  credits: `4`,
 },
 {
  deptt: "Physics",
  sem_elect: `7`,
  coursecode: `7PH1Coursecode1Coursecode`,
  coursetitle: `Elective-I`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `7`,
  coursecode: `7PH38`,
  coursetitle: `Advanced Physics Lab- V`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `7`,
  coursecode: `7MA190`,
  coursetitle: `Industrial Training(4 to 6 weeks after 6th Sem)`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },

 {
  deptt: "Physics",
  sem_elect: ` Semester Total`,
  coursecode: `-`,
  coursetitle: `-`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `19`,
 },
 {
  deptt: "Physics",
  sem_elect: `8`,
  coursecode: `8PH141`,
  coursetitle: `Particle Physics`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `8`,
  coursecode: `8PH142`,
  coursetitle: `Modern Analytical Techniques`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `8`,
  coursecode: `8PH143`,
  coursetitle: `Material Synthesis`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `8`,
  coursecode: `8PH144`,
  coursetitle: `Material Synthesis Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `8`,
  coursecode: `8PH146`,
  coursetitle: `Modelling & Simulation Lab`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `8`,
  coursecode: `PH190`,
  coursetitle: `Seminar and Comprehensive Viva-I`,
  l: `0`,
  t: `0`,
  p: `3`,
  credits: `1`,
 },
 {
  deptt: "Physics",
  sem_elect: `8`,
  coursecode: `8PH149`,
  coursetitle: `Advanced Physics Lab-VI`,
  l: `0`,
  t: `0`,
  p: `6`,
  credits: `2`,
 },

 {
  deptt: "Physics",
  sem_elect: `8`,
  coursecode: `8PH190`,
  coursetitle: `Minor Project`,
  l: `0`,
  t: `0`,
  p: `15`,
  credits: `5`,
 },
 {
  deptt: "Physics",
  sem_elect: ` Semester Total`,
  coursecode: `-`,
  coursetitle: `-`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `20`,
 },
 {
  deptt: "Physics",
  sem_elect: `9`,
  coursecode: `9PH191`,
  coursetitle: `Seminar and Comprehensive Viva-Ii`,
  l: `0`,
  t: `0`,
  p: `6`,
  credits: `2`,
 },

 {
  deptt: "Physics",
  sem_elect: `9`,
  coursecode: `9PH192`,
  coursetitle: `Thesis(To be contd...)`,
  l: `0`,
  t: `0`,
  p: `15`,
  credits: `5`,
 },

 {
  deptt: "Physics",
  sem_elect: ` Semester Total`,
  coursecode: `-`,
  coursetitle: `-`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `19`,
 },
 {
  deptt: "Physics",
  sem_elect: `10`,
  coursecode: `10PH193`,
  coursetitle: `Seminar and Comprehensive viva-III`,
  l: `0`,
  t: `0`,
  p: `6`,
  credits: `2`,
 },
 {
  deptt: "Physics",
  sem_elect: `10`,
  coursecode: `10PH194`,
  coursetitle: `Thesis`,
  l: `0`,
  t: `0`,
  p: `54`,
  credits: `18`,
 },

 {
  deptt: "Physics",
  sem_elect: ` Semester Total`,
  coursecode: `-`,
  coursetitle: `-`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `20`,
 },

 {
  deptt: "Physics",
  sem_elect: ` Grand Total`,
  coursecode: `-`,
  coursetitle: `-`,
  l: `-`,
  t: `-`,
  p: `-`,
  credits: `200`,
 },
 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH151`,
  coursetitle: `Smart Material`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH152`,
  coursetitle: `Nano Technology`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH153`,
  coursetitle: `Synthesis & Characteristic of Functional Material`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH154`,
  coursetitle: `Material Characteristic Techniques`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH155`,
  coursetitle: `Ion Beam Patterning & Nano-bio Technology `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH156`,
  coursetitle: `Quatum Information Computation & Cryptography `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH157`,
  coursetitle: `Physics of the Universe`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH158 `,
  coursetitle: `General Relativity and Black Hole Physics `,
  l: `3`,
  t: `0 `,
  p: `0 `,
  credits: `3`,
 },

 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH159`,
  coursetitle: `Quantum field Theory and its Applications `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH160`,
  coursetitle: `Advanced Statistical Mechanics `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH161`,
  coursetitle: `Membrane Separations: Principles ,Design & Application`,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },

 {
  deptt: "Physics",
  sem_elect: `EL `,
  coursecode: `PH162`,
  coursetitle: `Electrochemical energy conversion and storage `,
  l: `3`,
  t: `0`,
  p: `0`,
  credits: `3`,
 },
]
export default PhyCourseStructure
