import React from "react"

const EEMtechSyllabusControl = [
 {
  title: "sghsgd",
  data: [
   {
    para: "sjdhufrj",
    link: "",
   },
  ],
 },
]
export default EEMtechSyllabusControl

// export const EEMtechSyllabusControl = [
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `Core`,
//   sem: `1`,
//   course_code: `1EE601`,
//   course_title: `Advance Control System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `Core`,
//   sem: `1`,
//   course_code: `1EE602`,
//   course_title: `Advance Instrumentation`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-1`,
//   sem: `1`,
//   course_code: `1EE6xx`,
//   course_title: `Elective I`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-2`,
//   sem: `1`,
//   course_code: `1EE6xx`,
//   course_title: `Elective II`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-3`,
//   sem: `1`,
//   course_code: `1xx6xx`,
//   course_title: `Elective III/Open Elective`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `Lab`,
//   sem: `1`,
//   course_code: `1EE691`,
//   course_title: `Advance Electrical Engineering Lab I`,
//   l: `0`,
//   t: `0`,
//   p: `6`,
//   credits: `4`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `-`,
//   sem: `1`,
//   course_code: `-`,
//   course_title: <strong>Total Semester Credit</strong>,
//   l: `12`,
//   t: `0`,
//   p: `6`,
//   credits: `19`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `Core`,
//   sem: `2`,
//   course_code: `2EE603`,
//   course_title: `Digital Control System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-4`,
//   sem: `2`,
//   course_code: `2EE6xx`,
//   course_title: `Elective IV`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-5`,
//   sem: `2`,
//   course_code: `2EE6xx`,
//   course_title: `Elective V`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-6`,
//   sem: `2`,
//   course_code: `2EE6xx`,
//   course_title: `Elective VI`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-7`,
//   sem: `2`,
//   course_code: `2xx6xx`,
//   course_title: `Elective VII/ Open Elective`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `Lab`,
//   sem: `2`,
//   course_code: `2EE692`,
//   course_title: `Advance Electrical Engineering Lab II`,
//   l: `0`,
//   t: `0`,
//   p: `6`,
//   credits: `4`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `Lab`,
//   sem: `2`,
//   course_code: `2EE694`,
//   course_title: `Seminar`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `2`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `-`,
//   sem: `2`,
//   course_code: `-`,
//   course_title: <strong>Semester Credit Total</strong>,
//   l: `12`,
//   t: `0`,
//   p: `9`,
//   credits: `21`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `Lab`,
//   sem: `3`,
//   course_code: `3EE695`,
//   course_title: `Seminar and Comprehensive Viva I`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `2`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `Lab`,
//   sem: `3`,
//   course_code: `3EE697`,
//   course_title: `Dissertation (to be continued in 4th Sem)`,
//   l: `0`,
//   t: `0`,
//   p: `12`,
//   credits: `8`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `-`,
//   sem: `3`,
//   course_code: `-`,
//   course_title: <strong>Semester Credit Total</strong>,
//   l: `0`,
//   t: `0`,
//   p: `15`,
//   credits: `10`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `Lab`,
//   sem: `4`,
//   course_code: `4EE696`,
//   course_title: `Seminar and Comprehensive Viva II`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `2`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `Lab`,
//   sem: `4`,
//   course_code: `4EE698`,
//   course_title: `Dissertation`,
//   l: `0`,
//   t: `0`,
//   p: `15`,
//   credits: `10`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `-`,
//   sem: `4`,
//   course_code: `-`,
//   course_title: <strong>Semester Credit Total</strong>,
//   l: `0`,
//   t: `0`,
//   p: `18`,
//   credits: `12`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `-`,
//   sem: `-`,
//   course_code: `-`,
//   course_title: <strong>Cumulative Total Credit</strong>,
//   l: ``,
//   t: ``,
//   p: ``,
//   credits: `62`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE605`,
//   course_title: `Intelligent Instrumentation`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE606`,
//   course_title: `Non-linear Control System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE607`,
//   course_title: `Microcontroller and Embedded System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE608`,
//   course_title: `System Modeling and Identification`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE609`,
//   course_title: `Optimal Control Theory`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE610`,
//   course_title: `State Estimation`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE611`,
//   course_title: `SCADA and Energy Management`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE612`,
//   course_title: `Process Control`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE614`,
//   course_title: `Bio Medical Instrumentation`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE618`,
//   course_title: `Modern Optimization Techniques`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE615`,
//   course_title: `Robotics and Robot Applications`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE616`,
//   course_title: `Industrial Drives and Control (PG)`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE619`,
//   course_title: `Stochastic Process`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `XEC6xx`,
//   course_title: `Digital Signal Processing`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EECO`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `XEC6xx`,
//   course_title: `VLSI Design`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
// ]
// export const EEMtechSyllabuspower = [
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `Core`,
//   sem: `1`,
//   course_code: `1EE631`,
//   course_title: `Advance power System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `Core`,
//   sem: `1`,
//   course_code: `1EE632`,
//   course_title: `Modern Power System Operation and Control`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-1`,
//   sem: `1`,
//   course_code: `1EE6xx`,
//   course_title: `Elective I`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-2`,
//   sem: `1`,
//   course_code: `1EE6xx`,
//   course_title: `Elective II`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-3`,
//   sem: `1`,
//   course_code: `1xx6xx`,
//   course_title: `Elective  III/ Open Elective`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `Lab`,
//   sem: `1`,
//   course_code: `1EE691`,
//   course_title: `Advance Electrical Engineering Lab I`,
//   l: `0`,
//   t: `0`,
//   p: `6`,
//   credits: `4`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `-`,
//   sem: `1`,
//   course_code: `-`,
//   course_title: <strong>Semester Credit Total</strong>,
//   l: `12`,
//   t: `0`,
//   p: `6`,
//   credits: `19`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `Core`,
//   sem: `2`,
//   course_code: `2EE643`,
//   course_title: `Power System Protection`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-4`,
//   sem: `2`,
//   course_code: `2EE6xx`,
//   course_title: `Elective IV`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-5`,
//   sem: `2`,
//   course_code: `2EE6xx`,
//   course_title: `Elective V`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-6`,
//   sem: `2`,
//   course_code: `2EE6xx`,
//   course_title: `Elective VI`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-7`,
//   sem: `2`,
//   course_code: `2xx6xx`,
//   course_title: `Elective VII`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `Lab`,
//   sem: `2`,
//   course_code: `2EE692`,
//   course_title: `Advance Electrical Engineering Lab II`,
//   l: `0`,
//   t: `0`,
//   p: `6`,
//   credits: `4`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `Lab`,
//   sem: `2`,
//   course_code: `2EE694`,
//   course_title: `Seminar`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `2`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `-`,
//   sem: `2`,
//   course_code: `-`,
//   course_title: <strong>Semester Credit Total</strong>,
//   l: `12`,
//   t: `0`,
//   p: `9`,
//   credits: `21`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `Lab`,
//   sem: `3`,
//   course_code: `3EE695`,
//   course_title: `Seminar and Comprehensive Viva I`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `2`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `Lab`,
//   sem: `3`,
//   course_code: `3EE697`,
//   course_title: `Dissertation (to be continued in 4th Sem)`,
//   l: `0`,
//   t: `0`,
//   p: `12`,
//   credits: `8`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `-`,
//   sem: `3`,
//   course_code: `-`,
//   course_title: <strong>Semester Credit Total</strong>,
//   l: `0`,
//   t: `0`,
//   p: `15`,
//   credits: `10`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `Lab`,
//   sem: `4`,
//   course_code: `4EE696`,
//   course_title: `Seminar and Comprehensive Viva II`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `2`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `Lab`,
//   sem: `4`,
//   course_code: `4EE698`,
//   course_title: `Dissertation`,
//   l: `0`,
//   t: `0`,
//   p: `15`,
//   credits: `10`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `-`,
//   sem: `4`,
//   course_code: `-`,
//   course_title: <strong>Semester Credit Total</strong>,
//   l: `0`,
//   t: `0`,
//   p: `18`,
//   credits: `12`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `-`,
//   sem: `-`,
//   course_code: `-`,
//   course_title: <strong>Cumulative Total Credit</strong>,
//   l: ``,
//   t: ``,
//   p: ``,
//   credits: `62`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE602`,
//   course_title: `Advance Instrumentation`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE607`,
//   course_title: `Microcontroller and Embedded System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE635`,
//   course_title: `Non - Conventional Energy System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE636`,
//   course_title: `Computer Aided Power System Analysis`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE637`,
//   course_title: `High Voltage Engineering`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE638`,
//   course_title: `Advanced Electrical Machine`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE611`,
//   course_title: `SCADA and Energy Management`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE618`,
//   course_title: `Modern Optimization Techniques`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE641`,
//   course_title: `Power System Stability and Control`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE642`,
//   course_title: `System Theory`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE643`,
//   course_title: `EHV Power Transmission`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE616`,
//   course_title: `Industrial Drives and Control (PG)`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE644`,
//   course_title: `HVDC Power Transmission`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `EE645`,
//   course_title: `Flexible AC Transmission`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE647`,
//   course_title: `Smart Grid Design and Analysis`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE646`,
//   course_title: `Power Quality Management`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE648`,
//   course_title: `Power Line Communication`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE649`,
//   course_title: `Power System Planning and Reliability`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `M.Tech-EE`,
//   ccmt: `EEPS`,
//   grp: `EL-x`,
//   sem: `-`,
//   course_code: `xEE650`,
//   course_title: `Power System Dynamics and Stability`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
// ]
