const EECourseStructure = [
 {
  title: "UG Program B.Tech. in Electrical Engineering",
  data: [
   {
    para: "B.Tech_EE_Course Structure_Batch-2021",
    link: "",
   },
  ],
 },
]
export default EECourseStructure

// import React, { useEffect, useState } from "react"
// import Table from "../../table"
// import { TabPage } from "../../styles/tabpage"
// import { EECourseStructure as Courseug } from "./Elec_Btech_course_structure"
// import main from "../img/book.svg"
// import {
//  EEMtechSyllabusControl as EeMtechControl,
//  EEMtechSyllabuspower as EeMtechPower,
// } from "./Elec_MTECH_syllabus"
// import { EEPhdCourse as Coursephd } from "./Elelc_phd"
// import Coursedd from "./eedd.js"
// import { PageLayout } from "../../styles/pagelayout"

// const EECourseStructure = props =>{
//     const [course, setCourse] = useState("programmesug")
//  const [syllabus, setSyllabus] = useState(Courseug)

//  useEffect(() => {}, [course])
//  return (
//     <>
//     <PageLayout style={{  marginTop: `10vh`, marginBottom: `15vh`}}
//     >
//         <TabPage>
//             <div className="mainDiv syllabus-page" style={{width:"90vw"}}>
//             <div className="row rowmarl3">
//        <div className="digital">
//         <h1 style={{ marginBottom: `1rem` }}>Syllabus</h1>
//         <h2 data-aos="zoom-in-right"> -Mechanical Engineering</h2>
//         <ul className="rowmarl3">
//          <li>
//           <a href="https://drive.google.com/file/d/1dQQR-i9mGoj6QdnEE7fTQieG4q9Sy8MC/view?usp=sharing">
//            B.Tech_Course Structure_2021-Modified.
//           </a>
//          </li>
//          <li>
//           <a href="https://drive.google.com/file/d/19oiSnssWgxThMoNtDzQrKASD1p7KXxOU/view?usp=sharing">
//            B.Tech_Course Structure_2022 Onwards.
//           </a>
//          </li>
//          <li>
//           <a href="https://drive.google.com/file/d/1s42tWWitU86Ezu2bGOTmPrnkDnhrERWJ/view?usp=sharing">
//            B.Tech_Detailed Syllabus_3rd Semester Onwards.
//           </a>
//          </li>
//          <li>
//           <a href="https://drive.google.com/file/d/1xUykTxPcv-mk2y3-sSXRt7BLczMZ_vVe/view?usp=sharing">
//            Dual Degree (B.Tech + M.Tech) _ Course Structure _ 2022 Onwards.
//           </a>
//          </li>
//          <li>
//           <a href="https://drive.google.com/file/d/10a4fvU12B-ZD7e6qkrHkKHrl_1Y180kc/view?usp=sharing">
//            Dual Degree ( B.Tech + M.Tech) _ Detailed Syllabus _ 3rd Semester
//            Onwards.
//           </a>
//          </li>
//          <li>
//           <a href="https://drive.google.com/file/d/1_B0-MakBnJ2vTNKZHsiD8hKM0aZ2c4E-/view?usp=sharing">
//            M.Tech _ Course Structure _ All Specializations.
//           </a>
//          </li>
//          <li>
//           <a href="https://drive.google.com/file/d/1DeGz_0NB4AteNBmTYEJxSueZaXlONqXq/view?usp=sharing">
//            M.Tech _ Detailed Syllabus _ All Specializations.
//           </a>
//          </li>
//          <li>
//           <a href="https://drive.google.com/file/d/1tov1rQO4_fA65l_IcjMMN-_4cyLA3nCk/view?usp=sharing">
//            PHD.
//           </a>
//          </li>
//         </ul>
//        </div>
//       </div>
//             </div>

//         </TabPage>

//     </PageLayout>
//     </>
//  )
// }
// export default EECourseStructure

// export const EECourseStructure = [
//  {
//   prog: `EEUG`,
//   sem: `1`,
//   course_code: `HS1601`,
//   course_title: `Science, Society and Ethic values`,
//   l: `2`,
//   t: `1`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `1`,
//   course_code: `MA1601`,
//   course_title: `Engineering Mathematics I`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `1`,
//   course_code: `CH1601`,
//   course_title: `Engineering Chemistry`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `1`,
//   course_code: `CHL1601`,
//   course_title: `Chemistry Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `1`,
//   course_code: `EC1601`,
//   course_title: `Elements of Electronics Engineering`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `1`,
//   course_code: `ECL1601`,
//   course_title: `EC Workshop`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `1`,
//   course_code: `EE1601`,
//   course_title: `Elements of Electrical Engineering-I`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `1`,
//   course_code: `EEL1601`,
//   course_title: `Electrical Engineering Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `1`,
//   course_code: `MEL1601`,
//   course_title: `Engineering Graphics Lab`,
//   l: `1`,
//   t: `0`,
//   p: `3`,
//   credits: `2`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `1`,
//   course_code: `EAA1601`,
//   course_title: `EAA-Sports/Innovative project`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `-`,
//   sem: `1`,
//   course_code: <strong>Total</strong>,
//   course_title: `-`,
//   l: `-`,
//   t: `-`,
//   p: `-`,
//   credits: `21`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `2`,
//   course_code: `HS2601`,
//   course_title: `Communicative English`,
//   l: `2`,
//   t: `1`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `2`,
//   course_code: `HSL2601`,
//   course_title: `Language Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `2`,
//   course_code: `MA2601`,
//   course_title: `Engineering Mathematics II`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `2`,
//   course_code: `PH2601`,
//   course_title: `Engineering Physics`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `2`,
//   course_code: `PHL2601`,
//   course_title: `Physics Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `2`,
//   course_code: `CS2601`,
//   course_title: `Introduction to computing`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `2`,
//   course_code: `CSL2601`,
//   course_title: `Computing Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `2`,
//   course_code: `PH2602`,
//   course_title: `Material Science and Technology`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `2`,
//   course_code: `MEL2601`,
//   course_title: `Workshop Practice`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `2`,
//   course_code: `EAA2601`,
//   course_title: `EAA-Swatch Bharat Mission (SBM)`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `-`,
//   sem: `2`,
//   course_code: <strong>Total</strong>,
//   course_title: `-`,
//   l: `-`,
//   t: `-`,
//   p: `-`,
//   credits: `20`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `3`,
//   course_code: `EE3601`,
//   course_title: `Electrical Machines-I`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `3`,
//   course_code: `EEL3601`,
//   course_title: `Electrical Machine-I Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `3`,
//   course_code: `EE3602`,
//   course_title: `Network Analysis and Synthesis`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `3`,
//   course_code: `EE3603`,
//   course_title: `Electrical Measurement and Instrumentation`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `3`,
//   course_code: `EEL3603`,
//   course_title: `Electrical Measurement and Instrumentation Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `3`,
//   course_code: `EE3604`,
//   course_title: `Electromagnetic Field Theory`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `3`,
//   course_code: `EC3601`,
//   course_title: `Analog Electronics`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `3`,
//   course_code: `ECL3602`,
//   course_title: `Analog Electronics Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `3`,
//   course_code: `MA3601`,
//   course_title: `Numerical Methods for Engineers`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `-`,
//   sem: `3`,
//   course_code: <strong>Total</strong>,
//   course_title: `-`,
//   l: `-`,
//   t: `-`,
//   p: `-`,
//   credits: `21`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `4`,
//   course_code: `CH4601`,
//   course_title: `Green Technology (Environmental Science)`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `4`,
//   course_code: `EE4601`,
//   course_title: `Electrical Machine-II`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `4`,
//   course_code: `EEL4601`,
//   course_title: `Electrical Machine-II Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `4`,
//   course_code: `EE4602`,
//   course_title: `Power Transmission and Distribution`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `4`,
//   course_code: `CS4601`,
//   course_title: `Object Oriented Programing`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `4`,
//   course_code: `CSL4601`,
//   course_title: `Object Oriented Programing Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `4`,
//   course_code: `EC4601`,
//   course_title: `Digital Electronics`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `4`,
//   course_code: `ECL4601`,
//   course_title: `Digital Electronics Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `4`,
//   course_code: `EC4602`,
//   course_title: `Signals and Systems Analysis`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `-`,
//   sem: `4`,
//   course_code: <strong>Total</strong>,
//   course_title: `-`,
//   l: `-`,
//   t: `-`,
//   p: `-`,
//   credits: `21`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `5`,
//   course_code: `EE5601`,
//   course_title: `Power System Analysis`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `5`,
//   course_code: `EEl5601`,
//   course_title: `Power System Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `5`,
//   course_code: `EE5602`,
//   course_title: `Linear Control System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `5`,
//   course_code: `EEL5602`,
//   course_title: `Control System Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `5`,
//   course_code: `EE5603`,
//   course_title: `Power Electronics`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `5`,
//   course_code: `EEl5603`,
//   course_title: `Power Electronics Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `5`,
//   course_code: `EE5604`,
//   course_title: `Microprocessor and its Application`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `5`,
//   course_code: `EE56XX`,
//   course_title: `Departmental Elective -I`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `5`,
//   course_code: `OEXXXX`,
//   course_title: `Open Elective (From Other Department)`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `5`,
//   course_code: `XXXXXX`,
//   course_title: `MOOC/Swayam (Online)`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `-`,
//   sem: `5`,
//   course_code: <strong>Total</strong>,
//   course_title: `-`,
//   l: `-`,
//   t: `-`,
//   p: `-`,
//   credits: `21+3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `6`,
//   course_code: `EE6601`,
//   course_title: `Industrial Drives and Control`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `6`,
//   course_code: `EEL6601`,
//   course_title: `Industrial Drives and Control lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `6`,
//   course_code: `EE6602`,
//   course_title: `Power System Protection and Switchgear`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `6`,
//   course_code: `EEL6602`,
//   course_title: `Power System Protection and Switchgear Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `6`,
//   course_code: `EE6603`,
//   course_title: `Microcontroller, Interfacing  and Applications`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `6`,
//   course_code: `EEL6603`,
//   course_title: `Microprocessor and Microcontroller Lab`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `6`,
//   course_code: `EE66XX`,
//   course_title: `Departmental Elective-II`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `6`,
//   course_code: `EE66XX`,
//   course_title: ` Departmental Elective-III`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `6`,
//   course_code: `OEXXXX`,
//   course_title: `Open Elective (From Other Department)`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `6`,
//   course_code: `EE6604`,
//   course_title: `Industrial Training`,
//   l: `0`,
//   t: `0`,
//   p: `6`,
//   credits: `2`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `6`,
//   course_code: `XXXXXX`,
//   course_title: `MOOC/Swayam (Online`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `-`,
//   sem: `6`,
//   course_code: <strong>Total</strong>,
//   course_title: `-`,
//   l: `-`,
//   t: `-`,
//   p: `-`,
//   credits: `23+3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `7`,
//   course_code: `EE7601`,
//   course_title: `Renewable Energy`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `7`,
//   course_code: `EE76XX`,
//   course_title: `Departmental Elective-IV`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `7`,
//   course_code: `EE76XX`,
//   course_title: `Departmental Elective-V`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `7`,
//   course_code: `EE76XX`,
//   course_title: `Departmental Elective-VI`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `7`,
//   course_code: `HS7601`,
//   course_title: `Industrial Economics and Financial Management`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `7`,
//   course_code: `OEXXXX`,
//   course_title: `Open Elective (From other Department)`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `7`,
//   course_code: `XXXXXX`,
//   course_title: `MOOC/Swayam (Online)`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `7`,
//   course_code: `EE7604`,
//   course_title: `Seminar and Technical Report Writing`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `7`,
//   course_code: `EE7605`,
//   course_title: `Minor Project`,
//   l: `0`,
//   t: `0`,
//   p: `6`,
//   credits: `5`,
//  },
//  {
//   prog: `-`,
//   sem: `7`,
//   course_code: <strong>Total</strong>,
//   course_title: `-`,
//   l: `-`,
//   t: `-`,
//   p: `-`,
//   credits: `24+3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `8`,
//   course_code: `EE86XX`,
//   course_title: `Departmental Elective-VII`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `8`,
//   course_code: `EE8601`,
//   course_title: `Seminar and Technical Report Writing`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `1`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `8`,
//   course_code: `EE8602`,
//   course_title: `Comprehensive Viva`,
//   l: `0`,
//   t: `0`,
//   p: `6`,
//   credits: `2`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `8`,
//   course_code: `EE8603`,
//   course_title: `Major Project`,
//   l: `0`,
//   t: `0`,
//   p: `3`,
//   credits: `10`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `8`,
//   course_code: `OEXXXX`,
//   course_title: `Open Elective (From other Department)`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `8`,
//   course_code: `XXXXXX`,
//   course_title: `MOOC/Swayam (Online)`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `-`,
//   sem: `8`,
//   course_code: <strong>Total</strong>,
//   course_title: `-`,
//   l: `-`,
//   t: `-`,
//   p: `-`,
//   credits: `19+3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `CSx610`,
//   course_title: `Computer Architecture`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `CSx611`,
//   course_title: `Machine Learning`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `CSx612`,
//   course_title: `Data Structure`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `ECx610`,
//   course_title: `Digital Signal Processing`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `ECx611`,
//   course_title: `Digital Image Processing`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `ECx612`,
//   course_title: `Digital Communication`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx611`,
//   course_title: `Electrical Machine Design`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx612`,
//   course_title: `Special Electrical Machine`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx613`,
//   course_title: `Utilization and Traction`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx614`,
//   course_title: `Advanced Power Electronics`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx615`,
//   course_title: `Modern AC Drive`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx616`,
//   course_title: `Power Plant Engineering`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx617`,
//   course_title: `Power System Dynamics and Stability`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx618`,
//   course_title: `Computer Aided Power System Analysis`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx619`,
//   course_title: `Power System Design`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx620`,
//   course_title: `Modern Power Operation and Control`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx621`,
//   course_title: `HVDC Transmission`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx622`,
//   course_title: `Flexible AC Transmission Systems (FACTS)`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx623`,
//   course_title: `E-Mobility and Energy Storage`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx624`,
//   course_title: `SCADA and Energy Management System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx625`,
//   course_title: `Restructuring of Power System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx626`,
//   course_title: `Distributed Generation and Microgrid`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx627`,
//   course_title: `Electronic Instrumentation and Measurements`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx628`,
//   course_title: `Advanced Instrumentation`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx629`,
//   course_title: `Modern Control Theory`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx630`,
//   course_title: `Digital Control System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx631`,
//   course_title: `Robotics and Control`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx632`,
//   course_title: `Process Control`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `EL`,
//   course_code: `EEx633`,
//   course_title: `Computational Electromagnetics`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `OPEL`,
//   course_code: `OEx601`,
//   course_title: `Non-Conventional Energy System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `OPEL`,
//   course_code: `OEx602`,
//   course_title: `Illumination Engineering and House Wiring`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `OPEL`,
//   course_code: `OEx603`,
//   course_title: `Soft Computing`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `OPEL`,
//   course_code: `OEx604`,
//   course_title: `An Overview of Power System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `OPEL`,
//   course_code: `OEx605`,
//   course_title: `Smart Grid`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `OPEL`,
//   course_code: `OEx606`,
//   course_title: `Utilization of Electrical Energy`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
//  {
//   prog: `EEUG`,
//   sem: `OPEL`,
//   course_code: `OEx607`,
//   course_title: `utomatic Control System`,
//   l: `3`,
//   t: `0`,
//   p: `0`,
//   credits: `3`,
//  },
// ]
